-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [work].[vCascadeWorkOrderHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [CascadeNumber], [CascadeStatus], [MappedNodeEntityId], [CascadeWorkOrderType], [LastSyncedAt], [SyncDirection], [Notes], [SysStart], [SysEnd]
FROM [work].[CascadeWorkOrder] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [work].[vCascadeWorkOrderHistory] TO [app_execute];
GO
