-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [work].[vNotificationDelivery] AS
SELECT [NotificationDeliveryId], [NotificationEntityId], [Channel], [SentAt], [DeliveryStatus]
FROM [work].[NotificationDelivery];
GO
GRANT SELECT ON [work].[vNotificationDelivery] TO [app_execute];
GO
