-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [work].[vNotification] AS
-- current: the latest row per entity valid now, not deleted (decision 69, 71)
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [NotificationTypeDefinitionVersionRowId], [RecipientActorId], [RecipientRoleCode], [SubjectKind], [SubjectEntityId], [Status], [CurrentEscalationStep], [Summary], [Detail], [ResolvedAt], [ResolvedByActorId], [ResolutionRecordEntityId]
FROM (
    SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [NotificationTypeDefinitionVersionRowId], [RecipientActorId], [RecipientRoleCode], [SubjectKind], [SubjectEntityId], [Status], [CurrentEscalationStep], [Summary], [Detail], [ResolvedAt], [ResolvedByActorId], [ResolutionRecordEntityId],
           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn
    FROM [work].[Notification]
    WHERE [IsDeleted] = 0
      AND [ValidFrom] <= SYSDATETIMEOFFSET()
      AND ([ValidTo] IS NULL OR [ValidTo] > SYSDATETIMEOFFSET())
) x WHERE x._rn = 1;
GO
GRANT SELECT ON [work].[vNotification] TO [app_execute];
GO
