-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [work].[vRequestTrackHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [WorkRequestEntityId], [TrackCode], [Status], [TrackDate], [Note], [SysStart], [SysEnd]
FROM [work].[RequestTrack] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [work].[vRequestTrackHistory] TO [app_execute];
GO
