-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[BlockInstance_Update]
    @RowId UNIQUEIDENTIFIER,
    @ProcedureInstanceEntityId UNIQUEIDENTIFIER,
    @ParentBlockInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @BlockPath NVARCHAR(400),
    @BlockKind NVARCHAR(20),
    @IterationKey NVARCHAR(100) = NULL,
    @Pass INT = 1,
    @MemberSubjectKind NVARCHAR(40) = NULL,
    @MemberSubjectEntityId UNIQUEIDENTIFIER = NULL,
    @State NVARCHAR(40),
    @Outcome NVARCHAR(40) = NULL,
    @StartedAt DATETIMEOFFSET(7) = NULL,
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @MemberSubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@MemberSubjectKind, @MemberSubjectEntityId) = 0
        THROW 50101, N'process.BlockInstance: no MemberSubject entity of kind @MemberSubjectKind with that id.', 1;
    UPDATE [process].[BlockInstance] SET [ProcedureInstanceEntityId] = @ProcedureInstanceEntityId, [ParentBlockInstanceEntityId] = @ParentBlockInstanceEntityId, [BlockPath] = @BlockPath, [BlockKind] = @BlockKind, [IterationKey] = @IterationKey, [Pass] = @Pass, [MemberSubjectKind] = @MemberSubjectKind, [MemberSubjectEntityId] = @MemberSubjectEntityId, [State] = @State, [Outcome] = @Outcome, [StartedAt] = @StartedAt, [CompletedAt] = @CompletedAt, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.BlockInstance: no live row with that key.', 1;
END;
