-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[HoldInstance_Update]
    @RowId UNIQUEIDENTIFIER,
    @BlockInstanceEntityId UNIQUEIDENTIFIER,
    @Reason NVARCHAR(400),
    @HeldAt DATETIMEOFFSET(7),
    @HeldByActorId UNIQUEIDENTIFIER = NULL,
    @ReleasedAt DATETIMEOFFSET(7) = NULL,
    @ReleasedByActorId UNIQUEIDENTIFIER = NULL,
    @ReleaseBasis NVARCHAR(20) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [process].[HoldInstance] SET [BlockInstanceEntityId] = @BlockInstanceEntityId, [Reason] = @Reason, [HeldAt] = @HeldAt, [HeldByActorId] = @HeldByActorId, [ReleasedAt] = @ReleasedAt, [ReleasedByActorId] = @ReleasedByActorId, [ReleaseBasis] = @ReleaseBasis, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.HoldInstance: no live row with that key.', 1;
END;
