-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[ProcedureFactUse_Update]
    @RowId UNIQUEIDENTIFIER,
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @BlockPath NVARCHAR(400),
    @FactName NVARCHAR(200),
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [process].[ProcedureFactUse] SET [DefinitionVersionRowId] = @DefinitionVersionRowId, [BlockPath] = @BlockPath, [FactName] = @FactName, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.ProcedureFactUse: no live row with that key.', 1;
END;
