-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[ProcedureStep_Add]
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @StepId NVARCHAR(64),
    @BlockPath NVARCHAR(400),
    @Ordinal INT,
    @Title NVARCHAR(200),
    @RoleAlias NVARCHAR(40),
    @RoleCode NVARCHAR(40),
    @RecordKindCode NVARCHAR(40),
    @SignoffAction NVARCHAR(100) = NULL,
    @RequiresWitness BIT = 0,
    @HasPrecondition BIT = 0,
    @HasDue BIT = 0,
    @AllowsDeviation BIT = 0,
    @AdvancesWorkflowKey NVARCHAR(100) = NULL,
    @AdvancesTransition NVARCHAR(100) = NULL,
    @ProducesName NVARCHAR(40) = NULL,
    @ProducesKind NVARCHAR(40) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [process].[ProcedureStepRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [process].[ProcedureStep] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionVersionRowId], [StepId], [BlockPath], [Ordinal], [Title], [RoleAlias], [RoleCode], [RecordKindCode], [SignoffAction], [RequiresWitness], [HasPrecondition], [HasDue], [AllowsDeviation], [AdvancesWorkflowKey], [AdvancesTransition], [ProducesName], [ProducesKind])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionVersionRowId, @StepId, @BlockPath, @Ordinal, @Title, @RoleAlias, @RoleCode, @RecordKindCode, @SignoffAction, @RequiresWitness, @HasPrecondition, @HasDue, @AllowsDeviation, @AdvancesWorkflowKey, @AdvancesTransition, @ProducesName, @ProducesKind);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
