-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[ProcedureInstance_Add]
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @ParentInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @CallBlockPath NVARCHAR(400) = NULL,
    @WorkflowInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @InvokedAtState NVARCHAR(40) = NULL,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @Inputs NVARCHAR(MAX) = NULL,
    @Produced NVARCHAR(MAX) = NULL,
    @State NVARCHAR(40),
    @Outcome NVARCHAR(40) = NULL,
    @StartedAt DATETIMEOFFSET(7),
    @StartedByActorId UNIQUEIDENTIFIER,
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'process.ProcedureInstance: no Subject entity of kind @SubjectKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [process].[ProcedureInstanceRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [process].[ProcedureInstance] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionVersionRowId], [ParentInstanceEntityId], [CallBlockPath], [WorkflowInstanceEntityId], [InvokedAtState], [SubjectKind], [SubjectEntityId], [WorkRequestEntityId], [Inputs], [Produced], [State], [Outcome], [StartedAt], [StartedByActorId], [CompletedAt])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionVersionRowId, @ParentInstanceEntityId, @CallBlockPath, @WorkflowInstanceEntityId, @InvokedAtState, @SubjectKind, @SubjectEntityId, @WorkRequestEntityId, @Inputs, @Produced, @State, @Outcome, @StartedAt, @StartedByActorId, @CompletedAt);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
