-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[ProcedureInstance_Update]
    @RowId UNIQUEIDENTIFIER,
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @ParentInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @CallBlockPath NVARCHAR(400) = NULL,
    @WorkflowInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @InvokedAtState NVARCHAR(40) = NULL,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @Inputs NVARCHAR(MAX) = NULL,
    @Produced NVARCHAR(MAX) = NULL,
    @State NVARCHAR(40),
    @Outcome NVARCHAR(40) = NULL,
    @StartedAt DATETIMEOFFSET(7),
    @StartedByActorId UNIQUEIDENTIFIER,
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'process.ProcedureInstance: no Subject entity of kind @SubjectKind with that id.', 1;
    UPDATE [process].[ProcedureInstance] SET [DefinitionVersionRowId] = @DefinitionVersionRowId, [ParentInstanceEntityId] = @ParentInstanceEntityId, [CallBlockPath] = @CallBlockPath, [WorkflowInstanceEntityId] = @WorkflowInstanceEntityId, [InvokedAtState] = @InvokedAtState, [SubjectKind] = @SubjectKind, [SubjectEntityId] = @SubjectEntityId, [WorkRequestEntityId] = @WorkRequestEntityId, [Inputs] = @Inputs, [Produced] = @Produced, [State] = @State, [Outcome] = @Outcome, [StartedAt] = @StartedAt, [StartedByActorId] = @StartedByActorId, [CompletedAt] = @CompletedAt, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.ProcedureInstance: no live row with that key.', 1;
END;
