-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[ProcedureFactUse_Add]
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @BlockPath NVARCHAR(400),
    @FactName NVARCHAR(200),
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [process].[ProcedureFactUseRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [process].[ProcedureFactUse] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionVersionRowId], [BlockPath], [FactName])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionVersionRowId, @BlockPath, @FactName);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
