-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[StepInstance_Add]
    @BlockInstanceEntityId UNIQUEIDENTIFIER,
    @StepId NVARCHAR(64),
    @State NVARCHAR(40),
    @AssignedRoleCode NVARCHAR(40),
    @ClaimedByActorId UNIQUEIDENTIFIER = NULL,
    @ClaimedAt DATETIMEOFFSET(7) = NULL,
    @ClaimExpiresAt DATETIMEOFFSET(7) = NULL,
    @Draft NVARCHAR(MAX) = NULL,
    @DraftModifiedAt DATETIMEOFFSET(7) = NULL,
    @CapturedAt DATETIMEOFFSET(7) = NULL,
    @CapturedByActorId UNIQUEIDENTIFIER = NULL,
    @CaptureSource NVARCHAR(20) = NULL,
    @CaptureTimeQuality TINYINT = NULL,
    @CommittedRecordEntityId UNIQUEIDENTIFIER = NULL,
    @CommittedByActorId UNIQUEIDENTIFIER = NULL,
    @WitnessedByActorId UNIQUEIDENTIFIER = NULL,
    @AcceptedIntoPlatformByActorId UNIQUEIDENTIFIER = NULL,
    @CommittedAt DATETIMEOFFSET(7) = NULL,
    @Outcome NVARCHAR(40) = NULL,
    @DeviationFindingEntityId UNIQUEIDENTIFIER = NULL,
    @HeldReason NVARCHAR(400) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [process].[StepInstanceRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [process].[StepInstance] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [BlockInstanceEntityId], [StepId], [State], [AssignedRoleCode], [ClaimedByActorId], [ClaimedAt], [ClaimExpiresAt], [Draft], [DraftModifiedAt], [CapturedAt], [CapturedByActorId], [CaptureSource], [CaptureTimeQuality], [CommittedRecordEntityId], [CommittedByActorId], [WitnessedByActorId], [AcceptedIntoPlatformByActorId], [CommittedAt], [Outcome], [DeviationFindingEntityId], [HeldReason])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @BlockInstanceEntityId, @StepId, @State, @AssignedRoleCode, @ClaimedByActorId, @ClaimedAt, @ClaimExpiresAt, @Draft, @DraftModifiedAt, @CapturedAt, @CapturedByActorId, @CaptureSource, @CaptureTimeQuality, @CommittedRecordEntityId, @CommittedByActorId, @WitnessedByActorId, @AcceptedIntoPlatformByActorId, @CommittedAt, @Outcome, @DeviationFindingEntityId, @HeldReason);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
