-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[StepInstance_Update]
    @RowId UNIQUEIDENTIFIER,
    @BlockInstanceEntityId UNIQUEIDENTIFIER,
    @StepId NVARCHAR(64),
    @State NVARCHAR(40),
    @AssignedRoleCode NVARCHAR(40),
    @ClaimedByActorId UNIQUEIDENTIFIER = NULL,
    @ClaimedAt DATETIMEOFFSET(7) = NULL,
    @ClaimExpiresAt DATETIMEOFFSET(7) = NULL,
    @Draft NVARCHAR(MAX) = NULL,
    @DraftModifiedAt DATETIMEOFFSET(7) = NULL,
    @CapturedAt DATETIMEOFFSET(7) = NULL,
    @CapturedByActorId UNIQUEIDENTIFIER = NULL,
    @CaptureSource NVARCHAR(20) = NULL,
    @CaptureTimeQuality TINYINT = NULL,
    @CommittedRecordEntityId UNIQUEIDENTIFIER = NULL,
    @CommittedByActorId UNIQUEIDENTIFIER = NULL,
    @WitnessedByActorId UNIQUEIDENTIFIER = NULL,
    @AcceptedIntoPlatformByActorId UNIQUEIDENTIFIER = NULL,
    @CommittedAt DATETIMEOFFSET(7) = NULL,
    @Outcome NVARCHAR(40) = NULL,
    @DeviationFindingEntityId UNIQUEIDENTIFIER = NULL,
    @HeldReason NVARCHAR(400) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [process].[StepInstance] SET [BlockInstanceEntityId] = @BlockInstanceEntityId, [StepId] = @StepId, [State] = @State, [AssignedRoleCode] = @AssignedRoleCode, [ClaimedByActorId] = @ClaimedByActorId, [ClaimedAt] = @ClaimedAt, [ClaimExpiresAt] = @ClaimExpiresAt, [Draft] = @Draft, [DraftModifiedAt] = @DraftModifiedAt, [CapturedAt] = @CapturedAt, [CapturedByActorId] = @CapturedByActorId, [CaptureSource] = @CaptureSource, [CaptureTimeQuality] = @CaptureTimeQuality, [CommittedRecordEntityId] = @CommittedRecordEntityId, [CommittedByActorId] = @CommittedByActorId, [WitnessedByActorId] = @WitnessedByActorId, [AcceptedIntoPlatformByActorId] = @AcceptedIntoPlatformByActorId, [CommittedAt] = @CommittedAt, [Outcome] = @Outcome, [DeviationFindingEntityId] = @DeviationFindingEntityId, [HeldReason] = @HeldReason, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.StepInstance: no live row with that key.', 1;
END;
