-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [process].[WorkflowInstance_Update]
    @RowId UNIQUEIDENTIFIER,
    @WorkflowDefinitionVersionRowId UNIQUEIDENTIFIER,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @CurrentState NVARCHAR(40),
    @StartedAt DATETIMEOFFSET(7),
    @StartedByActorId UNIQUEIDENTIFIER,
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @IsCancelled BIT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'process.WorkflowInstance: no Subject entity of kind @SubjectKind with that id.', 1;
    UPDATE [process].[WorkflowInstance] SET [WorkflowDefinitionVersionRowId] = @WorkflowDefinitionVersionRowId, [SubjectKind] = @SubjectKind, [SubjectEntityId] = @SubjectEntityId, [CurrentState] = @CurrentState, [StartedAt] = @StartedAt, [StartedByActorId] = @StartedByActorId, [CompletedAt] = @CompletedAt, [IsCancelled] = @IsCancelled, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'process.WorkflowInstance: no live row with that key.', 1;
END;
