-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [event].[vChannel] AS
SELECT [ChannelId], [EventId], [ChannelKind], [Name], [UnitCode], [Phase], [CtRatio], [PtRatio], [PrimaryOrSecondary], [SortOrder], [SourcePortEntityId]
FROM [event].[Channel];
GO
GRANT SELECT ON [event].[vChannel] TO [app_execute];
GO
