-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [event].[vEvent] AS
SELECT [EventId], [OccurredAt], [TimeSourceQuality], [SourceDeviceEntityId], [SourceKind], [Format], [SampleRateHz], [DurationMs], [NominalFrequencyHz], [TriggerDescription], [ProtectionOperationEntityId], [RawFileEntityId], [IngestedAt], [IngestRunId]
FROM [event].[Event];
GO
GRANT SELECT ON [event].[vEvent] TO [app_execute];
GO
