"""
migration_rules.py — the register of migration rules, generated from the sources of truth (#194).

The owner, 2026-09-19: "All of these 'migration' decisions need to be remembered so that we can duplicate during our actual
cutover ... we are going to accept a verified version from the client of the legacy database which I am going to want to
apply all of these rules". The rules live in three places and nowhere else:
  1. legacy_import.py — every self.rule("...") is a rule applied per input row (counted in the RECONCILIATION reports);
  2. docs/schema/ddl/PostDeploy/*.sql — a seed that acts on migrated data carries a "-- migration-rule:" line and replays
     on every deploy, so a fresh cutover gets it;
  3. DEV-ONLY-MUTATIONS.json — hand edits on a copy that are NOT rules and must not be repeated.
This writes MIGRATION-RULES.md from them so the register cannot go stale. Run after any of the three changes; commit both.

Usage: python docs/schema/migration/migration_rules.py
"""
import io, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
NL = chr(13) + chr(10)

def importer_rules():
    src = io.open(os.path.join(HERE, "legacy_import.py"), encoding="utf-8").read().split("\n")
    out, func = [], "?"
    for i, line in enumerate(src, 1):
        m = re.match(r"\s*def (\w+)", line)
        if m: func = m.group(1)
        for r in re.findall(r'self\.rule\(\s*(?:f?"([^"]+)"|\{([^}]+)\})', line):
            text = r[0] or r[1]
            out.append((text, func, i))
    return out

def seed_rules():
    out = []
    d = os.path.join(ROOT, "docs", "schema", "ddl", "PostDeploy")
    for f in sorted(os.listdir(d)):
        if not f.endswith(".sql"): continue
        for line in io.open(os.path.join(d, f), encoding="utf-8"):
            m = re.match(r"\s*--\s*migration-rule:\s*(.+)", line)
            if m: out.append((m.group(1).strip(), f))
    return out

def main():
    mut = json.load(io.open(os.path.join(HERE, "DEV-ONLY-MUTATIONS.json"), encoding="utf-8"))["mutations"]
    L = ["# Migration rules — the register (generated by migration_rules.py; do not edit)", "",
         "The owner, 2026-09-19: every migration decision must be remembered and replayed at the real cutover, on the verified copy of the",
         "legacy database the client provides. **A migration decision is applied by the importer or by a PostDeploy seed, never by hand on",
         "a copy; a hand edit on DEV or QA is recorded in `DEV-ONLY-MUTATIONS.json` as not-a-rule.** The reasoning behind each rule is in",
         "`docs/decisions/DECISION-LOG.md` under its number; the mapping in prose is `docs/migration/CUTOVER-STRATEGY.md` §5; the field-by-field",
         "record is `LEGACY-FIELDS.md`. A rehearsal (`run_rehearsal.py`) proves the importer's rules by their row counts in its RECONCILIATION report.", "",
         "## 1. Rules the importer applies per row (`legacy_import.py`)", "", "| Rule | Function | Line |", "|---|---|---:|"]
    for text, func, line in importer_rules():
        L.append("| " + text.replace("|", "\\|") + " | `" + func + "` | " + str(line) + " |")
    L += ["", "## 2. Rules a PostDeploy seed applies to migrated data (replayed on every deploy)", "", "| Rule | Seed |", "|---|---|"]
    for text, f in seed_rules():
        L.append("| " + text.replace("|", "\\|") + " | `" + f + "` |")
    L += ["", "## 3. Hand edits on a copy — NOT rules (`DEV-ONLY-MUTATIONS.json`)", "", "| Date | What | Why | A rule? |", "|---|---|---|---|"]
    for m in mut:
        L.append("| " + m["date"] + " | " + m["what"] + " | " + m["why"] + " | " + ("yes — an application of a rule above" if m.get("rule") else "no") + " |")
    io.open(os.path.join(HERE, "MIGRATION-RULES.md"), "w", encoding="utf-8", newline="").write(NL.join(L) + NL)
    print(str(len(importer_rules())) + " importer rules, " + str(len(seed_rules())) + " seed rules, " + str(len(mut)) + " hand edits -> MIGRATION-RULES.md")

if __name__ == "__main__":
    main()
