-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [network].[ConstantsRun_Append]
    @StartedAt DATETIMEOFFSET(7),
    @ActorId UNIQUEIDENTIFIER,
    @EngineDefinitionVersionRowId UNIQUEIDENTIFIER,
    @Method NVARCHAR(40),
    @EarthResistivityOhmM DECIMAL(18,4) = NULL,
    @FrequencyHz DECIMAL(18,4) = NULL,
    @SectionsCalculated INT = NULL,
    @Status NVARCHAR(20) = NULL,
    @RunId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    SET @RunId = ISNULL(@RunId, NEWID());
    INSERT [network].[ConstantsRun] ([RunId], [StartedAt], [ActorId], [EngineDefinitionVersionRowId], [Method], [EarthResistivityOhmM], [FrequencyHz], [SectionsCalculated], [Status])
    VALUES (@RunId, @StartedAt, @ActorId, @EngineDefinitionVersionRowId, @Method, @EarthResistivityOhmM, @FrequencyHz, @SectionsCalculated, @Status);
END;
