-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [network].[LayerNodeEndpoint_Add]
    @LayerNodeEntityId UNIQUEIDENTIFIER,
    @AnchorKind NVARCHAR(40),
    @AnchorEntityId UNIQUEIDENTIFIER,
    @LineAssetEntityId UNIQUEIDENTIFIER = NULL,
    @IsPrimary BIT = 0,
    @SnapMethod NVARCHAR(20),
    @Location GEOGRAPHY = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @AnchorEntityId IS NOT NULL AND [meta].[fEntityExists](@AnchorKind, @AnchorEntityId) = 0
        THROW 50101, N'network.LayerNodeEndpoint: no Anchor entity of kind @AnchorKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [network].[LayerNodeEndpointRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [network].[LayerNodeEndpoint] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [LayerNodeEntityId], [AnchorKind], [AnchorEntityId], [LineAssetEntityId], [IsPrimary], [SnapMethod], [Location], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @LayerNodeEntityId, @AnchorKind, @AnchorEntityId, @LineAssetEntityId, @IsPrimary, @SnapMethod, @Location, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
