-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [network].[LineSection_Add]
    @LineAssetEntityId UNIQUEIDENTIFIER,
    @FromRouteStepRowId UNIQUEIDENTIFIER = NULL,
    @ToRouteStepRowId UNIQUEIDENTIFIER = NULL,
    @StructureTypeDefinitionVersionRowId UNIQUEIDENTIFIER = NULL,
    @ConductorTypeCode NVARCHAR(40) = NULL,
    @GroundWireCount INT = NULL,
    @LengthKm DECIMAL(18,4) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [network].[LineSectionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [network].[LineSection] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [LineAssetEntityId], [FromRouteStepRowId], [ToRouteStepRowId], [StructureTypeDefinitionVersionRowId], [ConductorTypeCode], [GroundWireCount], [LengthKm])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @LineAssetEntityId, @FromRouteStepRowId, @ToRouteStepRowId, @StructureTypeDefinitionVersionRowId, @ConductorTypeCode, @GroundWireCount, @LengthKm);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
