-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [network].[SourceEquivalent_Add]
    @CaseEntityId UNIQUEIDENTIFIER,
    @LayerNodeEntityId UNIQUEIDENTIFIER,
    @Z1R DECIMAL(18,8) = NULL,
    @Z1X DECIMAL(18,8) = NULL,
    @Z0R DECIMAL(18,8) = NULL,
    @Z0X DECIMAL(18,8) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [network].[SourceEquivalentRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [network].[SourceEquivalent] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [CaseEntityId], [LayerNodeEntityId], [Z1R], [Z1X], [Z0R], [Z0X])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @CaseEntityId, @LayerNodeEntityId, @Z1R, @Z1X, @Z0R, @Z0X);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
