-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vAuditRequestHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [AuditEntityId], [RequestReference], [RequirementEntityId], [SubjectKind], [SubjectEntityId], [RequestedAt], [DueAt], [Description], [AnsweredByPackageEntityId], [SysStart], [SysEnd]
FROM [compliance].[AuditRequest] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [compliance].[vAuditRequestHistory] TO [app_execute];
GO
