-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vEvidencePackage] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [AuditRequestEntityId], [SubjectKind], [SubjectEntityId], [StandardVersionRowId], [PeriodStartAt], [PeriodEndAt], [ValidAsOf], [BelievedAsOf], [PreparedByActorId], [PreparedAt], [ReviewedByActorId], [ReviewedAt], [ApprovedByActorId], [ApprovedAt], [SubmittedAt], [SubmittedToEntityEntityId], [PackageDocumentEntityId], [PackageHash]
FROM [compliance].[EvidencePackage]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [compliance].[vEvidencePackage] TO [app_execute];
GO
