-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vObligationInstanceFact] AS
SELECT [ObligationInstanceFactId], [ObligationInstanceRowId], [FactName], [SourceRowId], [ValueAsRead]
FROM [compliance].[ObligationInstanceFact];
GO
GRANT SELECT ON [compliance].[vObligationInstanceFact] TO [app_execute];
GO
