-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vRequirementHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [StandardVersionRowId], [RequirementNumber], [SubRequirement], [Title], [Summary], [EvidenceGuidance], [SubjectKinds], [SysStart], [SysEnd]
FROM [compliance].[Requirement] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [compliance].[vRequirementHistory] TO [app_execute];
GO
