-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vRuleEvaluationRun] AS
SELECT [RunId], [RuleDefinitionVersionRowId], [Mode], [Trigger], [StartedAt], [CompletedAt], [ActorId], [SubjectsScoped], [InstancesOpened], [InstancesClosed], [InstancesUnchanged], [ResultDocumentEntityId]
FROM [compliance].[RuleEvaluationRun];
GO
GRANT SELECT ON [compliance].[vRuleEvaluationRun] TO [app_execute];
GO
