-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vStandard] AS
SELECT [StandardCode], [IssuingEntityEntityId], [Family], [Subject], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [compliance].[Standard]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [compliance].[vStandard] TO [app_execute];
GO
