-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [compliance].[vSubjectVerdictHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [SubjectKind], [SubjectEntityId], [VerdictKind], [DefinitionEntityId], [VersionRowId], [Result], [Reason], [ReadsJson], [Error], [SinceRunId], [SinceAt], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [compliance].[SubjectVerdict] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [compliance].[vSubjectVerdictHistory] TO [app_execute];
GO
