-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [scheme].[vFaultRecordHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [OperationEntityId], [FaultType], [PhasesInvolved], [FaultedAssetEntityId], [LocationMethod], [DistanceKm], [DistancePercent], [CurrentKaA], [CurrentKaB], [CurrentKaC], [CurrentKaN], [ResistanceOhm], [ReactanceOhm], [IsFieldConfirmed], [FieldConfirmedAt], [PatrolRecordEntityId], [OscillographyDocumentEntityId], [ComputedByActorId], [SysStart], [SysEnd]
FROM [scheme].[FaultRecord] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [scheme].[vFaultRecordHistory] TO [app_execute];
GO
