-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [scheme].[vProtectionConditionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [ConditionKindCode], [ConditionValue], [Reason], [OpenedByActorId], [ClosedByActorId], [AuthorisedByActorId], [RevertObligationInstanceEntityId], [NotificationRecordEntityId], [WorkRequestEntityId], [SysStart], [SysEnd]
FROM [scheme].[ProtectionCondition] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [scheme].[vProtectionConditionHistory] TO [app_execute];
GO
