-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [scheme].[vProtectionOperationSnapshot] AS
SELECT [SnapshotId], [OperationEntityId], [SubjectKind], [SubjectRowId], [CapturedAt]
FROM [scheme].[ProtectionOperationSnapshot];
GO
GRANT SELECT ON [scheme].[vProtectionOperationSnapshot] TO [app_execute];
GO
