-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [scheme].[vSchemeMemberHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SchemeEntityId], [MemberKind], [MemberEntityId], [MemberRoleCode], [IsInService], [Notes], [AnalogInputEntityId], [SysStart], [SysEnd]
FROM [scheme].[SchemeMember] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [scheme].[vSchemeMemberHistory] TO [app_execute];
GO
