-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [scheme].[vSchemeActionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SchemeEntityId], [Sequence], [ActionKind], [TargetAssetEntityId], [TargetNodeEntityId], [LoadMw], [GenerationMw], [Mvar], [MaxExecutionMs], [Description], [SysStart], [SysEnd]
FROM [scheme].[SchemeAction] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [scheme].[vSchemeActionHistory] TO [app_execute];
GO
