-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vCharacteristicValueHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [HostEntityId], [CharacteristicDefinitionRowId], [TextValue], [IntegerValue], [DecimalValue], [BooleanValue], [DateTimeValue], [ReferenceEntityId], [UnitOverrideCode], [SysStart], [SysEnd]
FROM [record].[CharacteristicValue] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vCharacteristicValueHistory] TO [app_execute];
GO
