-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vConsistencyCheckHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ScdConfigurationFileRevisionRowId], [IedsInScl], [IedsInRegistry], [Matched], [UnmatchedScl], [UnmatchedRegistry], [SysStart], [SysEnd]
FROM [record].[ConsistencyCheck] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vConsistencyCheckHistory] TO [app_execute];
GO
