-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vInstrumentHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [InstrumentKind], [Range], [Accuracy], [SysStart], [SysEnd]
FROM [record].[Instrument] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vInstrumentHistory] TO [app_execute];
GO
