-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vRecordHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [RecordKindCode], [SubjectKind], [SubjectEntityId], [SecondSubjectKind], [SecondSubjectEntityId], [WorkRequestEntityId], [OccurredAt], [TimeSourceQuality], [PerformedByActorId], [WitnessedByActorId], [OverallResult], [Summary], [TemplateDefinitionVersionRowId], [SysStart], [SysEnd]
FROM [record].[Record] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vRecordHistory] TO [app_execute];
GO
