-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vTestResultHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [TestSheetEntityId], [TestPlanStepRowId], [StepSubjectKind], [StepSubjectEntityId], [Status], [NotPerformedReason], [Outcome], [Notes], [SysStart], [SysEnd]
FROM [record].[TestResult] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vTestResultHistory] TO [app_execute];
GO
