-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [record].[vTestReadingHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [TestResultEntityId], [TestPlanReadingRowId], [Phase], [TextValue], [IntegerValue], [DecimalValue], [BooleanValue], [DateTimeValue], [ReferenceEntityId], [UnitOverrideCode], [IsWithinLimits], [SysStart], [SysEnd]
FROM [record].[TestReading] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [record].[vTestReadingHistory] TO [app_execute];
GO
