-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [asset].[Asset_Add]
    @AssetTypeCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @VoltageClassCode NVARCHAR(20) = NULL,
    @ManufacturerEntityId UNIQUEIDENTIFIER = NULL,
    @ModelId UNIQUEIDENTIFIER = NULL,
    @Status NVARCHAR(20),
    @CommissionedAt DATETIMEOFFSET(7) = NULL,
    @RetiredAt DATETIMEOFFSET(7) = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [asset].[AssetRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [asset].[Asset] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [AssetTypeCode], [Name], [VoltageClassCode], [ManufacturerEntityId], [ModelId], [Status], [CommissionedAt], [RetiredAt], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @AssetTypeCode, @Name, @VoltageClassCode, @ManufacturerEntityId, @ModelId, @Status, @CommissionedAt, @RetiredAt, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
