-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [asset].[Classification_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @ClassificationKindCode NVARCHAR(40),
    @ClassificationValue NVARCHAR(60),
    @Basis NVARCHAR(20),
    @DerivationDefinitionVersionRowId UNIQUEIDENTIFIER = NULL,
    @DeterminedByActorId UNIQUEIDENTIFIER,
    @DeterminedAt DATETIMEOFFSET(7),
    @ReferenceDocumentRevisionRowId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'asset.Classification: no Subject entity of kind @SubjectKind with that id.', 1;
    IF NOT EXISTS (SELECT 1 FROM [asset].[Classification] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'asset.Classification: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [asset].[Classification] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [asset].[Classification] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [ClassificationKindCode], [ClassificationValue], [Basis], [DerivationDefinitionVersionRowId], [DeterminedByActorId], [DeterminedAt], [ReferenceDocumentRevisionRowId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SubjectKind, @SubjectEntityId, @ClassificationKindCode, @ClassificationValue, @Basis, @DerivationDefinitionVersionRowId, @DeterminedByActorId, @DeterminedAt, @ReferenceDocumentRevisionRowId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
