-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [migration].[Provenance_Append]
    @RunId UNIQUEIDENTIFIER,
    @TargetSchema SYSNAME,
    @TargetTable SYSNAME,
    @TargetEntityId UNIQUEIDENTIFIER = NULL,
    @TargetRowId UNIQUEIDENTIFIER = NULL,
    @SourceKey NVARCHAR(400),
    @SourceRowHash BINARY(32) = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ProvenanceId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [migration].[Provenance] ([RunId], [TargetSchema], [TargetTable], [TargetEntityId], [TargetRowId], [SourceKey], [SourceRowHash], [Notes])
    VALUES (@RunId, @TargetSchema, @TargetTable, @TargetEntityId, @TargetRowId, @SourceKey, @SourceRowHash, @Notes);
    SET @ProvenanceId = SCOPE_IDENTITY();
END;
