-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [security].[Delegation_Add]
    @FromPersonEntityId UNIQUEIDENTIFIER,
    @ToPersonEntityId UNIQUEIDENTIFIER,
    @RoleCode NVARCHAR(40),
    @StartsAt DATETIMEOFFSET(7),
    @EndsAt DATETIMEOFFSET(7) = NULL,
    @Reason NVARCHAR(400) = NULL,
    @GrantedByActorId UNIQUEIDENTIFIER,
    @RevokedByActorId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [security].[DelegationRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [security].[Delegation] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [FromPersonEntityId], [ToPersonEntityId], [RoleCode], [StartsAt], [EndsAt], [Reason], [GrantedByActorId], [RevokedByActorId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @FromPersonEntityId, @ToPersonEntityId, @RoleCode, @StartsAt, @EndsAt, @Reason, @GrantedByActorId, @RevokedByActorId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
