-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [security].[OverrideApproval_Append]
    @EventKind NVARCHAR(20),
    @RefersToOverrideApprovalId BIGINT = NULL,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @Action NVARCHAR(100),
    @ForPersonEntityId UNIQUEIDENTIFIER,
    @Reason NVARCHAR(400) = NULL,
    @ActorId UNIQUEIDENTIFIER,
    @OccurredAt DATETIMEOFFSET(7),
    @ExpiresAt DATETIMEOFFSET(7) = NULL,
    @SegregationOverrideId BIGINT = NULL,
    @ActionLogId BIGINT,
    @OverrideApprovalId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'security.OverrideApproval: no Subject entity of kind @SubjectKind with that id.', 1;
    INSERT [security].[OverrideApproval] ([EventKind], [RefersToOverrideApprovalId], [SubjectKind], [SubjectEntityId], [Action], [ForPersonEntityId], [Reason], [ActorId], [OccurredAt], [ExpiresAt], [SegregationOverrideId], [ActionLogId])
    VALUES (@EventKind, @RefersToOverrideApprovalId, @SubjectKind, @SubjectEntityId, @Action, @ForPersonEntityId, @Reason, @ActorId, @OccurredAt, @ExpiresAt, @SegregationOverrideId, @ActionLogId);
    SET @OverrideApprovalId = SCOPE_IDENTITY();
END;
