-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [security].[Role_Upsert]
    @RoleCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @RoleKind NVARCHAR(20) = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [security].[Role] t WHERE t.[RoleCode] = @RoleCode)
        UPDATE t SET [Name] = @Name, [RoleKind] = @RoleKind, [Description] = @Description, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [security].[Role] t WHERE t.[RoleCode] = @RoleCode;
    ELSE
        INSERT [security].[Role] ([RoleCode], [Name], [RoleKind], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@RoleCode, @Name, @RoleKind, @Description, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
