-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [security].[SegregationOverride_Append]
    @RuleDefinitionVersionRowId UNIQUEIDENTIFIER,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @ActionTaken NVARCHAR(100),
    @ActorId UNIQUEIDENTIFIER,
    @Reason NVARCHAR(400),
    @ApprovedByActorId UNIQUEIDENTIFIER = NULL,
    @OccurredAt DATETIMEOFFSET(7),
    @ActionLogId BIGINT,
    @OverrideId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'security.SegregationOverride: no Subject entity of kind @SubjectKind with that id.', 1;
    INSERT [security].[SegregationOverride] ([RuleDefinitionVersionRowId], [SubjectKind], [SubjectEntityId], [ActionTaken], [ActorId], [Reason], [ApprovedByActorId], [OccurredAt], [ActionLogId])
    VALUES (@RuleDefinitionVersionRowId, @SubjectKind, @SubjectEntityId, @ActionTaken, @ActorId, @Reason, @ApprovedByActorId, @OccurredAt, @ActionLogId);
    SET @OverrideId = SCOPE_IDENTITY();
END;
