-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[AppliesToDimension_Upsert]
    @DimensionCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @ValueKind NVARCHAR(20),
    @SubjectKindCode NVARCHAR(40) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[AppliesToDimension] t WHERE t.[DimensionCode] = @DimensionCode)
        UPDATE t SET [Name] = @Name, [ValueKind] = @ValueKind, [SubjectKindCode] = @SubjectKindCode, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[AppliesToDimension] t WHERE t.[DimensionCode] = @DimensionCode;
    ELSE
        INSERT [ref].[AppliesToDimension] ([DimensionCode], [Name], [ValueKind], [SubjectKindCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@DimensionCode, @Name, @ValueKind, @SubjectKindCode, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
