-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[AssetType_Upsert]
    @AssetTypeCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @Description NVARCHAR(MAX) = NULL,
    @AssetClassCode NVARCHAR(40),
    @IsDevice BIT = 0,
    @IsRouted BIT = 0,
    @IsAssembly BIT = 0,
    @DefaultTemplateDefinitionEntityId UNIQUEIDENTIFIER = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[AssetType] t WHERE t.[AssetTypeCode] = @AssetTypeCode)
        UPDATE t SET [Name] = @Name, [Description] = @Description, [AssetClassCode] = @AssetClassCode, [IsDevice] = @IsDevice, [IsRouted] = @IsRouted, [IsAssembly] = @IsAssembly, [DefaultTemplateDefinitionEntityId] = @DefaultTemplateDefinitionEntityId, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[AssetType] t WHERE t.[AssetTypeCode] = @AssetTypeCode;
    ELSE
        INSERT [ref].[AssetType] ([AssetTypeCode], [Name], [Description], [AssetClassCode], [IsDevice], [IsRouted], [IsAssembly], [DefaultTemplateDefinitionEntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@AssetTypeCode, @Name, @Description, @AssetClassCode, @IsDevice, @IsRouted, @IsAssembly, @DefaultTemplateDefinitionEntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
