-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[AssetClass_Upsert]
    @AssetClassCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @Rule NVARCHAR(400) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[AssetClass] t WHERE t.[AssetClassCode] = @AssetClassCode)
        UPDATE t SET [Name] = @Name, [Rule] = @Rule, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[AssetClass] t WHERE t.[AssetClassCode] = @AssetClassCode;
    ELSE
        INSERT [ref].[AssetClass] ([AssetClassCode], [Name], [Rule], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@AssetClassCode, @Name, @Rule, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
