-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[ConductorType_Upsert]
    @ConductorTypeCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @Gmr DECIMAL(18,8) = NULL,
    @GmrUnitCode NVARCHAR(20) = NULL,
    @Resistance DECIMAL(18,8) = NULL,
    @ResistanceUnitCode NVARCHAR(20) = NULL,
    @Diameter DECIMAL(18,8) = NULL,
    @DiameterUnitCode NVARCHAR(20) = NULL,
    @Ampacity DECIMAL(18,4) = NULL,
    @AmpacityUnitCode NVARCHAR(20) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[ConductorType] t WHERE t.[ConductorTypeCode] = @ConductorTypeCode)
        UPDATE t SET [Name] = @Name, [Gmr] = @Gmr, [GmrUnitCode] = @GmrUnitCode, [Resistance] = @Resistance, [ResistanceUnitCode] = @ResistanceUnitCode, [Diameter] = @Diameter, [DiameterUnitCode] = @DiameterUnitCode, [Ampacity] = @Ampacity, [AmpacityUnitCode] = @AmpacityUnitCode, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[ConductorType] t WHERE t.[ConductorTypeCode] = @ConductorTypeCode;
    ELSE
        INSERT [ref].[ConductorType] ([ConductorTypeCode], [Name], [Gmr], [GmrUnitCode], [Resistance], [ResistanceUnitCode], [Diameter], [DiameterUnitCode], [Ampacity], [AmpacityUnitCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@ConductorTypeCode, @Name, @Gmr, @GmrUnitCode, @Resistance, @ResistanceUnitCode, @Diameter, @DiameterUnitCode, @Ampacity, @AmpacityUnitCode, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
