-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[ConditionKind_Upsert]
    @ConditionKindCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @Description NVARCHAR(MAX) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[ConditionKind] t WHERE t.[ConditionKindCode] = @ConditionKindCode)
        UPDATE t SET [Name] = @Name, [Description] = @Description, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[ConditionKind] t WHERE t.[ConditionKindCode] = @ConditionKindCode;
    ELSE
        INSERT [ref].[ConditionKind] ([ConditionKindCode], [Name], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@ConditionKindCode, @Name, @Description, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
