-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[LocationNodeTypeParent_Upsert]
    @ChildNodeTypeCode NVARCHAR(40),
    @ParentNodeTypeCode NVARCHAR(40),
    @IsRequired BIT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[LocationNodeTypeParent] t WHERE t.[ChildNodeTypeCode] = @ChildNodeTypeCode AND t.[ParentNodeTypeCode] = @ParentNodeTypeCode)
        UPDATE t SET [IsRequired] = @IsRequired, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[LocationNodeTypeParent] t WHERE t.[ChildNodeTypeCode] = @ChildNodeTypeCode AND t.[ParentNodeTypeCode] = @ParentNodeTypeCode;
    ELSE
        INSERT [ref].[LocationNodeTypeParent] ([ChildNodeTypeCode], [ParentNodeTypeCode], [IsRequired], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@ChildNodeTypeCode, @ParentNodeTypeCode, @IsRequired, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
