-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[Manufacturer_Upsert]
    @ManufacturerId UNIQUEIDENTIFIER,
    @EntityEntityId UNIQUEIDENTIFIER,
    @ShortCode NVARCHAR(20),
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[Manufacturer] t WHERE t.[ManufacturerId] = @ManufacturerId)
        UPDATE t SET [EntityEntityId] = @EntityEntityId, [ShortCode] = @ShortCode, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[Manufacturer] t WHERE t.[ManufacturerId] = @ManufacturerId;
    ELSE
        INSERT [ref].[Manufacturer] ([ManufacturerId], [EntityEntityId], [ShortCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@ManufacturerId, @EntityEntityId, @ShortCode, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
