-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[RecordKind_Upsert]
    @RecordKindCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @Description NVARCHAR(MAX) = NULL,
    @TemplateDefinitionEntityId UNIQUEIDENTIFIER = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[RecordKind] t WHERE t.[RecordKindCode] = @RecordKindCode)
        UPDATE t SET [Name] = @Name, [Description] = @Description, [TemplateDefinitionEntityId] = @TemplateDefinitionEntityId, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[RecordKind] t WHERE t.[RecordKindCode] = @RecordKindCode;
    ELSE
        INSERT [ref].[RecordKind] ([RecordKindCode], [Name], [Description], [TemplateDefinitionEntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@RecordKindCode, @Name, @Description, @TemplateDefinitionEntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
