-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[SubjectKind_Upsert]
    @SubjectKindCode NVARCHAR(40),
    @Name NVARCHAR(200),
    @SchemaName SYSNAME = NULL,
    @TableName SYSNAME = NULL,
    @KeyColumnName SYSNAME = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[SubjectKind] t WHERE t.[SubjectKindCode] = @SubjectKindCode)
        UPDATE t SET [Name] = @Name, [SchemaName] = @SchemaName, [TableName] = @TableName, [KeyColumnName] = @KeyColumnName, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[SubjectKind] t WHERE t.[SubjectKindCode] = @SubjectKindCode;
    ELSE
        INSERT [ref].[SubjectKind] ([SubjectKindCode], [Name], [SchemaName], [TableName], [KeyColumnName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@SubjectKindCode, @Name, @SchemaName, @TableName, @KeyColumnName, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
