-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [ref].[Unit_Upsert]
    @UnitCode NVARCHAR(20),
    @Name NVARCHAR(100),
    @Dimension NVARCHAR(40),
    @BaseUnitCode NVARCHAR(20) = NULL,
    @ToBaseFactor DECIMAL(28,12) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [ref].[Unit] t WHERE t.[UnitCode] = @UnitCode)
        UPDATE t SET [Name] = @Name, [Dimension] = @Dimension, [BaseUnitCode] = @BaseUnitCode, [ToBaseFactor] = @ToBaseFactor, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [ref].[Unit] t WHERE t.[UnitCode] = @UnitCode;
    ELSE
        INSERT [ref].[Unit] ([UnitCode], [Name], [Dimension], [BaseUnitCode], [ToBaseFactor], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@UnitCode, @Name, @Dimension, @BaseUnitCode, @ToBaseFactor, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
