-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[ControlBlock_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @LogicalDeviceEntityId UNIQUEIDENTIFIER,
    @ControlBlockKind NVARCHAR(20),
    @CbName NVARCHAR(100),
    @AppId NVARCHAR(20) = NULL,
    @ConfRev BIGINT = NULL,
    @DatasetEntityId UNIQUEIDENTIFIER = NULL,
    @MulticastMac NVARCHAR(17) = NULL,
    @VlanId INT = NULL,
    @VlanPriority TINYINT = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [connection].[ControlBlock] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'connection.ControlBlock: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [connection].[ControlBlock] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[ControlBlock] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [LogicalDeviceEntityId], [ControlBlockKind], [CbName], [AppId], [ConfRev], [DatasetEntityId], [MulticastMac], [VlanId], [VlanPriority])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ConfigurationFileRevisionRowId, @LogicalDeviceEntityId, @ControlBlockKind, @CbName, @AppId, @ConfRev, @DatasetEntityId, @MulticastMac, @VlanId, @VlanPriority);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
