-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[ControlBlock_Add]
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @LogicalDeviceEntityId UNIQUEIDENTIFIER,
    @ControlBlockKind NVARCHAR(20),
    @CbName NVARCHAR(100),
    @AppId NVARCHAR(20) = NULL,
    @ConfRev BIGINT = NULL,
    @DatasetEntityId UNIQUEIDENTIFIER = NULL,
    @MulticastMac NVARCHAR(17) = NULL,
    @VlanId INT = NULL,
    @VlanPriority TINYINT = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[ControlBlockRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[ControlBlock] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [LogicalDeviceEntityId], [ControlBlockKind], [CbName], [AppId], [ConfRev], [DatasetEntityId], [MulticastMac], [VlanId], [VlanPriority])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ConfigurationFileRevisionRowId, @LogicalDeviceEntityId, @ControlBlockKind, @CbName, @AppId, @ConfRev, @DatasetEntityId, @MulticastMac, @VlanId, @VlanPriority);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
