-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[DataAttribute_Add]
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @LogicalNodeEntityId UNIQUEIDENTIFIER,
    @DoName NVARCHAR(100),
    @DaName NVARCHAR(100) = NULL,
    @Fc NVARCHAR(10) = NULL,
    @DataSource NVARCHAR(200) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[DataAttributeRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[DataAttribute] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [LogicalNodeEntityId], [DoName], [DaName], [Fc], [DataSource])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ConfigurationFileRevisionRowId, @LogicalNodeEntityId, @DoName, @DaName, @Fc, @DataSource);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
