-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[ExtRef_Add]
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @IedEntityId UNIQUEIDENTIFIER,
    @IntAddr NVARCHAR(200) = NULL,
    @LdInst NVARCHAR(100) = NULL,
    @LnClass NVARCHAR(10) = NULL,
    @LnInst NVARCHAR(10) = NULL,
    @DoName NVARCHAR(100) = NULL,
    @DaName NVARCHAR(100) = NULL,
    @PublisherIedName NVARCHAR(100) = NULL,
    @CbName NVARCHAR(100) = NULL,
    @DatasetRef NVARCHAR(200) = NULL,
    @ConnectionEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[ExtRefRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[ExtRef] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [IedEntityId], [IntAddr], [LdInst], [LnClass], [LnInst], [DoName], [DaName], [PublisherIedName], [CbName], [DatasetRef], [ConnectionEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ConfigurationFileRevisionRowId, @IedEntityId, @IntAddr, @LdInst, @LnClass, @LnInst, @DoName, @DaName, @PublisherIedName, @CbName, @DatasetRef, @ConnectionEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
