-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[LogicalDevice_Add]
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @IedEntityId UNIQUEIDENTIFIER,
    @Inst NVARCHAR(100),
    @LdName NVARCHAR(100) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[LogicalDeviceRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[LogicalDevice] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [IedEntityId], [Inst], [LdName])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ConfigurationFileRevisionRowId, @IedEntityId, @Inst, @LdName);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
