-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[PointMap_Add]
    @ProtocolEndpointEntityId UNIQUEIDENTIFIER,
    @ObjectGroup INT = NULL,
    @Variation INT = NULL,
    @PointIndex INT,
    @PointName NVARCHAR(100) = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @AssetEntityId UNIQUEIDENTIFIER = NULL,
    @UnitCode NVARCHAR(20) = NULL,
    @ScaleFactor DECIMAL(28,10) = NULL,
    @Offset DECIMAL(28,10) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[PointMapRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[PointMap] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ProtocolEndpointEntityId], [ObjectGroup], [Variation], [PointIndex], [PointName], [Description], [AssetEntityId], [UnitCode], [ScaleFactor], [Offset])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ProtocolEndpointEntityId, @ObjectGroup, @Variation, @PointIndex, @PointName, @Description, @AssetEntityId, @UnitCode, @ScaleFactor, @Offset);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
