-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[PortService_Add]
    @NetworkPortEntityId UNIQUEIDENTIFIER,
    @Protocol NVARCHAR(40),
    @LogicalPort INT = NULL,
    @ServiceName NVARCHAR(100) = NULL,
    @Direction NVARCHAR(20) = NULL,
    @BusinessJustification NVARCHAR(400) = NULL,
    @IsInsideSecurityPerimeter BIT = 0,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[PortServiceRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[PortService] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [NetworkPortEntityId], [Protocol], [LogicalPort], [ServiceName], [Direction], [BusinessJustification], [IsInsideSecurityPerimeter])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @NetworkPortEntityId, @Protocol, @LogicalPort, @ServiceName, @Direction, @BusinessJustification, @IsInsideSecurityPerimeter);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
