-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [connection].[ProtocolEndpoint_Add]
    @NetworkPortEntityId UNIQUEIDENTIFIER,
    @Protocol NVARCHAR(20),
    @Role NVARCHAR(20),
    @Address NVARCHAR(50) = NULL,
    @RemoteEndpointEntityId UNIQUEIDENTIFIER = NULL,
    @ConfigDetail NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [connection].[ProtocolEndpointRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [connection].[ProtocolEndpoint] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [NetworkPortEntityId], [Protocol], [Role], [Address], [RemoteEndpointEntityId], [ConfigDetail])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @NetworkPortEntityId, @Protocol, @Role, @Address, @RemoteEndpointEntityId, @ConfigDetail);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
