-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [asset].[vAlternateKeyHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SubjectEntityId], [KeyKindCode], [KeyValue], [ScopeEntityId], [IsPrimaryLabel], [SysStart], [SysEnd]
FROM [asset].[AlternateKey] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [asset].[vAlternateKeyHistory] TO [app_execute];
GO
