-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [asset].[vAssetRatingHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [AssetEntityId], [RatingKind], [Season], [Amperes], [Source], [SourceSystem], [Notes], [SysStart], [SysEnd]
FROM [asset].[AssetRating] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [asset].[vAssetRatingHistory] TO [app_execute];
GO
