-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [asset].[vInstrumentWindingHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [AssetEntityId], [WindingNo], [Code], [Purpose], [RatioTaps], [RatioInUse], [AccuracyClass], [RatedBurden], [KneePointVoltageV], [RatedSecondary], [Connection], [TapInUseEntityId], [Notes], [SysStart], [SysEnd]
FROM [asset].[InstrumentWinding] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [asset].[vInstrumentWindingHistory] TO [app_execute];
GO
