-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [asset].[vOwnershipLinkHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [EntityEntityId], [OwnershipRole], [Share], [IsResponsibleForReporting], [SysStart], [SysEnd]
FROM [asset].[OwnershipLink] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [asset].[vOwnershipLinkHistory] TO [app_execute];
GO
