-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [asset].[vPlacementHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [AssetEntityId], [NodeEntityId], [CustodyLocationEntityId], [PlacementKind], [InstalledByActorId], [RemovedByActorId], [WorkRequestEntityId], [SysStart], [SysEnd]
FROM [asset].[Placement] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [asset].[vPlacementHistory] TO [app_execute];
GO
