-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vDelegation] AS
-- current: the latest row per entity valid now, not deleted (decision 69, 71)
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [FromPersonEntityId], [ToPersonEntityId], [RoleCode], [StartsAt], [EndsAt], [Reason], [GrantedByActorId], [RevokedByActorId]
FROM (
    SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [FromPersonEntityId], [ToPersonEntityId], [RoleCode], [StartsAt], [EndsAt], [Reason], [GrantedByActorId], [RevokedByActorId],
           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn
    FROM [security].[Delegation]
    WHERE [IsDeleted] = 0
      AND [ValidFrom] <= SYSDATETIMEOFFSET()
      AND ([ValidTo] IS NULL OR [ValidTo] > SYSDATETIMEOFFSET())
) x WHERE x._rn = 1;
GO
GRANT SELECT ON [security].[vDelegation] TO [app_execute];
GO
