-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vOverrideApproval] AS
SELECT [OverrideApprovalId], [EventKind], [RefersToOverrideApprovalId], [SubjectKind], [SubjectEntityId], [Action], [ForPersonEntityId], [Reason], [ActorId], [OccurredAt], [ExpiresAt], [SegregationOverrideId], [ActionLogId]
FROM [security].[OverrideApproval];
GO
GRANT SELECT ON [security].[vOverrideApproval] TO [app_execute];
GO
