-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vPermissionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [PermissionCode], [SubjectClass], [Verb], [Name], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [security].[Permission] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [security].[vPermissionHistory] TO [app_execute];
GO
