-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vRoleHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RoleCode], [Name], [RoleKind], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [security].[Role] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [security].[vRoleHistory] TO [app_execute];
GO
