-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vRolePermission] AS
SELECT [RoleCode], [PermissionCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [security].[RolePermission]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [security].[vRolePermission] TO [app_execute];
GO
