-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vRolePermissionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RoleCode], [PermissionCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [security].[RolePermission] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [security].[vRolePermissionHistory] TO [app_execute];
GO
