-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [security].[vUserHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [PersonEntityId], [UserPrincipalName], [IsEnabled], [DisabledAt], [DisabledReason], [SysStart], [SysEnd]
FROM [security].[User] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [security].[vUserHistory] TO [app_execute];
GO
