-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [migration].[vRun] AS
SELECT [RunId], [SourceSystem], [SourceCaptureAt], [CleansingRuleVersionRowId], [StartedAt], [CompletedAt], [RunByActorId], [Notes]
FROM [migration].[Run];
GO
GRANT SELECT ON [migration].[vRun] TO [app_execute];
GO
