-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [party].[vEntityAgreementHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [EntityEntityId], [AgreementKind], [ProductLine], [Reference], [StartsAt], [EndsAt], [EndOfSupportAt], [EndOfLifeAt], [AcknowledgementDocumentEntityId], [ContactPersonEntityId], [SysStart], [SysEnd]
FROM [party].[EntityAgreement] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [party].[vEntityAgreementHistory] TO [app_execute];
GO
