-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [device].[vFirmwareHistoryHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DeviceEntityId], [FirmwareVersionId], [AppliedByActorId], [VerifiedByActorId], [VerifiedAt], [WorkRequestEntityId], [AdvisoryDispositionEntityId], [SysStart], [SysEnd]
FROM [device].[FirmwareHistory] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [device].[vFirmwareHistoryHistory] TO [app_execute];
GO
