-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [device].[vKnownDefectHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ModelId], [FirmwareVersionFromId], [FirmwareVersionToId], [Description], [Workaround], [VendorReference], [AdvisoryEntityId], [ReportedByActorId], [Status], [SysStart], [SysEnd]
FROM [device].[KnownDefect] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [device].[vKnownDefectHistory] TO [app_execute];
GO
