-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [device].[vLifecycleEvent] AS
SELECT [LifecycleEventId], [DeviceEntityId], [EventKind], [OccurredAt], [TimeSourceQuality], [ActorId], [NodeEntityId], [CustodyLocationEntityId], [WorkRequestEntityId], [RecordEntityId], [Notes]
FROM [device].[LifecycleEvent];
GO
GRANT SELECT ON [device].[vLifecycleEvent] TO [app_execute];
GO
