-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [work].[CascadeWorkOrder_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @CascadeNumber NVARCHAR(100),
    @CascadeStatus NVARCHAR(40) = NULL,
    @MappedNodeEntityId UNIQUEIDENTIFIER = NULL,
    @CascadeWorkOrderType NVARCHAR(40) = NULL,
    @LastSyncedAt DATETIMEOFFSET(7) = NULL,
    @SyncDirection NVARCHAR(20) = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [work].[CascadeWorkOrder] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'work.CascadeWorkOrder: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [work].[CascadeWorkOrder] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [work].[CascadeWorkOrder] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [CascadeNumber], [CascadeStatus], [MappedNodeEntityId], [CascadeWorkOrderType], [LastSyncedAt], [SyncDirection], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @CascadeNumber, @CascadeStatus, @MappedNodeEntityId, @CascadeWorkOrderType, @LastSyncedAt, @SyncDirection, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
