-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [work].[WorkRequest_Add]
    @ParentWorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @WorkTypeDefinitionVersionRowId UNIQUEIDENTIFIER,
    @Title NVARCHAR(200),
    @Description NVARCHAR(MAX) = NULL,
    @SpecialInstructions NVARCHAR(MAX) = NULL,
    @PriorityCode NVARCHAR(40) = NULL,
    @ScopeKind NVARCHAR(40),
    @ScopeEntityId UNIQUEIDENTIFIER,
    @PlannedStartAt DATETIMEOFFSET(7) = NULL,
    @PlannedEndAt DATETIMEOFFSET(7) = NULL,
    @ActualStartAt DATETIMEOFFSET(7) = NULL,
    @ActualEndAt DATETIMEOFFSET(7) = NULL,
    @EstimatedHours DECIMAL(8,2) = NULL,
    @OutageRequired BIT = 0,
    @OutageWindowStartAt DATETIMEOFFSET(7) = NULL,
    @OutageWindowEndAt DATETIMEOFFSET(7) = NULL,
    @OutageApprovalReference NVARCHAR(100) = NULL,
    @RaisedByObligationInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @RaisedByRecordEntityId UNIQUEIDENTIFIER = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @ScopeEntityId IS NOT NULL AND [meta].[fEntityExists](@ScopeKind, @ScopeEntityId) = 0
        THROW 50101, N'work.WorkRequest: no Scope entity of kind @ScopeKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [work].[WorkRequestRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [work].[WorkRequest] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ParentWorkRequestEntityId], [WorkTypeDefinitionVersionRowId], [Title], [Description], [SpecialInstructions], [PriorityCode], [ScopeKind], [ScopeEntityId], [PlannedStartAt], [PlannedEndAt], [ActualStartAt], [ActualEndAt], [EstimatedHours], [OutageRequired], [OutageWindowStartAt], [OutageWindowEndAt], [OutageApprovalReference], [RaisedByObligationInstanceEntityId], [RaisedByRecordEntityId], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ParentWorkRequestEntityId, @WorkTypeDefinitionVersionRowId, @Title, @Description, @SpecialInstructions, @PriorityCode, @ScopeKind, @ScopeEntityId, @PlannedStartAt, @PlannedEndAt, @ActualStartAt, @ActualEndAt, @EstimatedHours, @OutageRequired, @OutageWindowStartAt, @OutageWindowEndAt, @OutageApprovalReference, @RaisedByObligationInstanceEntityId, @RaisedByRecordEntityId, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
