-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [archive].[vRetention] AS
SELECT [RetentionCode], [RecordKindCode], [EventKind], [RuleDefinitionEntityId], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [archive].[Retention]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [archive].[vRetention] TO [app_execute];
GO
