-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [archive].[vRetentionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RetentionCode], [RecordKindCode], [EventKind], [RuleDefinitionEntityId], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [archive].[Retention] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [archive].[vRetentionHistory] TO [app_execute];
GO
