-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAlternateKeyKindHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [KeyKindCode], [Name], [SchemaName], [SubjectKindCode], [ScopeRequired], [ScopeSubjectKindCode], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[AlternateKeyKind] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vAlternateKeyKindHistory] TO [app_execute];
GO
