-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAlternateKeyKind] AS
SELECT [KeyKindCode], [Name], [SchemaName], [SubjectKindCode], [ScopeRequired], [ScopeSubjectKindCode], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[AlternateKeyKind]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vAlternateKeyKind] TO [app_execute];
GO
