-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAppliesToDimension] AS
SELECT [DimensionCode], [Name], [ValueKind], [SubjectKindCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[AppliesToDimension]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vAppliesToDimension] TO [app_execute];
GO
