-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAppliesToDimensionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [DimensionCode], [Name], [ValueKind], [SubjectKindCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[AppliesToDimension] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vAppliesToDimensionHistory] TO [app_execute];
GO
