-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAssetClassHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [AssetClassCode], [Name], [Rule], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[AssetClass] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vAssetClassHistory] TO [app_execute];
GO
