-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAssetTypeHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [AssetTypeCode], [Name], [Description], [AssetClassCode], [IsDevice], [IsRouted], [IsAssembly], [DefaultTemplateDefinitionEntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[AssetType] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vAssetTypeHistory] TO [app_execute];
GO
