-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAssetType] AS
SELECT [AssetTypeCode], [Name], [Description], [AssetClassCode], [IsDevice], [IsRouted], [IsAssembly], [DefaultTemplateDefinitionEntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[AssetType]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vAssetType] TO [app_execute];
GO
