-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vAuthorisationRightKindHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RightKindCode], [Name], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[AuthorisationRightKind] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vAuthorisationRightKindHistory] TO [app_execute];
GO
