-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vClassificationKind] AS
SELECT [ClassificationKindCode], [Name], [Description], [AllowedValuesDefinitionRowId], [SubjectKinds], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[ClassificationKind]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vClassificationKind] TO [app_execute];
GO
