-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vConditionKind] AS
SELECT [ConditionKindCode], [Name], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[ConditionKind]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vConditionKind] TO [app_execute];
GO
