-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vConductorTypeHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [ConductorTypeCode], [Name], [Gmr], [GmrUnitCode], [Resistance], [ResistanceUnitCode], [Diameter], [DiameterUnitCode], [Ampacity], [AmpacityUnitCode], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[ConductorType] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vConductorTypeHistory] TO [app_execute];
GO
