-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vFirmwareVersionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [FirmwareVersionId], [ModelId], [VersionString], [VendorReleaseReference], [ReleasedAt], [ParseTransformDefinitionEntityId], [IcdDocumentEntityId], [VendorLifecycleStatus], [StatusAsOf], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[FirmwareVersion] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vFirmwareVersionHistory] TO [app_execute];
GO
