-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vLocationNodeTypeParentHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [ChildNodeTypeCode], [ParentNodeTypeCode], [IsRequired], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[LocationNodeTypeParent] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vLocationNodeTypeParentHistory] TO [app_execute];
GO
