-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vLocationNodeTypeParent] AS
SELECT [ChildNodeTypeCode], [ParentNodeTypeCode], [IsRequired], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[LocationNodeTypeParent]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vLocationNodeTypeParent] TO [app_execute];
GO
