-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vModelHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [ModelId], [ManufacturerId], [ModelCode], [ModelName], [AssetTypeCode], [DeviceCategory], [FirmwareFamily], [MaxSettingGroups], [VendorSoftware], [ProjectFileExtension], [Technology], [VendorLifecycleStatus], [StatusAsOf], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[Model] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vModelHistory] TO [app_execute];
GO
