-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vMulticastAddress] AS
SELECT [MacAddress], [Name], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[MulticastAddress]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vMulticastAddress] TO [app_execute];
GO
