-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vRecordKindHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RecordKindCode], [Name], [Description], [TemplateDefinitionEntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[RecordKind] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vRecordKindHistory] TO [app_execute];
GO
