-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vSubjectKindHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [SubjectKindCode], [Name], [SchemaName], [TableName], [KeyColumnName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[SubjectKind] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vSubjectKindHistory] TO [app_execute];
GO
