-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vVlanHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [VlanId], [Name], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [ref].[Vlan] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [ref].[vVlanHistory] TO [app_execute];
GO
