-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [ref].[vVlan] AS
SELECT [VlanId], [Name], [Description], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId]
FROM [ref].[Vlan]
WHERE [IsActive] = 1;
GO
GRANT SELECT ON [ref].[vVlan] TO [app_execute];
GO
