-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vCaseHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [LayerEntityId], [Name], [SystemModelAt], [Origin], [SourceFileDocumentEntityId], [StudyRevisionRowId], [SysStart], [SysEnd]
FROM [network].[Case] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [network].[vCaseHistory] TO [app_execute];
GO
