-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vConstantsRun] AS
SELECT [RunId], [StartedAt], [ActorId], [EngineDefinitionVersionRowId], [Method], [EarthResistivityOhmM], [FrequencyHz], [SectionsCalculated], [Status]
FROM [network].[ConstantsRun];
GO
GRANT SELECT ON [network].[vConstantsRun] TO [app_execute];
GO
