-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vLayerHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [Name], [Description], [ExportTransformDefinitionEntityId], [ImportTransformDefinitionEntityId], [OwnerEntityEntityId], [Notes], [SysStart], [SysEnd]
FROM [network].[Layer] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [network].[vLayerHistory] TO [app_execute];
GO
