-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vLayer] AS
-- current: the latest row per entity valid now, not deleted (decision 69, 71)
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [Name], [Description], [ExportTransformDefinitionEntityId], [ImportTransformDefinitionEntityId], [OwnerEntityEntityId], [Notes]
FROM (
    SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [Name], [Description], [ExportTransformDefinitionEntityId], [ImportTransformDefinitionEntityId], [OwnerEntityEntityId], [Notes],
           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn
    FROM [network].[Layer]
    WHERE [IsDeleted] = 0
      AND [ValidFrom] <= SYSDATETIMEOFFSET()
      AND ([ValidTo] IS NULL OR [ValidTo] > SYSDATETIMEOFFSET())
) x WHERE x._rn = 1;
GO
GRANT SELECT ON [network].[vLayer] TO [app_execute];
GO
