-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vLineSectionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [LineAssetEntityId], [FromRouteStepRowId], [ToRouteStepRowId], [StructureTypeDefinitionVersionRowId], [ConductorTypeCode], [GroundWireCount], [LengthKm], [SysStart], [SysEnd]
FROM [network].[LineSection] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [network].[vLineSectionHistory] TO [app_execute];
GO
