-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vLineSectionMutualConstants] AS
SELECT [LineSectionMutualConstantsId], [LineSectionConstantsId], [MutualsToSectionEntityId], [Z0mR], [Z0mX]
FROM [network].[LineSectionMutualConstants];
GO
GRANT SELECT ON [network].[vLineSectionMutualConstants] TO [app_execute];
GO
