-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vLineSectionConstants] AS
SELECT [LineSectionConstantsId], [RunId], [LineSectionEntityId], [Z1RPerKm], [Z1XPerKm], [Z0RPerKm], [Z0XPerKm], [B1PerKm], [B0PerKm], [Z1RTotal], [Z1XTotal], [Z0RTotal], [Z0XTotal], [B1Total], [B0Total], [InputHash]
FROM [network].[LineSectionConstants];
GO
GRANT SELECT ON [network].[vLineSectionConstants] TO [app_execute];
GO
