-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [network].[vSourceEquivalentHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [CaseEntityId], [LayerNodeEntityId], [Z1R], [Z1X], [Z0R], [Z0X], [SysStart], [SysEnd]
FROM [network].[SourceEquivalent] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [network].[vSourceEquivalentHistory] TO [app_execute];
GO
