-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vDocumentHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DocumentClassDefinitionEntityId], [Title], [Description], [OwnerEntityEntityId], [ClassificationMarking], [Notes], [SysStart], [SysEnd]
FROM [document].[Document] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [document].[vDocumentHistory] TO [app_execute];
GO
