-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vDrawing] AS
SELECT [RevisionRowId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SheetNumber], [SheetCount], [TitleLine1], [TitleLine2], [AssetTitle], [JobNumber], [WbsNumber], [DrawnByActorId], [CheckedByActorId], [DesignedByActorId], [DrawingStatusCode], [Orientation], [PaperSize], [Scale], [DrawingKind]
FROM [document].[Drawing]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [document].[vDrawing] TO [app_execute];
GO
