-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vDrawingHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RevisionRowId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [SheetNumber], [SheetCount], [TitleLine1], [TitleLine2], [AssetTitle], [JobNumber], [WbsNumber], [DrawnByActorId], [CheckedByActorId], [DesignedByActorId], [DrawingStatusCode], [Orientation], [PaperSize], [Scale], [DrawingKind], [SysStart], [SysEnd]
FROM [document].[Drawing] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [document].[vDrawingHistory] TO [app_execute];
GO
