-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vRevisionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DocumentEntityId], [RevisionLabel], [Status], [PreparedByActorId], [PreparedAt], [CheckedByActorId], [CheckedAt], [ApprovedByActorId], [ApprovedAt], [IssuedAt], [EffectiveFrom], [EffectiveTo], [ChangeNote], [SupersedesRevisionRowId], [SysStart], [SysEnd]
FROM [document].[Revision] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [document].[vRevisionHistory] TO [app_execute];
GO
