-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vStudyHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RevisionRowId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [StudyKind], [Software], [SoftwareVersion], [SystemModelAt], [NetworkModelCaseEntityId], [FaultLevelAssumptions], [TopologyReference], [ValidWhile], [IsStale], [SysStart], [SysEnd]
FROM [document].[Study] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [document].[vStudyHistory] TO [app_execute];
GO
