-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [document].[vStudy] AS
SELECT [RevisionRowId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [StudyKind], [Software], [SoftwareVersion], [SystemModelAt], [NetworkModelCaseEntityId], [FaultLevelAssumptions], [TopologyReference], [ValidWhile], [IsStale]
FROM [document].[Study]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [document].[vStudy] TO [app_execute];
GO
