-- GENERATED by tools/capability_sel221f.py - do not edit; edit the data there and regenerate.
-- #181 (2026-09-17): what an SEL-221F can do, from the instruction manual (IM 981207). The owner asked for a
-- checklist on the device built from the manual, so that placing a relay offers its elements rather than asking
-- a person to invent them. scheme.FunctionCapability is the table the design already provided for this
-- (SCHEMA-DESIGN 7.3, decision 117: 'what a relay model (or firmware) can do'); nothing had ever written a row.
-- Every row cites the manual heading and page that says the relay has that function; the ANSI code is the one
-- the settings template already assigns to that function's settings (#168), so the two agree.
-- Idempotent: a capability already recorded for the model is left alone.
IF OBJECT_ID(N'[scheme].[FunctionCapability_Add]') IS NULL RETURN;   -- bootstrap (tables-only) publish
GO
DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';
DECLARE @sel UNIQUEIDENTIFIER = (SELECT TOP (1) [ManufacturerId] FROM [ref].[vManufacturer] WHERE [ShortCode] = N'SEL');
IF @sel IS NULL RETURN;   -- the SEL templates seed the manufacturer; nothing to bind to yet
DECLARE @model UNIQUEIDENTIFIER, @code NVARCHAR(200);
DECLARE mc CURSOR LOCAL FAST_FORWARD FOR SELECT [Code] FROM (VALUES (N'SEL-221F Z1-3=.125-64 OHMS'), (N'SEL-221F')) x ([Code]);
OPEN mc; FETCH NEXT FROM mc INTO @code;
WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @model = [ModelId] FROM [ref].[vModel] WHERE [ManufacturerId] = @sel AND [ModelCode] = @code;
    IF @model IS NOT NULL
    BEGIN
        -- 21 Phase and ground distance (all) - Functional Specifications > Expanded Mho Characteristics for Phase-Ground, Phase-Phase, and Three-Phase Faults (2-2); Relay Overview (1-1)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'21')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'21', @Source = N'Manual', @ActorId = @author;
        -- 51N Residual time-overcurrent (all) - Functional Specifications > Residual Overcurrent Backup Protection for Ground Faults (2-3)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'51N')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'51N', @Source = N'Manual', @ActorId = @author;
        -- 50N Instantaneous residual overcurrent (all) - Functional Specifications > Residual Overcurrent Backup Protection for Ground Faults (2-3)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'50N')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'50N', @Source = N'Manual', @ActorId = @author;
        -- 67N Ground directional overcurrent (all) - Title page; Functional Specifications > Residual Overcurrent Backup Protection for Ground Faults (2-3)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'67N')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'67N', @Source = N'Manual', @ActorId = @author;
        -- 50 Phase overcurrent (nondirectional) (all) - Functional Specifications > Nondirectional Phase Overcurrent Elements (2-3, 2-4)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'50')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'50', @Source = N'Manual', @ActorId = @author;
        -- 79 Reclosing (all) - Title page; Functional Specifications > Reclosing (2-4)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'79')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'79', @Source = N'Manual', @ActorId = @author;
        -- 25 Synchronism check (all) - Title page; Functional Specifications > Synchronism Checking (2-4)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'25')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'25', @Source = N'Manual', @ActorId = @author;
        -- 27 Undervoltage (dead-line / dead-bus check) (all) - Functional Specifications > Voltage Checking (2-4)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'27')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'27', @Source = N'Manual', @ActorId = @author;
        -- 59 Overvoltage (live-line / live-bus check) (all) - Functional Specifications > Voltage Checking (2-4)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'59')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'59', @Source = N'Manual', @ActorId = @author;
        -- 50BF Breaker failure (SEL-221F-3, -4 only) - Introduction > Model Variations (1-2); Specifications > Breaker Failure Features of the SEL-221F-3/121F-3 and SEL-221F-4 Relays (2-50)
        IF NOT EXISTS (SELECT 1 FROM [scheme].[vFunctionCapability] WHERE [ModelId] = @model AND [AnsiCode] = N'50BF')
            EXEC [scheme].[FunctionCapability_Add] @ModelId = @model, @AnsiCode = N'50BF', @Source = N'Manual', @ActorId = @author;
    END
    FETCH NEXT FROM mc INTO @code;
END
CLOSE mc; DEALLOCATE mc;
GO
