-- GENERATED by tools/template_line.py — do not edit; change the table there and regenerate.
-- #219 (2026-09-21): the transmission line's template, LINE_Template — the line's impedances, length and charging as characteristics of
-- the line asset (the owner: the line impedance 'must move onto the line asset'), the default template of the asset type Line, so
-- asset.SetAssetCharacteristic records them per line and the rationale reads them as line.R1, line.X1, line.R0, line.X0, line.LengthMiles.
-- Idempotent: adds the version only when no Effective version carries this change note; sets the type's default only when unset or different.
IF OBJECT_ID(N'[config].[AddDefinition]') IS NULL RETURN;   -- bootstrap (tables-only) publish
GO
DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001', @approver UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';
DECLARE @e UNIQUEIDENTIFIER, @v UNIQUEIDENTIFIER, @no INT;
SELECT @e = [EntityId] FROM [config].[Definition] WHERE [DefinitionKind] = N'CharacteristicSchema.AssetTemplate' AND [DefinitionKey] = N'LINE_Template' AND [IsDeleted] = 0;
IF @e IS NULL
    EXEC [config].[AddDefinition] @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @DefinitionKey = N'LINE_Template',
         @Name = N'Transmission line template', @Description = N'What the platform holds of a transmission line as an asset: its positive- and zero-sequence impedance, its length and its charging (#219) — recorded once on the line, read by every relay rationale on it.',
         @ActorId = @author, @EntityId = @e OUTPUT;
IF NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' AND [ChangeNote] = N'seed v1 (#219): the line''s positive- and zero-sequence impedance, length and charging')
BEGIN
    EXEC [config].[AddDefinitionVersion] @DefinitionKey = N'LINE_Template', @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @ChangeNote = N'seed v1 (#219): the line''s positive- and zero-sequence impedance, length and charging', @ActorId = @author, @VersionRowId = @v OUTPUT, @VersionNumber = @no OUTPUT;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'R1', @Name = N'Positive-sequence resistance', @DataType = N'Decimal', @UnitCode = N'Ω', @Base = N'Primary', @DisplayGroup = N'Impedance', @DisplayOrder = 1, @Description = N'Positive-sequence line resistance, ohms primary, end to end. The legacy rationales write it as the real part of Z1 (A4811.docx: ''Z1=1.685+j6.7524'').', @ActorId = @author;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'X1', @Name = N'Positive-sequence reactance', @DataType = N'Decimal', @UnitCode = N'Ω', @Base = N'Primary', @DisplayGroup = N'Impedance', @DisplayOrder = 2, @Description = N'Positive-sequence line reactance, ohms primary, end to end (the imaginary part of Z1).', @ActorId = @author;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'R0', @Name = N'Zero-sequence resistance', @DataType = N'Decimal', @UnitCode = N'Ω', @Base = N'Primary', @DisplayGroup = N'Impedance', @DisplayOrder = 3, @Description = N'Zero-sequence line resistance, ohms primary, end to end (the real part of Z0).', @ActorId = @author;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'X0', @Name = N'Zero-sequence reactance', @DataType = N'Decimal', @UnitCode = N'Ω', @Base = N'Primary', @DisplayGroup = N'Impedance', @DisplayOrder = 4, @Description = N'Zero-sequence line reactance, ohms primary, end to end (the imaginary part of Z0).', @ActorId = @author;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'LengthMiles', @Name = N'Length', @DataType = N'Decimal', @UnitCode = N'mi', @Base = NULL, @DisplayGroup = N'Impedance', @DisplayOrder = 5, @Description = N'Line length in miles, terminal to terminal (the legacy rationales: ''LL=8.49 miles''; the SEL-221F''s LL setting is the fault locator''s line length).', @ActorId = @author;
    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = N'ChargingMvaPerMile', @Name = N'Charging (MVA per mile)', @DataType = N'Decimal', @UnitCode = NULL, @Base = NULL, @DisplayGroup = N'Impedance', @DisplayOrder = 6, @Description = N'Line charging in MVA per mile, used for the supervisory overcurrent pickups (A4811.docx: ''ICharge=0.128 MVA/mile*8.49 miles*4.18 amps/MVA''). Optional.', @ActorId = @author;
    EXEC [config].[ApproveDefinitionVersion] @VersionRowId = @v, @ActorId = @approver;
END
UPDATE [ref].[AssetType] SET [DefaultTemplateDefinitionEntityId] = @e WHERE [AssetTypeCode] = N'Line' AND ([DefaultTemplateDefinitionEntityId] IS NULL OR [DefaultTemplateDefinitionEntityId] <> @e);
GO
