-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [document].[CharacteristicValue_SoftDelete]
    @EntityId UNIQUEIDENTIFIER,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    -- decision 71: soft delete closes belief only; ValidTo is untouched
    UPDATE [document].[CharacteristicValue] SET [IsDeleted] = 1, [DeletedBy] = @ActorId, [DeletedAt] = @now, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50105, N'document.CharacteristicValue: nothing live to delete for @EntityId.', 1;
END;
