-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [document].[ConfigurationFile_Update]
    @RevisionRowId UNIQUEIDENTIFIER,
    @DeviceEntityId UNIQUEIDENTIFIER = NULL,
    @FileKind NVARCHAR(20),
    @ModelId UNIQUEIDENTIFIER = NULL,
    @FirmwareVersionId UNIQUEIDENTIFIER = NULL,
    @CaptureKind NVARCHAR(20),
    @InServiceFrom DATETIMEOFFSET(7) = NULL,
    @InServiceTo DATETIMEOFFSET(7) = NULL,
    @InServiceFromQuality TINYINT = 0,
    @DifferentialRecordEntityId UNIQUEIDENTIFIER = NULL,
    @ParseStatus NVARCHAR(20) = NULL,
    @ParseError NVARCHAR(MAX) = NULL,
    @SettingsGroupCount TINYINT = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [document].[ConfigurationFile] SET [DeviceEntityId] = @DeviceEntityId, [FileKind] = @FileKind, [ModelId] = @ModelId, [FirmwareVersionId] = @FirmwareVersionId, [CaptureKind] = @CaptureKind, [InServiceFrom] = @InServiceFrom, [InServiceTo] = @InServiceTo, [InServiceFromQuality] = @InServiceFromQuality, [DifferentialRecordEntityId] = @DifferentialRecordEntityId, [ParseStatus] = @ParseStatus, [ParseError] = @ParseError, [SettingsGroupCount] = @SettingsGroupCount, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RevisionRowId] = @RevisionRowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'document.ConfigurationFile: no live row with that key.', 1;
END;
