-- #219 (2026-09-21): the rationale the platform generates for an outstanding settings revision — one Document of class Rationale
-- with one Draft revision that holds the engineer's inputs (document.CharacteristicValue rows against the rationale template's
-- characteristic definitions, document.SetRationaleValue) and the files the engine writes (rationale.json, rationale.docx),
-- linked About the configuration-file revision it justifies (SubjectKind DocumentRevision — never the device, as #217).
-- document.Rationale points at the template version (CharacteristicSchema.RationaleDevice) the inputs and sections come from.
-- Idempotent: the Draft rationale of that revision is returned when one exists (its template pointer brought up to date).
--   50296 the settings revision is not an outstanding (Draft) configuration-file revision
CREATE PROCEDURE [document].[CreateRationale]
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @RevisionRowId UNIQUEIDENTIFIER = NULL OUTPUT,
    @DocumentEntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @Created BIT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    DECLARE @status NVARCHAR(20), @device UNIQUEIDENTIFIER, @deviceName NVARCHAR(200), @label NVARCHAR(20);
    SELECT @status = r.[Status], @device = cf.[DeviceEntityId], @label = r.[RevisionLabel]
      FROM [document].[vRevision] r JOIN [document].[vConfigurationFile] cf ON cf.[RevisionRowId] = r.[RowId]
     WHERE r.[RowId] = @ConfigurationFileRevisionRowId;
    IF @status IS NULL OR @status <> N'Draft'
        THROW 50296, N'document.CreateRationale: a rationale is written for an outstanding (Draft) configuration-file revision only.', 1;
    SELECT @deviceName = [Name] FROM [asset].[vAsset] WHERE [EntityId] = @device;

    -- the Draft rationale this revision already has
    SELECT TOP (1) @RevisionRowId = r.[RowId], @DocumentEntityId = r.[DocumentEntityId]
      FROM [document].[vRevisionLink] l
      JOIN [document].[vRevision] r ON r.[RowId] = l.[RevisionRowId] AND r.[Status] = N'Draft'
      JOIN [document].[Rationale] ra ON ra.[RevisionRowId] = r.[RowId] AND ra.[IsDeleted] = 0
     WHERE l.[SubjectKind] = N'DocumentRevision' AND l.[SubjectEntityId] = @ConfigurationFileRevisionRowId AND l.[LinkKind] = N'About'
     ORDER BY r.[CreatedAt] DESC;
    IF @RevisionRowId IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM [document].[Rationale] WHERE [RevisionRowId] = @RevisionRowId AND [IsDeleted] = 0 AND ISNULL([DeviceTemplateDefinitionVersionRowId], '00000000-0000-0000-0000-000000000000') <> @DefinitionVersionRowId)
            EXEC [document].[Rationale_Update] @RevisionRowId = @RevisionRowId, @DeviceTemplateDefinitionVersionRowId = @DefinitionVersionRowId, @ActorId = @ActorId;
        SET @Created = 0;
        RETURN;
    END

    DECLARE @cls UNIQUEIDENTIFIER = (SELECT [EntityId] FROM [config].[vDefinition] WHERE [DefinitionKind] = N'CharacteristicSchema.DocumentClass' AND [DefinitionKey] = N'Rationale');
    IF @cls IS NULL THROW 50296, N'document.CreateRationale: the document class Rationale is not seeded.', 1;
    DECLARE @title NVARCHAR(200) = LEFT(CONCAT(N'Rationale — ', ISNULL(@deviceName, N'device'), N' rev ', ISNULL(@label, N'?')), 200);
    DECLARE @revEntity UNIQUEIDENTIFIER;
    BEGIN TRANSACTION;
    EXEC [document].[Document_Add] @DocumentClassDefinitionEntityId = @cls, @Title = @title,
         @Description = N'The settings rationale generated by the platform from the rationale template: one section per protective element (#219).',
         @ValidFrom = @now, @ActorId = @ActorId, @EntityId = @DocumentEntityId OUTPUT;
    EXEC [document].[Revision_Add] @DocumentEntityId = @DocumentEntityId, @RevisionLabel = N'1', @Status = N'Draft', @PreparedByActorId = @ActorId, @PreparedAt = @now,
         @ChangeNote = N'generated by the platform from the rationale template (#219)', @ValidFrom = @now, @ActorId = @ActorId, @EntityId = @revEntity OUTPUT, @RowId = @RevisionRowId OUTPUT;
    EXEC [document].[Rationale_Add] @RevisionRowId = @RevisionRowId, @DeviceTemplateDefinitionVersionRowId = @DefinitionVersionRowId, @ActorId = @ActorId;
    EXEC [document].[RevisionLink_Add] @RevisionRowId = @RevisionRowId, @LinkKind = N'About', @SubjectKind = N'DocumentRevision', @SubjectEntityId = @ConfigurationFileRevisionRowId,
         @ValidFrom = @now, @ActorId = @ActorId;
    DECLARE @detail NVARCHAR(MAX) = CONCAT(N'{"action":"rationale-created","configurationFileRevisionRowId":"', CONVERT(NVARCHAR(36), @ConfigurationFileRevisionRowId),
        N'","templateVersionRowId":"', CONVERT(NVARCHAR(36), @DefinitionVersionRowId), N'"}');
    EXEC [audit].[LogAction] @ActionKindCode = N'Administrative', @SubjectSchema = N'document', @SubjectTable = N'Revision', @SubjectEntityId = @revEntity, @SubjectRowId = @RevisionRowId,
         @ActorId = @ActorId, @Detail = @detail, @OccurredAt = @now;
    COMMIT TRANSACTION;
    SET @Created = 1;
END;
GO
GRANT EXECUTE ON [document].[CreateRationale] TO [app_execute];
GO
