-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [document].[File_Add]
    @RevisionRowId UNIQUEIDENTIFIER,
    @FileName NVARCHAR(260),
    @MimeType NVARCHAR(100),
    @SizeBytes BIGINT,
    @Sha256 BINARY(32),
    @FileStreamId UNIQUEIDENTIFIER = NULL,
    @FileRole NVARCHAR(20),
    @RedactionStatus NVARCHAR(20) = N'None',
    @IsCapturedFromDevice BIT = 0,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [document].[FileRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [document].[File] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [RevisionRowId], [FileName], [MimeType], [SizeBytes], [Sha256], [FileStreamId], [FileRole], [RedactionStatus], [IsCapturedFromDevice])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @RevisionRowId, @FileName, @MimeType, @SizeBytes, @Sha256, @FileStreamId, @FileRole, @RedactionStatus, @IsCapturedFromDevice);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
