-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [document].[Rationale_Add]
    @RevisionRowId UNIQUEIDENTIFIER,
    @SchemeTypeTemplateDefinitionVersionRowId UNIQUEIDENTIFIER = NULL,
    @DeviceTemplateDefinitionVersionRowId UNIQUEIDENTIFIER = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    INSERT [document].[Rationale] ([RevisionRowId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SchemeTypeTemplateDefinitionVersionRowId], [DeviceTemplateDefinitionVersionRowId])
    VALUES (@RevisionRowId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SchemeTypeTemplateDefinitionVersionRowId, @DeviceTemplateDefinitionVersionRowId);
END;
