-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [document].[RevisionLink_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @RevisionRowId UNIQUEIDENTIFIER,
    @LinkKind NVARCHAR(20),
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @DrawingKey NVARCHAR(100) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'document.RevisionLink: no Subject entity of kind @SubjectKind with that id.', 1;
    IF NOT EXISTS (SELECT 1 FROM [document].[RevisionLink] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'document.RevisionLink: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [document].[RevisionLink] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [document].[RevisionLink] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [RevisionRowId], [LinkKind], [SubjectKind], [SubjectEntityId], [DrawingKey])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @RevisionRowId, @LinkKind, @SubjectKind, @SubjectEntityId, @DrawingKey);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
