-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [location].[Node_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @NodeTypeCode NVARCHAR(40),
    @ParentEntityId UNIQUEIDENTIFIER = NULL,
    @Path NVARCHAR(900),
    @Depth TINYINT,
    @SiblingOrder INT = 0,
    @Name NVARCHAR(200),
    @SubtypeCode NVARCHAR(40) = NULL,
    @Location GEOGRAPHY = NULL,
    @Extent GEOGRAPHY = NULL,
    @RegionSplitOfEntityId UNIQUEIDENTIFIER = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [location].[Node] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'location.Node: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [location].[Node] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [location].[Node] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [NodeTypeCode], [ParentEntityId], [Path], [Depth], [SiblingOrder], [Name], [SubtypeCode], [Location], [Extent], [RegionSplitOfEntityId], [WorkRequestEntityId], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @NodeTypeCode, @ParentEntityId, @Path, @Depth, @SiblingOrder, @Name, @SubtypeCode, @Location, @Extent, @RegionSplitOfEntityId, @WorkRequestEntityId, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
