-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [location].[Segment_Add]
    @FromAdjacencyRowId UNIQUEIDENTIFIER = NULL,
    @ToAdjacencyRowId UNIQUEIDENTIFIER = NULL,
    @Length DECIMAL(12,3) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    IF NOT EXISTS (SELECT 1 FROM [location].[NodeRegistry] WHERE [EntityId] = @EntityId)
        THROW 50102, N'location.Segment: @EntityId is not a registered Node.', 1;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [location].[Segment] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [FromAdjacencyRowId], [ToAdjacencyRowId], [Length])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @FromAdjacencyRowId, @ToAdjacencyRowId, @Length);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
