-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [audit].[vActionLog] AS
SELECT [ActionLogId], [OccurredAt], [ActorId], [ActionKindCode], [SubjectSchema], [SubjectTable], [SubjectEntityId], [SubjectRowId], [DefinitionVersionRowId], [Detail]
FROM [audit].[ActionLog];
GO
GRANT SELECT ON [audit].[vActionLog] TO [app_execute];
GO
