-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [personnel].[vPersonQualificationHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [PersonEntityId], [QualificationTypeCode], [GrantedAt], [GrantedByActorId], [ExpiresAt], [AssessmentRecordEntityId], [OjtHoursCompleted], [RevokedAt], [RevocationReason], [SysStart], [SysEnd]
FROM [personnel].[PersonQualification] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [personnel].[vPersonQualificationHistory] TO [app_execute];
GO
