-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [personnel].[vPositionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [EntityEntityId], [Title], [ReportsToPositionEntityId], [IsActive], [SysStart], [SysEnd]
FROM [personnel].[Position] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [personnel].[vPositionHistory] TO [app_execute];
GO
