-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [personnel].[vQualificationTypeHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [QualificationTypeCode], [Name], [WorkCategory], [ApplicableAssetTypeCode], [RequiredOjtHours], [RequiredExperienceYears], [RecertificationDays], [RequiresSupervisorSignOff], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [personnel].[QualificationType] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [personnel].[vQualificationTypeHistory] TO [app_execute];
GO
