-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [personnel].[vQualificationTypeModuleHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [QualificationTypeCode], [TrainingModuleCode], [IsPrerequisite], [MinimumPassScore], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsActive], [MigrationRunId], [SysStart], [SysEnd]
FROM [personnel].[QualificationTypeModule] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [personnel].[vQualificationTypeModuleHistory] TO [app_execute];
GO
