-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [device].[AdvisoryDisposition_Add]
    @AdvisoryEntityId UNIQUEIDENTIFIER,
    @DeviceEntityId UNIQUEIDENTIFIER,
    @Applicability NVARCHAR(20),
    @AssessedByActorId UNIQUEIDENTIFIER,
    @AssessedAt DATETIMEOFFSET(7),
    @Action NVARCHAR(20),
    @DueAt DATETIMEOFFSET(7) = NULL,
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @DeferralReason NVARCHAR(400) = NULL,
    @RiskAcceptedByActorId UNIQUEIDENTIFIER = NULL,
    @DeferralReviewAt DATETIMEOFFSET(7) = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [device].[AdvisoryDispositionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [device].[AdvisoryDisposition] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [AdvisoryEntityId], [DeviceEntityId], [Applicability], [AssessedByActorId], [AssessedAt], [Action], [DueAt], [CompletedAt], [DeferralReason], [RiskAcceptedByActorId], [DeferralReviewAt], [WorkRequestEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @AdvisoryEntityId, @DeviceEntityId, @Applicability, @AssessedByActorId, @AssessedAt, @Action, @DueAt, @CompletedAt, @DeferralReason, @RiskAcceptedByActorId, @DeferralReviewAt, @WorkRequestEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
