-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [device].[Advisory_Add]
    @IssuerEntityEntityId UNIQUEIDENTIFIER,
    @AdvisoryReference NVARCHAR(100),
    @AdvisoryKind NVARCHAR(40),
    @Severity NVARCHAR(20) = NULL,
    @PublishedAt DATETIMEOFFSET(7) = NULL,
    @NotifiedAt DATETIMEOFFSET(7) = NULL,
    @DocumentEntityId UNIQUEIDENTIFIER = NULL,
    @Summary NVARCHAR(MAX) = NULL,
    @MitigationSummary NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [device].[AdvisoryRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [device].[Advisory] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [IssuerEntityEntityId], [AdvisoryReference], [AdvisoryKind], [Severity], [PublishedAt], [NotifiedAt], [DocumentEntityId], [Summary], [MitigationSummary])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @IssuerEntityEntityId, @AdvisoryReference, @AdvisoryKind, @Severity, @PublishedAt, @NotifiedAt, @DocumentEntityId, @Summary, @MitigationSummary);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
