-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [device].[Device_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @PartNumber NVARCHAR(100) = NULL,
    @HardwareRevision NVARCHAR(50) = NULL,
    @ManufacturedAt DATE = NULL,
    @CurrentFirmwareVersionId UNIQUEIDENTIFIER = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [device].[Device] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'device.Device: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [device].[Device] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [device].[Device] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [PartNumber], [HardwareRevision], [ManufacturedAt], [CurrentFirmwareVersionId], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @PartNumber, @HardwareRevision, @ManufacturedAt, @CurrentFirmwareVersionId, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
