-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [device].[FirmwareHistory_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @DeviceEntityId UNIQUEIDENTIFIER,
    @FirmwareVersionId UNIQUEIDENTIFIER,
    @AppliedByActorId UNIQUEIDENTIFIER = NULL,
    @VerifiedByActorId UNIQUEIDENTIFIER = NULL,
    @VerifiedAt DATETIMEOFFSET(7) = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @AdvisoryDispositionEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [device].[FirmwareHistory] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'device.FirmwareHistory: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [device].[FirmwareHistory] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [device].[FirmwareHistory] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DeviceEntityId], [FirmwareVersionId], [AppliedByActorId], [VerifiedByActorId], [VerifiedAt], [WorkRequestEntityId], [AdvisoryDispositionEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DeviceEntityId, @FirmwareVersionId, @AppliedByActorId, @VerifiedByActorId, @VerifiedAt, @WorkRequestEntityId, @AdvisoryDispositionEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
