-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [device].[LifecycleEvent_Append]
    @DeviceEntityId UNIQUEIDENTIFIER,
    @EventKind NVARCHAR(20),
    @OccurredAt DATETIMEOFFSET(7),
    @TimeSourceQuality TINYINT,
    @ActorId UNIQUEIDENTIFIER,
    @NodeEntityId UNIQUEIDENTIFIER = NULL,
    @CustodyLocationEntityId UNIQUEIDENTIFIER = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @RecordEntityId UNIQUEIDENTIFIER = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @LifecycleEventId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    INSERT [device].[LifecycleEvent] ([DeviceEntityId], [EventKind], [OccurredAt], [TimeSourceQuality], [ActorId], [NodeEntityId], [CustodyLocationEntityId], [WorkRequestEntityId], [RecordEntityId], [Notes])
    VALUES (@DeviceEntityId, @EventKind, @OccurredAt, @TimeSourceQuality, @ActorId, @NodeEntityId, @CustodyLocationEntityId, @WorkRequestEntityId, @RecordEntityId, @Notes);
    SET @LifecycleEventId = SCOPE_IDENTITY();
END;
