-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [personnel].[PersonQualification_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @PersonEntityId UNIQUEIDENTIFIER,
    @QualificationTypeCode NVARCHAR(40),
    @GrantedAt DATETIMEOFFSET(7),
    @GrantedByActorId UNIQUEIDENTIFIER,
    @ExpiresAt DATETIMEOFFSET(7) = NULL,
    @AssessmentRecordEntityId UNIQUEIDENTIFIER = NULL,
    @OjtHoursCompleted DECIMAL(8,2) = NULL,
    @RevokedAt DATETIMEOFFSET(7) = NULL,
    @RevocationReason NVARCHAR(400) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [personnel].[PersonQualification] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'personnel.PersonQualification: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [personnel].[PersonQualification] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [personnel].[PersonQualification] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [PersonEntityId], [QualificationTypeCode], [GrantedAt], [GrantedByActorId], [ExpiresAt], [AssessmentRecordEntityId], [OjtHoursCompleted], [RevokedAt], [RevocationReason])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @PersonEntityId, @QualificationTypeCode, @GrantedAt, @GrantedByActorId, @ExpiresAt, @AssessmentRecordEntityId, @OjtHoursCompleted, @RevokedAt, @RevocationReason);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
