-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [personnel].[QualificationType_Deactivate]
    @QualificationTypeCode NVARCHAR(40),
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [personnel].[QualificationType] SET [IsActive] = 0, [ModifiedBy] = @ActorId, [ModifiedAt] = @now WHERE [QualificationTypeCode] = @QualificationTypeCode AND [IsActive] = 1;
    IF @@ROWCOUNT = 0 THROW 50106, N'personnel.QualificationType: no active row with that key.', 1;
END;
