-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [personnel].[QualificationTypeModule_Upsert]
    @QualificationTypeCode NVARCHAR(40),
    @TrainingModuleCode NVARCHAR(40),
    @IsPrerequisite BIT = 0,
    @MinimumPassScore DECIMAL(5,2) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [personnel].[QualificationTypeModule] t WHERE t.[QualificationTypeCode] = @QualificationTypeCode AND t.[TrainingModuleCode] = @TrainingModuleCode)
        UPDATE t SET [IsPrerequisite] = @IsPrerequisite, [MinimumPassScore] = @MinimumPassScore, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [personnel].[QualificationTypeModule] t WHERE t.[QualificationTypeCode] = @QualificationTypeCode AND t.[TrainingModuleCode] = @TrainingModuleCode;
    ELSE
        INSERT [personnel].[QualificationTypeModule] ([QualificationTypeCode], [TrainingModuleCode], [IsPrerequisite], [MinimumPassScore], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@QualificationTypeCode, @TrainingModuleCode, @IsPrerequisite, @MinimumPassScore, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
