-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [archive].[Manifest_Append]
    @SourceSchema SYSNAME,
    @SourceTable SYSNAME,
    @KeyRangeFrom NVARCHAR(100),
    @KeyRangeTo NVARCHAR(100),
    @RowCount BIGINT,
    @MovedAt DATETIMEOFFSET(7),
    @Destination NVARCHAR(40),
    @DestinationReference NVARCHAR(400),
    @Sha256 BINARY(32),
    @MovedByActorId UNIQUEIDENTIFIER,
    @ManifestId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [archive].[Manifest] ([SourceSchema], [SourceTable], [KeyRangeFrom], [KeyRangeTo], [RowCount], [MovedAt], [Destination], [DestinationReference], [Sha256], [MovedByActorId])
    VALUES (@SourceSchema, @SourceTable, @KeyRangeFrom, @KeyRangeTo, @RowCount, @MovedAt, @Destination, @DestinationReference, @Sha256, @MovedByActorId);
    SET @ManifestId = SCOPE_IDENTITY();
END;
