-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[Finding_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @FindingCategoryCode NVARCHAR(40),
    @Severity NVARCHAR(20),
    @Description NVARCHAR(MAX),
    @AsFoundValue NVARCHAR(400) = NULL,
    @ExpectedValue NVARCHAR(400) = NULL,
    @Disposition NVARCHAR(30) = N'Open',
    @CorrectiveWorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @ClosedByActorId UNIQUEIDENTIFIER = NULL,
    @ClosedAt DATETIMEOFFSET(7) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [record].[Finding] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'record.Finding: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [record].[Finding] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[Finding] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [FindingCategoryCode], [Severity], [Description], [AsFoundValue], [ExpectedValue], [Disposition], [CorrectiveWorkRequestEntityId], [ClosedByActorId], [ClosedAt])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @FindingCategoryCode, @Severity, @Description, @AsFoundValue, @ExpectedValue, @Disposition, @CorrectiveWorkRequestEntityId, @ClosedByActorId, @ClosedAt);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
