-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[Readback_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @ProducedConfigurationFileRevisionRowId UNIQUEIDENTIFIER,
    @ComparedToConfigurationFileRevisionRowId UNIQUEIDENTIFIER = NULL,
    @ComparisonResult NVARCHAR(20),
    @DifferenceCount INT = NULL,
    @DifferenceDetailRecordEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [record].[Readback] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'record.Readback: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [record].[Readback] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[Readback] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [ProducedConfigurationFileRevisionRowId], [ComparedToConfigurationFileRevisionRowId], [ComparisonResult], [DifferenceCount], [DifferenceDetailRecordEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @ProducedConfigurationFileRevisionRowId, @ComparedToConfigurationFileRevisionRowId, @ComparisonResult, @DifferenceCount, @DifferenceDetailRecordEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
