-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[Record_Add]
    @RecordKindCode NVARCHAR(40),
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @SecondSubjectKind NVARCHAR(40) = NULL,
    @SecondSubjectEntityId UNIQUEIDENTIFIER = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @OccurredAt DATETIMEOFFSET(7),
    @TimeSourceQuality TINYINT = 3,
    @PerformedByActorId UNIQUEIDENTIFIER,
    @WitnessedByActorId UNIQUEIDENTIFIER = NULL,
    @OverallResult NVARCHAR(20) = NULL,
    @Summary NVARCHAR(1000) = NULL,
    @TemplateDefinitionVersionRowId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'record.Record: no Subject entity of kind @SubjectKind with that id.', 1;
    IF @SecondSubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SecondSubjectKind, @SecondSubjectEntityId) = 0
        THROW 50101, N'record.Record: no SecondSubject entity of kind @SecondSubjectKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [record].[RecordRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[Record] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [RecordKindCode], [SubjectKind], [SubjectEntityId], [SecondSubjectKind], [SecondSubjectEntityId], [WorkRequestEntityId], [OccurredAt], [TimeSourceQuality], [PerformedByActorId], [WitnessedByActorId], [OverallResult], [Summary], [TemplateDefinitionVersionRowId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @RecordKindCode, @SubjectKind, @SubjectEntityId, @SecondSubjectKind, @SecondSubjectEntityId, @WorkRequestEntityId, @OccurredAt, @TimeSourceQuality, @PerformedByActorId, @WitnessedByActorId, @OverallResult, @Summary, @TemplateDefinitionVersionRowId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
