-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[TestReading_Add]
    @TestResultEntityId UNIQUEIDENTIFIER,
    @TestPlanReadingRowId UNIQUEIDENTIFIER,
    @Phase NVARCHAR(20),
    @TextValue NVARCHAR(400) = NULL,
    @IntegerValue BIGINT = NULL,
    @DecimalValue DECIMAL(28,10) = NULL,
    @BooleanValue BIT = NULL,
    @DateTimeValue DATETIMEOFFSET(7) = NULL,
    @ReferenceEntityId UNIQUEIDENTIFIER = NULL,
    @UnitOverrideCode NVARCHAR(20) = NULL,
    @IsWithinLimits BIT = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [record].[TestReadingRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[TestReading] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [TestResultEntityId], [TestPlanReadingRowId], [Phase], [TextValue], [IntegerValue], [DecimalValue], [BooleanValue], [DateTimeValue], [ReferenceEntityId], [UnitOverrideCode], [IsWithinLimits])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @TestResultEntityId, @TestPlanReadingRowId, @Phase, @TextValue, @IntegerValue, @DecimalValue, @BooleanValue, @DateTimeValue, @ReferenceEntityId, @UnitOverrideCode, @IsWithinLimits);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
