-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[TestReading_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @TestResultEntityId UNIQUEIDENTIFIER,
    @TestPlanReadingRowId UNIQUEIDENTIFIER,
    @Phase NVARCHAR(20),
    @TextValue NVARCHAR(400) = NULL,
    @IntegerValue BIGINT = NULL,
    @DecimalValue DECIMAL(28,10) = NULL,
    @BooleanValue BIT = NULL,
    @DateTimeValue DATETIMEOFFSET(7) = NULL,
    @ReferenceEntityId UNIQUEIDENTIFIER = NULL,
    @UnitOverrideCode NVARCHAR(20) = NULL,
    @IsWithinLimits BIT = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [record].[TestReading] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'record.TestReading: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [record].[TestReading] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[TestReading] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [TestResultEntityId], [TestPlanReadingRowId], [Phase], [TextValue], [IntegerValue], [DecimalValue], [BooleanValue], [DateTimeValue], [ReferenceEntityId], [UnitOverrideCode], [IsWithinLimits])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @TestResultEntityId, @TestPlanReadingRowId, @Phase, @TextValue, @IntegerValue, @DecimalValue, @BooleanValue, @DateTimeValue, @ReferenceEntityId, @UnitOverrideCode, @IsWithinLimits);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
