-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [record].[TestResult_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @TestSheetEntityId UNIQUEIDENTIFIER,
    @TestPlanStepRowId UNIQUEIDENTIFIER,
    @StepSubjectKind NVARCHAR(40) = NULL,
    @StepSubjectEntityId UNIQUEIDENTIFIER = NULL,
    @Status NVARCHAR(20),
    @NotPerformedReason NVARCHAR(400) = NULL,
    @Outcome NVARCHAR(20) = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @StepSubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@StepSubjectKind, @StepSubjectEntityId) = 0
        THROW 50101, N'record.TestResult: no StepSubject entity of kind @StepSubjectKind with that id.', 1;
    IF NOT EXISTS (SELECT 1 FROM [record].[TestResult] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'record.TestResult: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [record].[TestResult] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [record].[TestResult] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [TestSheetEntityId], [TestPlanStepRowId], [StepSubjectKind], [StepSubjectEntityId], [Status], [NotPerformedReason], [Outcome], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @TestSheetEntityId, @TestPlanStepRowId, @StepSubjectKind, @StepSubjectEntityId, @Status, @NotPerformedReason, @Outcome, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
