-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [audit].[BackupRun_Append]
    @PolicyDefinitionVersionRowId UNIQUEIDENTIFIER,
    @BackupKind NVARCHAR(20),
    @DatabaseName SYSNAME,
    @StartedAt DATETIMEOFFSET(7),
    @CompletedAt DATETIMEOFFSET(7) = NULL,
    @DestinationReference NVARCHAR(400) = NULL,
    @SizeBytes BIGINT = NULL,
    @ChecksumVerified BIT = 0,
    @VerifyOnlyPassed BIT = NULL,
    @Outcome NVARCHAR(20),
    @ServerMessage NVARCHAR(MAX) = NULL,
    @AchievedRpoMinutes INT = NULL,
    @BackupRunId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [audit].[BackupRun] ([PolicyDefinitionVersionRowId], [BackupKind], [DatabaseName], [StartedAt], [CompletedAt], [DestinationReference], [SizeBytes], [ChecksumVerified], [VerifyOnlyPassed], [Outcome], [ServerMessage], [AchievedRpoMinutes])
    VALUES (@PolicyDefinitionVersionRowId, @BackupKind, @DatabaseName, @StartedAt, @CompletedAt, @DestinationReference, @SizeBytes, @ChecksumVerified, @VerifyOnlyPassed, @Outcome, @ServerMessage, @AchievedRpoMinutes);
    SET @BackupRunId = SCOPE_IDENTITY();
END;
