-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [platform].[vRelease] AS
SELECT [ReleaseId], [Version], [ReleasedAt], [DacpacHash], [PackageHash], [SbomDocumentEntityId], [ReleaseDocumentEntityId], [RecordedByActorId], [Notes]
FROM [platform].[Release];
GO
GRANT SELECT ON [platform].[vRelease] TO [app_execute];
GO
