-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE FUNCTION [compliance].[fEvidenceLinkAsOf] (@validAt DATETIMEOFFSET(7), @believedAtUtc DATETIME2(7))
RETURNS TABLE AS RETURN
-- bi-temporal as-of (decision 69): rows valid at @validAt as the database believed them at
-- @believedAtUtc (system time, UTC). A row deleted after @believedAtUtc is still returned.
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ObligationInstanceRowId], [RecordRowId], [JudgedByActorId], [JudgedAt], [Sufficiency], [EvidenceDefinitionVersionRowId], [Notes], [SysStart], [SysEnd]
FROM (
    SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ObligationInstanceRowId], [RecordRowId], [JudgedByActorId], [JudgedAt], [Sufficiency], [EvidenceDefinitionVersionRowId], [Notes], [SysStart], [SysEnd],
           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn
    FROM [compliance].[EvidenceLink] FOR SYSTEM_TIME AS OF @believedAtUtc
    WHERE [IsDeleted] = 0
      AND [ValidFrom] <= @validAt
      AND ([ValidTo] IS NULL OR [ValidTo] > @validAt)
) x WHERE x._rn = 1;
GO
GRANT SELECT ON [compliance].[fEvidenceLinkAsOf] TO [app_execute];
GO
