-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [scheme].[FaultRecord_Add]
    @OperationEntityId UNIQUEIDENTIFIER,
    @FaultType NVARCHAR(40) = NULL,
    @PhasesInvolved NVARCHAR(10) = NULL,
    @FaultedAssetEntityId UNIQUEIDENTIFIER = NULL,
    @LocationMethod NVARCHAR(40) = NULL,
    @DistanceKm DECIMAL(12,3) = NULL,
    @DistancePercent DECIMAL(7,3) = NULL,
    @CurrentKaA DECIMAL(12,4) = NULL,
    @CurrentKaB DECIMAL(12,4) = NULL,
    @CurrentKaC DECIMAL(12,4) = NULL,
    @CurrentKaN DECIMAL(12,4) = NULL,
    @ResistanceOhm DECIMAL(18,6) = NULL,
    @ReactanceOhm DECIMAL(18,6) = NULL,
    @IsFieldConfirmed BIT = 0,
    @FieldConfirmedAt DATETIMEOFFSET(7) = NULL,
    @PatrolRecordEntityId UNIQUEIDENTIFIER = NULL,
    @OscillographyDocumentEntityId UNIQUEIDENTIFIER = NULL,
    @ComputedByActorId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [scheme].[FaultRecordRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [scheme].[FaultRecord] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [OperationEntityId], [FaultType], [PhasesInvolved], [FaultedAssetEntityId], [LocationMethod], [DistanceKm], [DistancePercent], [CurrentKaA], [CurrentKaB], [CurrentKaC], [CurrentKaN], [ResistanceOhm], [ReactanceOhm], [IsFieldConfirmed], [FieldConfirmedAt], [PatrolRecordEntityId], [OscillographyDocumentEntityId], [ComputedByActorId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @OperationEntityId, @FaultType, @PhasesInvolved, @FaultedAssetEntityId, @LocationMethod, @DistanceKm, @DistancePercent, @CurrentKaA, @CurrentKaB, @CurrentKaC, @CurrentKaN, @ResistanceOhm, @ReactanceOhm, @IsFieldConfirmed, @FieldConfirmedAt, @PatrolRecordEntityId, @OscillographyDocumentEntityId, @ComputedByActorId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
