-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [scheme].[ProtectionOperationSnapshot_Append]
    @OperationEntityId UNIQUEIDENTIFIER,
    @SubjectKind NVARCHAR(40),
    @SubjectRowId UNIQUEIDENTIFIER,
    @CapturedAt DATETIMEOFFSET(7),
    @SnapshotId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [scheme].[ProtectionOperationSnapshot] ([OperationEntityId], [SubjectKind], [SubjectRowId], [CapturedAt])
    VALUES (@OperationEntityId, @SubjectKind, @SubjectRowId, @CapturedAt);
    SET @SnapshotId = SCOPE_IDENTITY();
END;
