-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [scheme].[ProtectionCondition_Add]
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @ConditionKindCode NVARCHAR(40),
    @ConditionValue NVARCHAR(200) = NULL,
    @Reason NVARCHAR(400) = NULL,
    @OpenedByActorId UNIQUEIDENTIFIER = NULL,
    @ClosedByActorId UNIQUEIDENTIFIER = NULL,
    @AuthorisedByActorId UNIQUEIDENTIFIER = NULL,
    @RevertObligationInstanceEntityId UNIQUEIDENTIFIER = NULL,
    @NotificationRecordEntityId UNIQUEIDENTIFIER = NULL,
    @WorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'scheme.ProtectionCondition: no Subject entity of kind @SubjectKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [scheme].[ProtectionConditionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [scheme].[ProtectionCondition] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [ConditionKindCode], [ConditionValue], [Reason], [OpenedByActorId], [ClosedByActorId], [AuthorisedByActorId], [RevertObligationInstanceEntityId], [NotificationRecordEntityId], [WorkRequestEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SubjectKind, @SubjectEntityId, @ConditionKindCode, @ConditionValue, @Reason, @OpenedByActorId, @ClosedByActorId, @AuthorisedByActorId, @RevertObligationInstanceEntityId, @NotificationRecordEntityId, @WorkRequestEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
