-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [scheme].[ProtectionOperation_Add]
    @OccurredAt DATETIMEOFFSET(7),
    @TimeSourceQuality TINYINT,
    @PrimaryAssetEntityId UNIQUEIDENTIFIER,
    @Outcome NVARCHAR(20),
    @ElementsOperated NVARCHAR(400) = NULL,
    @ClearingTimeMs INT = NULL,
    @RecloseAttempts TINYINT = NULL,
    @RecloseSuccessful BIT = NULL,
    @DataSource NVARCHAR(20),
    @IsConfirmed BIT = 0,
    @ReviewRecordEntityId UNIQUEIDENTIFIER = NULL,
    @ExceptionEntityId UNIQUEIDENTIFIER = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [scheme].[ProtectionOperationRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [scheme].[ProtectionOperation] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [OccurredAt], [TimeSourceQuality], [PrimaryAssetEntityId], [Outcome], [ElementsOperated], [ClearingTimeMs], [RecloseAttempts], [RecloseSuccessful], [DataSource], [IsConfirmed], [ReviewRecordEntityId], [ExceptionEntityId], [Notes])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @OccurredAt, @TimeSourceQuality, @PrimaryAssetEntityId, @Outcome, @ElementsOperated, @ClearingTimeMs, @RecloseAttempts, @RecloseSuccessful, @DataSource, @IsConfirmed, @ReviewRecordEntityId, @ExceptionEntityId, @Notes);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
