-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [scheme].[SchemeAction_Add]
    @SchemeEntityId UNIQUEIDENTIFIER,
    @Sequence INT,
    @ActionKind NVARCHAR(20),
    @TargetAssetEntityId UNIQUEIDENTIFIER = NULL,
    @TargetNodeEntityId UNIQUEIDENTIFIER = NULL,
    @LoadMw DECIMAL(18,4) = NULL,
    @GenerationMw DECIMAL(18,4) = NULL,
    @Mvar DECIMAL(18,4) = NULL,
    @MaxExecutionMs INT = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [scheme].[SchemeActionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [scheme].[SchemeAction] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SchemeEntityId], [Sequence], [ActionKind], [TargetAssetEntityId], [TargetNodeEntityId], [LoadMw], [GenerationMw], [Mvar], [MaxExecutionMs], [Description])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SchemeEntityId, @Sequence, @ActionKind, @TargetAssetEntityId, @TargetNodeEntityId, @LoadMw, @GenerationMw, @Mvar, @MaxExecutionMs, @Description);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
