-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [event].[LightningStrike_Append]
    @SourceSystem NVARCHAR(50),
    @SourceStrikeId NVARCHAR(100),
    @OccurredAt DATETIMEOFFSET(7),
    @TimeSourceQuality TINYINT,
    @Location GEOGRAPHY,
    @AmplitudeKa DECIMAL(10,3) = NULL,
    @StationCount INT = NULL,
    @FeedRunId UNIQUEIDENTIFIER,
    @SourceHash BINARY(32) = NULL,
    @StrikeId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [event].[LightningStrike] ([SourceSystem], [SourceStrikeId], [OccurredAt], [TimeSourceQuality], [Location], [AmplitudeKa], [StationCount], [FeedRunId], [SourceHash])
    VALUES (@SourceSystem, @SourceStrikeId, @OccurredAt, @TimeSourceQuality, @Location, @AmplitudeKa, @StationCount, @FeedRunId, @SourceHash);
    SET @StrikeId = SCOPE_IDENTITY();
END;
