-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [event].[PhasorBlock_Append]
    @StreamId UNIQUEIDENTIFIER,
    @BlockStartAt DATETIMEOFFSET(7),
    @BlockEndAt DATETIMEOFFSET(7),
    @Encoding NVARCHAR(40),
    @Data VARBINARY(MAX),
    @PhasorBlockId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [event].[PhasorBlock] ([StreamId], [BlockStartAt], [BlockEndAt], [Encoding], [Data])
    VALUES (@StreamId, @BlockStartAt, @BlockEndAt, @Encoding, @Data);
    SET @PhasorBlockId = SCOPE_IDENTITY();
END;
