-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [event].[PmuStream_Append]
    @PmuDeviceEntityId UNIQUEIDENTIFIER,
    @ConfigurationFileRevisionRowId UNIQUEIDENTIFIER = NULL,
    @ReportingRateHz DECIMAL(18,4) = NULL,
    @StartedAt DATETIMEOFFSET(7),
    @EndedAt DATETIMEOFFSET(7) = NULL,
    @StreamId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @StreamId = ISNULL(@StreamId, NEWID());
    INSERT [event].[PmuStream] ([StreamId], [PmuDeviceEntityId], [ConfigurationFileRevisionRowId], [ReportingRateHz], [StartedAt], [EndedAt])
    VALUES (@StreamId, @PmuDeviceEntityId, @ConfigurationFileRevisionRowId, @ReportingRateHz, @StartedAt, @EndedAt);
END;
