"""A relay model's manual guide: the instruction manual's own words on how each setting is set, with its page (#235).

One generic generator; the data is one file per model, docs/design/examples/templates/<model>.manual-guide.json:

    {"key": "MANUAL_GUIDE_SEL_221F", "name": "...", "model": "SEL-221F", "settingsTemplate": "SETTINGS_TEXT_SEL_221F",
     "source": "<manual title, date code>", "sourceFile": "Z:\\...\\manual.pdf", "pageOffsets": "<how printed labels map to PDF pages>",
     "settings": {"27VLO": [{"page": "5-11", "pdfPage": 135, "quote": "...", "checked": "transcribed from the page image, <date>"}]}}

    python tools/manual_guide.py docs/design/examples/templates/sel-221f.manual-guide.json
      -> docs/schema/ddl/PostDeploy/Seed_config_ManualGuide_<MODEL>.sql   (register it in PostDeploy.sql once)
         docs/design/examples/templates/<model>.manual-guide.md            (the same quotes, for review)

The owner, 2026-09-23: "custom floatovers which are excerpts from the manual on the various settings on how they should be set",
"a hotlink to the exact location in the manual", and "keep good notes so that you can do the same for other templates". The rules
for the data (every quote verbatim from the page IMAGE, never the PDF's OCR text; the printed page and the PDF page read off the
image; an equation keeps its own line; "…" marks an elision; nothing summarised; a setting the manual does not address gets no
entry) and the whole procedure are in docs/runbook/MANUAL-GUIDE.md. The generator refuses a quote without its page, PDF page or
check, and a quote holding "[?]" (a word the transcriber could not read — settle it on the page first).
"""
import hashlib, io, json, os, re, sys

NL = "\r\n"


def check(doc):
    problems = []
    for k in ("key", "name", "model", "settingsTemplate", "source", "settings"):
        if not doc.get(k):
            problems.append("missing " + k)
    for code, quotes in (doc.get("settings") or {}).items():
        for i, x in enumerate(quotes):
            where = code + "[" + str(i) + "]"
            if not str(x.get("quote", "")).strip(): problems.append(where + ": empty quote")
            if not re.fullmatch(r"[0-9A-Z]{1,2}-\d{1,3}", str(x.get("page", ""))): problems.append(where + ": printed page not like 5-11")
            if not isinstance(x.get("pdfPage"), int) or x["pdfPage"] < 1: problems.append(where + ": no PDF page")
            if not str(x.get("checked", "")).strip(): problems.append(where + ": not recorded as checked against the page image")
            if "[?]" in str(x.get("quote", "")): problems.append(where + ": holds [?] - read that word off the page first")
    return problems


def payload_of(doc):
    return {"g": 1, "kind": "manualGuide", "key": doc["key"], "name": doc["name"], "settingsTemplate": doc["settingsTemplate"],
            "source": doc["source"], "settings": doc["settings"]}


def q(s):
    return "N'" + s.replace("'", "''") + "'"


def sql(doc, script):
    payload = json.dumps(payload_of(doc), ensure_ascii=False, separators=(",", ":"))
    note = "seed " + hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]
    key, model = doc["key"], doc["model"]
    desc = "What the " + model + " instruction manual says on how each setting is set, in its own words with the page."
    L = [
        "-- GENERATED by tools/manual_guide.py from " + script + " - do not edit; edit the data there and regenerate.",
        "-- #235: the " + model + " manual guide - the manual's own words on how each setting is set, verbatim from the page image,",
        "-- with the printed page and the PDF page (the Settings tab's floatover and its link into the manual). Idempotent and",
        "-- respectful of the Administrator, as the Relay Word seed: a key an Administrator has edited is left alone.",
        "IF OBJECT_ID(N'[config].[AddDefinition]') IS NULL RETURN;   -- bootstrap (tables-only) publish",
        "GO",
        "DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001', @approver UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';",
        "DECLARE @e UNIQUEIDENTIFIER, @v UNIQUEIDENTIFIER, @no INT, @payload NVARCHAR(MAX) = " + q(payload) + ";",
        "DECLARE @note NVARCHAR(200) = " + q(note) + ";",
        "SELECT @e = EntityId FROM [config].[Definition] WHERE [DefinitionKind] = N'Program.ManualGuide' AND [DefinitionKey] = " + q(key) + " AND [IsDeleted] = 0;",
        "IF @e IS NULL",
        "    EXEC [config].[AddDefinition] @DefinitionKind = N'Program.ManualGuide', @DefinitionKey = " + q(key) + ", @Name = " + q(doc["name"]) + ", @Description = " + q(desc) + ", @ActorId = @author, @EntityId = @e OUTPUT;",
        "IF NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [ChangeNote] NOT LIKE N'seed %')      -- untouched by an Administrator",
        "   AND NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' AND [ChangeNote] = @note)",
        "BEGIN",
        "    EXEC [config].[AddDefinitionVersion] @DefinitionKey = " + q(key) + ", @DefinitionKind = N'Program.ManualGuide', @ChangeNote = @note, @PayloadText = @payload, @ActorId = @author, @VersionRowId = @v OUTPUT, @VersionNumber = @no OUTPUT;",
        "    EXEC [config].[ApproveDefinitionVersion] @VersionRowId = @v, @ActorId = @approver;",
        "END",
        "GO",
    ]
    return NL.join(L) + NL


def md(doc, script):
    L = ["# " + doc["name"] + " - how each setting is set, in the manual's words", "",
         "Generated by `tools/manual_guide.py` from `" + script + "` (#235). Source: **" + doc["source"] + "**.",
         "Every quote is verbatim from the page image; the printed page is the manual's cite, the PDF page is where the link opens.",
         "Procedure and rules: `docs/runbook/MANUAL-GUIDE.md`.", ""]
    for code, quotes in doc["settings"].items():
        L += ["## " + code, ""]
        if not quotes:
            L += ["*(the manual gives no guidance for this setting)*", ""]
        for x in quotes:
            L += ["> " + x["quote"].replace("\n", "  \n> "), ">", "> — p. " + x["page"] + " (PDF page " + str(x["pdfPage"]) + "; " + x["checked"] + ")", ""]
    return NL.join(L) + NL


def main(path):
    doc = json.load(io.open(path, encoding="utf-8"))
    problems = check(doc)
    if problems:
        print("refused:\n  " + "\n  ".join(problems)); sys.exit(1)
    doc["settings"] = {c: v for c, v in doc["settings"].items() if v}   # a setting with no quote shows no floatover
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    model = re.sub(r"[^A-Za-z0-9]", "", doc["model"]).upper()
    rel = os.path.relpath(path, root).replace("\\", "/")
    a = os.path.join(root, "docs", "schema", "ddl", "PostDeploy", "Seed_config_ManualGuide_" + model + ".sql")
    b = os.path.splitext(path)[0] + ".md"
    io.open(a, "w", encoding="utf-8", newline="").write(sql(doc, rel))
    io.open(b, "w", encoding="utf-8", newline="").write(md(doc, rel))
    print(str(len(doc["settings"])) + " settings, " + str(sum(len(v) for v in doc["settings"].values())) + " quotes ->")
    print("  " + a); print("  " + b)


if __name__ == "__main__":
    main(sys.argv[1])
