"""
seed_screens.py — the screen definitions (#165) as a PostDeploy seed.

The documents under docs/design/examples/screens/*.screen.json are the source; this writes
docs/schema/ddl/PostDeploy/Seed_config_Screens.sql, which adds each as a Program.Screen definition with an Effective
version. Idempotent and respectful of the Administrator: a key whose current Effective version carries the same payload
hash is left alone; a key an Administrator has edited (any version whose ChangeNote does not start with 'seed') is left
alone; otherwise a new version is added and approved. Run after editing a screen document, commit both files.

Usage: python tools/seed_screens.py
"""
import glob, hashlib, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "design", "examples", "screens")
OUT = os.path.join(ROOT, "docs", "schema", "ddl", "PostDeploy", "Seed_config_Screens.sql")
SCHEMA = os.path.join(ROOT, "docs", "design", "screen.schema.json")


def check(doc, path):
    """The few structural rules the API's SchemaCheck would refuse first: keep the seed and the editor in agreement."""
    for k in ("g", "kind", "key", "name", "screenKind", "params"):
        if k not in doc:
            raise SystemExit(f"{path}: missing '{k}'")
    if doc["kind"] != "screen" or doc["g"] != 1:
        raise SystemExit(f"{path}: kind must be 'screen', g must be 1")


def sql_str(s):
    return "N'" + s.replace("'", "''") + "'"


def main():
    parts = ["""-- GENERATED by tools/seed_screens.py from docs/design/examples/screens/*.screen.json — do not edit by hand.
-- #165: the screen definitions (Program.Screen). Each is added with an Effective version unless the Administrator has
-- edited it (a version whose ChangeNote does not start with 'seed') or the same payload is already Effective.
IF OBJECT_ID(N'[config].[AddDefinition]') IS NULL RETURN;   -- bootstrap (tables-only) publish
GO
"""]
    files = sorted(glob.glob(os.path.join(SRC, "*.screen.json")))
    if not files:
        raise SystemExit("no screen documents found")
    for f in files:
        doc = json.load(open(f, encoding="utf-8"))
        check(doc, f)
        payload = json.dumps(doc, separators=(",", ":"), ensure_ascii=False)
        h = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]
        key, name, desc = doc["key"], doc["name"], doc.get("description") or ""
        parts.append(f"""-- {os.path.basename(f)}
DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001', @approver UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';
DECLARE @e UNIQUEIDENTIFIER, @v UNIQUEIDENTIFIER, @no INT, @payload NVARCHAR(MAX) = {sql_str(payload)};
DECLARE @note NVARCHAR(200) = N'seed {h}';
SELECT @e = EntityId FROM [config].[Definition] WHERE [DefinitionKind] = N'Program.Screen' AND [DefinitionKey] = {sql_str(key)} AND [IsDeleted] = 0;
IF @e IS NULL
    EXEC [config].[AddDefinition] @DefinitionKind = N'Program.Screen', @DefinitionKey = {sql_str(key)}, @Name = {sql_str(name)}, @Description = {sql_str(desc)}, @ActorId = @author, @EntityId = @e OUTPUT;
IF NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [ChangeNote] NOT LIKE N'seed %')      -- untouched by an Administrator
   AND NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' AND [ChangeNote] = @note)
BEGIN
    EXEC [config].[AddDefinitionVersion] @DefinitionKey = {sql_str(key)}, @DefinitionKind = N'Program.Screen', @ChangeNote = @note, @PayloadText = @payload, @ActorId = @author, @VersionRowId = @v OUTPUT, @VersionNumber = @no OUTPUT;
    EXEC [config].[ApproveDefinitionVersion] @VersionRowId = @v, @ActorId = @approver;
END
GO
""")
    with open(OUT, "w", encoding="utf-8", newline="\n") as o:
        o.write("".join(parts))
    print(f"{len(files)} screen(s) -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
