"""template_bundle_sel221f.py - the SEL-221F device template, SEL221F_Template (#184), as data.

The owner, 2026-09-18: a TEMPLATE is one per device type, one level below a scheme, named "SEL221F_Template"; it bundles
everything true of the device type itself - its settings list (tools/template_sel221f.py), what it can do
(tools/capability_sel221f.py) and the compliance that can attach to it - so that placing a relay of this model brings
all of it. This tool gives the bundle its name and its home: a CharacteristicSchema.AssetTemplate definition (a seeded
kind that had never held an instance) bound to the model through config.DefinitionAppliesTo, carrying the model-level
facts nothing else holds. The settings and the capabilities stay where they are and are found through the same model.

Source for every row: SEL-221F-2/-3/-4, SEL-121F-2/-3 Instruction Manual, date code 981207
(Z:\\Archive-WorkingData-Cloud\\Work\\DATA\\Manuals\\SEL\\221F-2-3-4_IM_19981207.pdf), page-cited.

Writes docs/schema/ddl/PostDeploy/Seed_config_AssetTemplate_SEL221F.sql.
"""
import io
import os

NL = chr(13) + chr(10)
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY = "SEL221F_Template"
MODEL_CODES = ["SEL-221F Z1-3=.125-64 OHMS", "SEL-221F"]   # the same two codes the settings template and the capabilities bind to
NOTE = "seed (#184): the SEL-221F device template, from IM 981207"

# (key, name, datatype, unit, group, order, description-with-cite)
ROWS = [
    ("ManualReference", "Instruction manual", "Text", None, "Identity", 1,
     "SEL-221F-2, -3, -4 / SEL-121F-2, -3 Instruction Manual, date code 981207, Schweitzer Engineering Laboratories, "
     "December 7, 1998 (title page). Held at Z:\\Archive-WorkingData-Cloud\\Work\\DATA\\Manuals\\SEL\\221F-2-3-4_IM_19981207.pdf."),
    ("Variations", "Model variations covered", "Text", None, "Identity", 2,
     "SEL-221F-2, -3, -4 and SEL-121F-2, -3: 'identical protection features but use different hardware designs' (1-1). "
     "'Firmware changes to the logic controlling reclosing, Relay Word bits, and command access level differentiate "
     "SEL-221F relay model variations' (1-1)."),
    ("BreakerFailureVariants", "Variations with breaker failure", "Text", None, "Identity", 3,
     "SEL-221F-3/121F-3 and SEL-221F-4 only: 'includes a breaker failure function ... the AITP setting is replaced with "
     "BFIN1 and the AITD setting is replaced with BFTD' (1-2). The -2 does not have it. The platform's model rows carry no "
     "variation suffix, so a person must know which relay is in front of them."),
    ("Application", "Intended application", "Text", None, "Identity", 4,
     "'designed to protect transmission, subtransmission, and distribution lines for all fault types' (1-1). Supports "
     "POTT, PUTT, DUTT and DTT communication-aided schemes (1-4)."),
    ("RatedInputs", "Rated inputs", "Text", None, "Inputs", 5,
     "115 V nominal phase-to-phase, three-phase four-wire; 5 A per phase nominal, 15 A continuous, 500 A one-second "
     "thermal (2-1)."),
    ("SettingsTemplate", "Settings list", "Text", None, "Bundle", 6,
     "The settings template SETTINGS_TEXT_SEL_221F (56 settings in the manual's twelve Specifications groups, #168), "
     "bound to this model through its firmware row; none hidden (#183)."),
    ("Capabilities", "What it can do", "Text", None, "Bundle", 7,
     "The fifteen elements of scheme.FunctionCapability for this model (#181, #182): ten with a C37.2 device number and "
     "five named in the manual's own words."),
    ("Prc023Inputs", "PRC-023 loadability inputs", "Text", None, "Compliance", 8,
     "The loadability calculation (#171) reads Z3%, R1, X1, MTA and 50H from this relay's settings, the terminal voltage "
     "of the protected line, and its four-hour, fifteen-minute and practical-limitation ratings. Manual 2-32 / 5-14: "
     "reach along the line angle; mho diameter = reach / cos(line angle - MTA)."),
    ("NpccDirectory4", "NPCC Directory 4 awareness", "Text", None, "Compliance", 9,
     "When the bus this relay protects is declared BPS by the NPCC A-10 study, Directory 4's protection criteria "
     "(R5.1 - R5.20, R6.1 - R6.3) attach as reading material; they govern the physical design of the protection, not "
     "its settings (the owner, 2026-09-18)."),
]


def q(s):
    return "N'" + s.replace("'", "''") + "'" if s is not None else "NULL"


def sql():
    L = [
        "-- GENERATED by tools/template_bundle_sel221f.py - do not edit; edit the data there and regenerate.",
        "-- #184 (2026-09-18): the SEL-221F device template, " + KEY + ". The owner: a template is one per device type, one",
        "-- level below a scheme; it bundles the settings list, what the relay can do, and the compliance that can attach.",
        "-- CharacteristicSchema.AssetTemplate is the seeded kind that had never held an instance; this is its first.",
        "-- Bound to the model through config.DefinitionAppliesTo (dimension Model), one row per model code, so a screen",
        "-- opened from a relay of either code finds it. Idempotent: adds the version only when no Effective version",
        "-- carries this change note; binds a model only when not already bound.",
        "IF OBJECT_ID(N'[config].[AddDefinition]') IS NULL RETURN;   -- bootstrap (tables-only) publish",
        "GO",
        "DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001', @approver UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';",
        "DECLARE @sel UNIQUEIDENTIFIER = (SELECT TOP (1) [ManufacturerId] FROM [ref].[vManufacturer] WHERE [ShortCode] = N'SEL');",
        "IF @sel IS NULL RETURN;",
        "DECLARE @e UNIQUEIDENTIFIER, @v UNIQUEIDENTIFIER, @no INT, @model UNIQUEIDENTIFIER, @code NVARCHAR(200);",
        "SELECT @e = [EntityId] FROM [config].[Definition] WHERE [DefinitionKind] = N'CharacteristicSchema.AssetTemplate' AND [DefinitionKey] = " + q(KEY) + " AND [IsDeleted] = 0;",
        "IF @e IS NULL",
        "    EXEC [config].[AddDefinition] @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @DefinitionKey = " + q(KEY) + ",",
        "         @Name = N'SEL-221F device template', @Description = N'Everything true of the SEL-221F as a device type: its manual, its variations, its settings list, what it can do, and the compliance that can attach to it (#184). One template per device type, one level below a scheme.',",
        "         @ActorId = @author, @EntityId = @e OUTPUT;",
        "IF NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' AND [ChangeNote] = " + q(NOTE) + ")",
        "BEGIN",
        "    EXEC [config].[AddDefinitionVersion] @DefinitionKey = " + q(KEY) + ", @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @ChangeNote = " + q(NOTE) + ", @ActorId = @author, @VersionRowId = @v OUTPUT, @VersionNumber = @no OUTPUT;",
    ]
    for (key, name, dt, unit, group, order, desc) in ROWS:
        L.append("    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = " + q(key)
                 + ", @Name = " + q(name) + ", @DataType = " + q(dt) + ", @UnitCode = " + q(unit) + ", @DisplayGroup = " + q(group)
                 + ", @DisplayOrder = " + str(order) + ", @Description = " + q(desc) + ", @ActorId = @author;")
    L += [
        "    EXEC [config].[ApproveDefinitionVersion] @VersionRowId = @v, @ActorId = @approver;",
        "END",
        "SELECT TOP (1) @v = [RowId] FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' ORDER BY [VersionNumber] DESC;",
        "-- bind the template to each model code it covers",
        "DECLARE mc CURSOR LOCAL FAST_FORWARD FOR SELECT [Code] FROM (VALUES " + ", ".join("(" + q(c) + ")" for c in MODEL_CODES) + ") x ([Code]);",
        "OPEN mc; FETCH NEXT FROM mc INTO @code;",
        "WHILE @@FETCH_STATUS = 0",
        "BEGIN",
        "    SELECT @model = [ModelId] FROM [ref].[vModel] WHERE [ManufacturerId] = @sel AND [ModelCode] = @code;",
        "    IF @model IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [config].[vDefinitionAppliesTo] WHERE [DefinitionVersionRowId] = @v AND [DimensionCode] = N'Model' AND [ValueEntityId] = @model)",
        "        EXEC [config].[DefinitionAppliesTo_Add] @DefinitionVersionRowId = @v, @DimensionCode = N'Model', @ValueEntityId = @model, @ActorId = @author;",
        "    FETCH NEXT FROM mc INTO @code;",
        "END",
        "CLOSE mc; DEALLOCATE mc;",
        "GO",
    ]
    return NL.join(L) + NL


def main():
    out = os.path.join(HERE, "docs", "schema", "ddl", "PostDeploy", "Seed_config_AssetTemplate_SEL221F.sql")
    io.open(out, "w", encoding="utf-8", newline="").write(sql())
    print(str(len(ROWS)) + " template facts -> " + out)


if __name__ == "__main__":
    main()
