"""template_line.py - the transmission line's template, LINE_Template (#219), as data.

The owner, 2026-09-21: the line impedance "must move onto the line asset" - until now R1, X1, R0, X0 and the line length
existed only as relay settings (the SEL-221F's Distance elements group), so every relay on a line re-typed the line. The
line asset carries them once, as characteristics of the asset type's default template (ref.AssetType.DefaultTemplateDefinitionEntityId,
the mechanism asset.SetAssetCharacteristic already resolves, #216), and the rationale reads them from there (line.R1 ...).
Nothing here is a value: values are recorded per line, under a work request, on the primary-asset screen.

Writes docs/schema/ddl/PostDeploy/Seed_config_AssetTemplate_Line.sql and docs/design/examples/templates/line.template.md.
"""
import io
import os

NL = chr(13) + chr(10)
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY = "LINE_Template"
NOTE = "seed v1 (#219): the line's positive- and zero-sequence impedance, length and charging"

# (key, name, datatype, unit, base, group, order, description)
ROWS = [
    ("R1", "Positive-sequence resistance", "Decimal", "Ω", "Primary", "Impedance", 1,
     "Positive-sequence line resistance, ohms primary, end to end. The legacy rationales write it as the real part of Z1 (A4811.docx: 'Z1=1.685+j6.7524')."),
    ("X1", "Positive-sequence reactance", "Decimal", "Ω", "Primary", "Impedance", 2,
     "Positive-sequence line reactance, ohms primary, end to end (the imaginary part of Z1)."),
    ("R0", "Zero-sequence resistance", "Decimal", "Ω", "Primary", "Impedance", 3,
     "Zero-sequence line resistance, ohms primary, end to end (the real part of Z0)."),
    ("X0", "Zero-sequence reactance", "Decimal", "Ω", "Primary", "Impedance", 4,
     "Zero-sequence line reactance, ohms primary, end to end (the imaginary part of Z0)."),
    ("LengthMiles", "Length", "Decimal", "mi", None, "Impedance", 5,
     "Line length in miles, terminal to terminal (the legacy rationales: 'LL=8.49 miles'; the SEL-221F's LL setting is the fault locator's line length)."),
    ("ChargingMvaPerMile", "Charging (MVA per mile)", "Decimal", None, None, "Impedance", 6,
     "Line charging in MVA per mile, used for the supervisory overcurrent pickups (A4811.docx: 'ICharge=0.128 MVA/mile*8.49 miles*4.18 amps/MVA'). Optional."),
]


def q(s):
    return "NULL" if s is None else "N'" + s.replace("'", "''") + "'"


def sql():
    L = [
        "-- GENERATED by tools/template_line.py — do not edit; change the table there and regenerate.",
        "-- #219 (2026-09-21): the transmission line's template, " + KEY + " — the line's impedances, length and charging as characteristics of",
        "-- the line asset (the owner: the line impedance 'must move onto the line asset'), the default template of the asset type Line, so",
        "-- asset.SetAssetCharacteristic records them per line and the rationale reads them as line.R1, line.X1, line.R0, line.X0, line.LengthMiles.",
        "-- Idempotent: adds the version only when no Effective version carries this change note; sets the type's default only when unset or different.",
        "IF OBJECT_ID(N'[config].[AddDefinition]') IS NULL RETURN;   -- bootstrap (tables-only) publish",
        "GO",
        "DECLARE @author UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001', @approver UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';",
        "DECLARE @e UNIQUEIDENTIFIER, @v UNIQUEIDENTIFIER, @no INT;",
        "SELECT @e = [EntityId] FROM [config].[Definition] WHERE [DefinitionKind] = N'CharacteristicSchema.AssetTemplate' AND [DefinitionKey] = " + q(KEY) + " AND [IsDeleted] = 0;",
        "IF @e IS NULL",
        "    EXEC [config].[AddDefinition] @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @DefinitionKey = " + q(KEY) + ",",
        "         @Name = N'Transmission line template', @Description = N'What the platform holds of a transmission line as an asset: its positive- and zero-sequence impedance, its length and its charging (#219) — recorded once on the line, read by every relay rationale on it.',",
        "         @ActorId = @author, @EntityId = @e OUTPUT;",
        "IF NOT EXISTS (SELECT 1 FROM [config].[vDefinitionVersion] WHERE [DefinitionEntityId] = @e AND [Status] = N'Effective' AND [ChangeNote] = " + q(NOTE) + ")",
        "BEGIN",
        "    EXEC [config].[AddDefinitionVersion] @DefinitionKey = " + q(KEY) + ", @DefinitionKind = N'CharacteristicSchema.AssetTemplate', @ChangeNote = " + q(NOTE) + ", @ActorId = @author, @VersionRowId = @v OUTPUT, @VersionNumber = @no OUTPUT;",
    ]
    for (key, name, dt, unit, base, group, order, desc) in ROWS:
        L.append("    EXEC [config].[CharacteristicDefinition_Add] @DefinitionVersionRowId = @v, @CharacteristicKey = " + q(key) + ", @Name = " + q(name)
                 + ", @DataType = " + q(dt) + ", @UnitCode = " + q(unit) + ", @Base = " + q(base) + ", @DisplayGroup = " + q(group)
                 + ", @DisplayOrder = " + str(order) + ", @Description = " + q(desc) + ", @ActorId = @author;")
    L += [
        "    EXEC [config].[ApproveDefinitionVersion] @VersionRowId = @v, @ActorId = @approver;",
        "END",
        "UPDATE [ref].[AssetType] SET [DefaultTemplateDefinitionEntityId] = @e WHERE [AssetTypeCode] = N'Line' AND ([DefaultTemplateDefinitionEntityId] IS NULL OR [DefaultTemplateDefinitionEntityId] <> @e);",
        "GO",
    ]
    return NL.join(L) + NL


def md():
    L = [
        "# Transmission line template — `" + KEY + "`",
        "",
        "Generated by `tools/template_line.py` (#219). The owner, 2026-09-21: the line impedance moves onto the line asset. These are the",
        "characteristics of every asset of type `Line` (the type's default template); a value is recorded per line through",
        "`asset.SetAssetCharacteristic` on the primary-asset screen, under a work request, and the relay rationale reads them as",
        "`line.R1`, `line.X1`, `line.R0`, `line.X0`, `line.LengthMiles`, `line.ChargingMvaPerMile`.",
        "",
        "| # | Key | Name | Type | Unit | Base | What it is |",
        "|---|---|---|---|---|---|---|",
    ]
    for (key, name, dt, unit, base, group, order, desc) in ROWS:
        L.append("| " + str(order) + " | `" + key + "` | " + name + " | " + dt + " | " + (unit or "") + " | " + (base or "") + " | " + desc + " |")
    L += ["", "The distance relay's own copies (the SEL-221F's R1, X1, R0, X0, LL settings) are written from these by the rationale; a line with no",
          "impedance recorded yet is said so on the record's Rationale tab.", ""]
    return NL.join(L) + NL


def main():
    out = os.path.join(HERE, "docs", "schema", "ddl", "PostDeploy", "Seed_config_AssetTemplate_Line.sql")
    io.open(out, "w", encoding="utf-8", newline="").write(sql())
    doc = os.path.join(HERE, "docs", "design", "examples", "templates", "line.template.md")
    io.open(doc, "w", encoding="utf-8", newline="").write(md())
    print(str(len(ROWS)) + " line characteristics -> " + out + " and " + doc)


if __name__ == "__main__":
    main()
