"""
view_items.py — what a person may show or hide on a screen, and what each role starts with (#226).

The owner, 2026-09-22: "I would not, purposely, block access to those screens from anyone … they should be default
hidden or shown depending upon the group that they are in, and more precisely, possibly by the individual … the choice
should be entirely personal as far as views … both engineering and technical staff need to be the same with the
compliance and history available. Note that the ability to edit at all levels need to be built in as well."

This writes docs/schema/ddl/PostDeploy/Seed_config_ViewItems.sql: one row per part of a screen a person may hide, and
the starting answer per role. It is a starting shape only — an Administrator edits the role rows on the "What people
see" screen, and every person overrides them for themselves, which nothing here ever touches.

Hiding is a preference, never a permission. An item marked always is one nobody hides, because it is the screen's
reason for being; everything else is one click away from the screen it sits on.

Usage: python tools/view_items.py      (then deploy; commit both files)
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "schema", "ddl", "PostDeploy", "Seed_config_ViewItems.sql")

# (ItemKey, Name, Description, DisplayOrder, ShownByDefault, IsAlways) — the order is the order they appear
SCREENS = {
    "SETTINGS_RECORD": [
        ("settings",   "Settings",          "The settings of this record, in the manual's own groups.", 10, 1, 1),
        ("rationale",  "Rationale",         "Why each element is set the way it is, section by section.", 20, 1, 0),
        ("analog",     "Analog inputs",     "The CT and VT inputs the relay works from, and their ratios.", 30, 1, 0),
        ("jumpers",    "Jumper settings",   "The hardware straps and port speeds set on the relay itself.", 40, 1, 0),
        ("record",     "Record",            "The record's own detail: its number, dates, tracks and who verified it.", 50, 0, 0),
        ("history",    "History",           "Every change request this relay has been through.", 60, 1, 0),
        ("compliance", "Compliance",        "The standards that apply to this relay and where each one stands.", 70, 1, 0),
        ("notes",      "Notes",             "The notes filed with this record.", 80, 1, 0),
        ("text",       "Settings file",     "The settings file as it was filed, in each form it takes.", 90, 0, 0),
        ("files",      "Files and records", "The documents behind the record, and the files they came in.", 100, 0, 0),
        ("manual",     "Manual",            "The relay model's instruction manual.", 110, 1, 0),
    ],
}

# What each role starts people with. Only a difference from the screen's own default needs a row, but every role that
# staff actually hold is written out in full, so the "What people see" screen shows a complete picture rather than gaps.
# The owner: engineering and technical staff are the same, with compliance and history available.
DAILY = ["settings", "rationale", "analog", "jumpers", "history", "compliance", "notes", "manual"]
EVERYTHING = [k for k, *_ in SCREENS["SETTINGS_RECORD"]]
ROLE_DEFAULTS = {
    "SETTINGS_RECORD": {
        "PCEngineer": DAILY,
        "PCTechnician": DAILY,
        "PCApprover": DAILY,
        "Administrator": EVERYTHING,
        "ReadOnly": EVERYTHING,
    },
}


def n(s):
    return "N'" + s.replace("'", "''") + "'"


def main():
    out = ["""-- GENERATED by tools/view_items.py — do not edit by hand.
-- #226: what a person may show or hide on a screen, and the shape each role starts with. Idempotent, and it never
-- touches a person's own choices (config.UserViewItem) — those are theirs. A role row an Administrator has changed
-- since the last deploy is left alone: the seed writes a role's answer only where none stands.
-- Each batch guards itself: RETURN ends the batch it is in, not the script.
IF OBJECT_ID(N'[config].[ViewItem_Upsert]') IS NULL RETURN;   -- bootstrap (tables-only) publish
DECLARE @a UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';
"""]
    for screen, items in SCREENS.items():
        out.append(f"-- {screen}")
        for key, name, desc, order, shown, always in items:
            out.append(
                f"EXEC [config].[ViewItem_Upsert] @ScreenKey = {n(screen)}, @ItemKey = {n(key)}, @Name = {n(name)}, "
                f"@Description = {n(desc)}, @ItemKind = N'Tab', @DisplayOrder = {order}, @ShownByDefault = {shown}, "
                f"@IsAlways = {always}, @ActorId = @a;")
        out.append("")
    out.append("GO")
    # every batch guards itself: RETURN ends the batch it is in, not the script (the 2026-09-22 deploy failure)
    out.append("IF OBJECT_ID(N'[config].[RoleViewItem_Upsert]') IS NULL RETURN;")
    out.append("DECLARE @a UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';")
    for screen, roles in ROLE_DEFAULTS.items():
        for role, shown_keys in roles.items():
            out.append(f"-- {screen}, {role}")
            for key, *_ in SCREENS[screen]:
                is_shown = 1 if key in shown_keys else 0
                out.append(
                    f"IF EXISTS (SELECT 1 FROM [security].[Role] WHERE [RoleCode] = {n(role)}) "
                    f"AND NOT EXISTS (SELECT 1 FROM [config].[RoleViewItem] WHERE [RoleCode] = {n(role)} "
                    f"AND [ScreenKey] = {n(screen)} AND [ItemKey] = {n(key)}) "
                    f"EXEC [config].[RoleViewItem_Upsert] @RoleCode = {n(role)}, @ScreenKey = {n(screen)}, "
                    f"@ItemKey = {n(key)}, @IsShown = {is_shown}, @ActorId = @a;")
            out.append("")
    out.append("GO")
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(out) + "\n")
    items = sum(len(v) for v in SCREENS.values())
    rows = sum(len(SCREENS[s]) * len(r) for s, r in ROLE_DEFAULTS.items())
    print(f"{os.path.relpath(OUT, ROOT)}: {items} screen item(s), {rows} role default(s)")


if __name__ == "__main__":
    main()
