"""
Build → publish → generate → build → publish → smoke, against PnCPlatform_V2_DEV by default (never the predecessor's PnCPlatform_DEV).

    python tools/deploy.py [--server 10.10.70.25] [--database PnCPlatform_V2_DEV]
                           [--fresh]        drop and recreate the database first
                           [--no-generate]  skip the generator pass
                           [--no-smoke]     skip tools/smoke.py

Password from dev.local (PNC_DEV_PWD=) or the environment. Needs the .NET SDK and the
microsoft.sqlpackage dotnet tool.
"""
import argparse, os, subprocess, sys, shutil
import pyodbc

HERE = os.path.dirname(os.path.abspath(__file__))
DDL = os.path.abspath(os.path.join(HERE, ".."))
ROOT = os.path.abspath(os.path.join(DDL, "..", "..", ".."))
DOTNET = shutil.which("dotnet") or r"C:\Program Files\dotnet\dotnet.exe"
SQLPACKAGE = shutil.which("sqlpackage") or os.path.expanduser(r"~\.dotnet\tools\sqlpackage.exe")
DACPAC = os.path.join(DDL, "bin", "Debug", "PnCPlatform.dacpac")


def password():
    if os.environ.get("PNC_DEV_PWD"):
        return os.environ["PNC_DEV_PWD"]
    p = os.path.join(ROOT, "dev.local")
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            if line.startswith("PNC_DEV_PWD="):
                return line.split("=", 1)[1].strip()
    sys.exit("No password: set PNC_DEV_PWD or put PNC_DEV_PWD=... in dev.local")


def run(cmd, **kw):
    print("+", " ".join(c if "Password" not in c else "/TargetPassword:***" for c in cmd))
    env = dict(os.environ, DOTNET_ROLL_FORWARD="Major")   # sqlpackage 170.4 targets an older runtime than the SDK ships
    r = subprocess.run(cmd, cwd=DDL, text=True, capture_output=True, env=env, **kw)
    if r.returncode != 0:
        print(r.stdout[-6000:]); print(r.stderr[-3000:])
        sys.exit(f"failed: {cmd[0]} ({r.returncode})")
    return r.stdout


def build(tables_only=False):
    cmd = [DOTNET, "build", "PnCPlatform.sqlproj", "-nologo", "-v", "q"]
    if tables_only:
        cmd.append("-p:TablesOnly=true")
    out = run(cmd)
    print("  build" + (" (tables only)" if tables_only else "") + ":", [l for l in out.splitlines() if "Warning(s)" in l or "Error(s)" in l])


def has_generated():
    header = "-- GENERATED by tools/generate.py"
    for root, _, names in os.walk(DDL):
        if any(x in root for x in ("bin", "obj", "tools")):
            continue
        for n in names:
            if n.endswith(".sql"):
                try:
                    if open(os.path.join(root, n), encoding="utf-8").readline().startswith(header):
                        return True
                except OSError:
                    pass
    return False


def publish(server, database, pwd):
    run([SQLPACKAGE, "/Action:Publish", f"/SourceFile:{DACPAC}", "/Profile:PnCPlatform_DEV.publish.xml",
         f"/TargetServerName:{server}", f"/TargetDatabaseName:{database}", "/TargetUser:dev_pnc", f"/TargetPassword:{pwd}",
         # explicit, not only in the profile: sqlpackage 170.5 ignored the profile's DoNotDropObjectTypes and dropped the
         # environment's database user (VGSOT\svc-pncapi on PnCPlatform_QA, 2026-09-07). Principals and grants are
         # environment configuration (Roles.sql) and must survive every publish.
         "/p:DropObjectsNotInSource=True", "/p:DoNotDropObjectTypes=Users;Logins;RoleMembership;Permissions",
         "/TargetTrustServerCertificate:True", "/p:BlockOnPossibleDataLoss=False"])
    print("  published to", database)


def fresh(server, database, pwd):
    c = pyodbc.connect(f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE=master;UID=dev_pnc;PWD={pwd};TrustServerCertificate=yes", autocommit=True, timeout=15)
    cur = c.cursor()
    if cur.execute("SELECT COUNT(*) FROM sys.databases WHERE name = ?", database).fetchone()[0]:
        cur.execute(f"ALTER DATABASE [{database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE")
        cur.execute(f"DROP DATABASE [{database}]")
    cur.execute(f"CREATE DATABASE [{database}]")
    print("  fresh database", database)


def ensure_filestream_directory(server, database, pwd):
    """FILESTREAM DIRECTORY_NAME must be unique per instance, so it is the database name. The
    sqlproj deliberately leaves it out of the model (see the comment there); set it here before
    the publish, which needs it for NON_TRANSACTED_ACCESS = FULL and the FileTable."""
    c = pyodbc.connect(f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE=master;UID=dev_pnc;PWD={pwd};TrustServerCertificate=yes", autocommit=True, timeout=15)
    cur = c.cursor()
    if not cur.execute("SELECT COUNT(*) FROM sys.databases WHERE name = ?", database).fetchone()[0]:
        return
    row = cur.execute("SELECT directory_name FROM sys.database_filestream_options WHERE database_id = DB_ID(?)", database).fetchone()
    if row and row[0]:
        return
    cur.execute(f"ALTER DATABASE [{database}] SET FILESTREAM (NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'{database}')")
    print("  FILESTREAM directory name set to", database)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--server", default="10.10.70.25")
    ap.add_argument("--database", default="PnCPlatform_V2_DEV")
    ap.add_argument("--allow-any-database", action="store_true", help="publish to a database whose name does not start with PnCPlatform_V2_ (never the predecessor's PnCPlatform_DEV / _QA)")
    ap.add_argument("--fresh", action="store_true")
    ap.add_argument("--no-generate", action="store_true")
    ap.add_argument("--no-smoke", action="store_true")
    ap.add_argument("--no-record", action="store_true", help="do not record the release/deployment (platform.Release / Deployment)")
    ap.add_argument("--package", default=None, help="dist/<version> from tools/package_release.py: its release.json package hash is recorded on the release row")
    ap.add_argument("--bootstrap", action="store_true", help="first pass builds tables only (automatic when no generated files exist)")
    a = ap.parse_args()
    # 2026-09-12 incident: this script defaulted to PnCPlatform_DEV — the predecessor's database, which V2 never
    # touches (CLAUDE.md) — and one unqualified run published the V2 schema over it. V2 targets are named for it.
    if not a.database.startswith("PnCPlatform_V2_") and not a.allow_any_database:
        sys.exit(f"refusing to publish to {a.database}: V2 deploys go to PnCPlatform_V2_*; pass --allow-any-database only for a database that is yours")
    pwd = password()
    if a.fresh:
        fresh(a.server, a.database, pwd)
    bootstrap = a.bootstrap or not has_generated()
    ensure_filestream_directory(a.server, a.database, pwd)
    if a.package:
        # a release deploy publishes the packaged DACPAC as built (its bytes are what the release row hashes; a
        # rebuild here would produce different bytes) — PLATFORM-ARCHITECTURE §9.2 deployment order
        src = os.path.join(a.package, "PnCPlatform.dacpac")
        if not os.path.exists(src):
            sys.exit(f"no PnCPlatform.dacpac in {a.package}")
        os.makedirs(os.path.dirname(DACPAC), exist_ok=True)
        shutil.copyfile(src, DACPAC)
        print(f"  publishing the packaged DACPAC from {a.package}")
        publish(a.server, a.database, pwd)
        run([sys.executable, os.path.join(HERE, "check_generated.py"), "--server", a.server, "--database", a.database])
        print("  generated files are current")
        a.no_generate = True
    else:
        build(tables_only=bootstrap)
        publish(a.server, a.database, pwd)
    if not a.no_generate:
        print(run([sys.executable, os.path.join(HERE, "generate.py"), "--server", a.server, "--database", a.database]).strip())
        build()
        publish(a.server, a.database, pwd)
        if bootstrap:
            print("  bootstrap pass: fEntityExists is a placeholder until the seeds are in; run deploy.py again to regenerate and check")
        else:
            run([sys.executable, os.path.join(HERE, "check_generated.py"), "--server", a.server, "--database", a.database])
            print("  generated files are current")
    if not a.no_smoke:
        r = subprocess.run([sys.executable, os.path.join(HERE, "smoke.py"), "--server", a.server, "--database", a.database], cwd=DDL, text=True)
        if r.returncode != 0:
            sys.exit("smoke failed")
    if not a.no_record and not bootstrap:
        run([sys.executable, os.path.join(HERE, "record_release.py"), "--server", a.server, "--database", a.database, "--outcome", "Succeeded"] + ([] if a.no_smoke else ["--notes", "deploy.py with smoke"]) + ([] if not a.package else ["--package-hash", os.path.abspath(os.path.join(a.package, "release.json"))]))
    print("OK")


if __name__ == "__main__":
    main()
