"""
Generator for the temporal-class views and base write procedures (SCHEMA-DESIGN decision 69,
§0.5; CONVENTIONS.md "Generated objects").

Reads the deployed catalog (sys.tables, sys.columns, sys.foreign_keys, the PnC.TemporalClass
extended property, ref.SubjectKind rows) and emits one .sql file per generated object into the
project. Files carry a GENERATED header; tools/check_generated.py fails if any differ from a
fresh generation.

Usage:
    python tools/generate.py [--server 10.10.70.25] [--database PnCPlatform_V2_DEV] [--check]

--check writes nothing; exits 1 if any generated file would change (used by check_generated.py).
"""
import argparse, os, sys, re
from collections import defaultdict
import pyodbc

HERE = os.path.dirname(os.path.abspath(__file__))
DDL = os.path.abspath(os.path.join(HERE, ".."))
ROOT = os.path.abspath(os.path.join(DDL, "..", "..", ".."))
HEADER = "-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py\n"

BASE_COLS = {"RowSeq", "RowId", "EntityId", "ValidFrom", "ValidTo", "ValidFromQuality", "SysStart", "SysEnd",
             "CreatedBy", "CreatedAt", "ModifiedBy", "ModifiedAt", "IsDeleted", "DeletedBy", "DeletedAt", "MigrationRunId"}
REF_AUDIT_COLS = {"SysStart", "SysEnd", "CreatedBy", "CreatedAt", "ModifiedBy", "ModifiedAt", "IsActive", "MigrationRunId"}
SUBCLASS_COLS = {"SysStart", "SysEnd", "CreatedBy", "CreatedAt", "ModifiedBy", "ModifiedAt", "IsDeleted", "DeletedBy", "DeletedAt", "MigrationRunId"}
SYSTEM_ACTOR = "00000000-0000-0000-0000-000000000001"


def password():
    if os.environ.get("PNC_DEV_PWD"):
        return os.environ["PNC_DEV_PWD"]
    p = os.path.join(ROOT, "dev.local")
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            if line.startswith("PNC_DEV_PWD="):
                return line.split("=", 1)[1].strip()
    sys.exit("No password: set PNC_DEV_PWD or put PNC_DEV_PWD=... in dev.local")


def connect(server, database):
    return pyodbc.connect(
        f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};"
        f"UID=dev_pnc;PWD={password()};TrustServerCertificate=yes", autocommit=True, timeout=15)


# ----------------------------------------------------------------------------- catalog

class Column:
    def __init__(self, name, typ, nullable, identity, hidden, computed, is_pk, default=None):
        self.name, self.type, self.nullable, self.identity, self.hidden, self.computed, self.is_pk = \
            name, typ, nullable, identity, hidden, computed, is_pk
        self.default = default        # literal column default usable as a parameter default, else None


class Table:
    def __init__(self, schema, name, tclass):
        self.schema, self.name, self.tclass = schema, name, tclass
        self.columns = []
        self.registry = None          # (schema, table) the EntityId FK points to, if any
        self.pk = []

    @property
    def qn(self):
        return f"[{self.schema}].[{self.name}]"

    def col(self, n):
        return next((c for c in self.columns if c.name == n), None)

    @property
    def domain(self):
        base = REF_AUDIT_COLS if self.tclass == "Reference" else SUBCLASS_COLS if self.tclass == "Subclass" else BASE_COLS
        return [c for c in self.columns if c.name not in base and not c.hidden and not c.computed and not c.identity]

    @property
    def own_registry(self):
        return self.registry is not None and self.registry[1] == self.name + "Registry"


def render_type(row):
    t = row.type_name
    ml, prec, scale = row.max_length, row.precision, row.scale
    if t in ("nvarchar", "nchar"):
        return f"{t.upper()}({'MAX' if ml == -1 else ml // 2})"
    if t in ("varchar", "char", "varbinary", "binary"):
        return f"{t.upper()}({'MAX' if ml == -1 else ml})"
    if t in ("decimal", "numeric"):
        return f"{t.upper()}({prec},{scale})"
    if t in ("datetimeoffset", "datetime2", "time"):
        return f"{t.upper()}({scale})"
    if t == "sysname":
        return "SYSNAME"
    return t.upper()


def literal_default(defn):
    """((0)) → 0, (N'x') → N'x'; function defaults (NEWSEQUENTIALID(), SYSDATETIMEOFFSET()) → None."""
    if not defn:
        return None
    d = defn.strip()
    while d.startswith("(") and d.endswith(")"):
        d = d[1:-1].strip()
    if re.fullmatch(r"-?\d+(\.\d+)?", d) or re.fullmatch(r"N?'[^']*'", d):
        return d
    return None


def load(cur):
    tables = {}
    rows = cur.execute("""
        SELECT s.name, t.name, CONVERT(NVARCHAR(40), ep.value)
        FROM sys.tables t
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        JOIN sys.extended_properties ep ON ep.major_id = t.object_id AND ep.minor_id = 0 AND ep.name = N'PnC.TemporalClass'
        WHERE t.temporal_type <> 1
        ORDER BY s.name, t.name""").fetchall()
    for s, n, c in rows:
        tables[(s, n)] = Table(s, n, c)
    cols = cur.execute("""
        SELECT s.name, t.name, c.name, ty.name AS type_name, c.max_length, c.precision, c.scale, c.is_nullable,
               c.is_identity, c.is_hidden, c.is_computed, c.column_id, dc.definition AS default_def,
               CASE WHEN EXISTS (SELECT 1 FROM sys.index_columns ic JOIN sys.indexes i ON i.object_id = ic.object_id AND i.index_id = ic.index_id
                                 WHERE i.is_primary_key = 1 AND ic.object_id = c.object_id AND ic.column_id = c.column_id) THEN 1 ELSE 0 END AS is_pk
        FROM sys.columns c
        JOIN sys.tables t ON t.object_id = c.object_id
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        JOIN sys.types ty ON ty.user_type_id = c.user_type_id
        LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
        WHERE t.temporal_type <> 1
        ORDER BY s.name, t.name, c.column_id""").fetchall()
    for r in cols:
        t = tables.get((r[0], r[1]))
        if t is None:
            continue
        c = Column(r[2], render_type(r), bool(r.is_nullable), bool(r.is_identity), bool(r.is_hidden), bool(r.is_computed), bool(r.is_pk),
                   literal_default(r.default_def))
        t.columns.append(c)
        if c.is_pk:
            t.pk.append(c.name)
    fks = cur.execute("""
        SELECT s.name, t.name, c.name, rs.name, rt.name
        FROM sys.foreign_key_columns fkc
        JOIN sys.tables t ON t.object_id = fkc.parent_object_id
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        JOIN sys.columns c ON c.object_id = fkc.parent_object_id AND c.column_id = fkc.parent_column_id
        JOIN sys.tables rt ON rt.object_id = fkc.referenced_object_id
        JOIN sys.schemas rs ON rs.schema_id = rt.schema_id
        WHERE c.name = N'EntityId'""").fetchall()
    for s, n, _, rs, rn in fks:
        t = tables.get((s, n))
        if t is not None:
            t.registry = (rs, rn)
    kinds = cur.execute("SELECT SubjectKindCode, SchemaName, TableName, KeyColumnName FROM ref.SubjectKind WHERE IsActive = 1 ORDER BY SubjectKindCode").fetchall() \
        if cur.execute("SELECT OBJECT_ID(N'ref.SubjectKind')").fetchone()[0] else []
    existing = {(s, n) for (s, n) in cur.execute("SELECT s.name, t.name FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id").fetchall()}
    return tables, kinds, existing


# ----------------------------------------------------------------------------- emitters

def cols_list(cols, alias=None):
    p = f"{alias}." if alias else ""
    return ", ".join(f"{p}[{c.name}]" for c in cols)


def grant(qn):
    return f"GO\nGRANT SELECT ON {qn} TO [app_execute];\nGO\n"


def view_current(t):
    vis = [c for c in t.columns if not c.hidden]
    qn = f"[{t.schema}].[v{t.name}]"
    if t.tclass in ("ValidTime", "BiTemporal"):
        body = (f"CREATE VIEW {qn} AS\n"
                f"-- current: the latest row per entity valid now, not deleted (decision 69, 71)\n"
                f"SELECT {cols_list(vis)}\nFROM (\n"
                f"    SELECT {cols_list(vis)},\n"
                f"           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn\n"
                f"    FROM {t.qn}\n"
                f"    WHERE [IsDeleted] = 0\n"
                f"      AND [ValidFrom] <= SYSDATETIMEOFFSET()\n"
                f"      AND ([ValidTo] IS NULL OR [ValidTo] > SYSDATETIMEOFFSET())\n"
                f") x WHERE x._rn = 1;\n")
    elif t.tclass in ("Versioned", "Subclass"):
        body = f"CREATE VIEW {qn} AS\nSELECT {cols_list(vis)}\nFROM {t.qn}\nWHERE [IsDeleted] = 0;\n"
    elif t.tclass == "Reference":
        body = f"CREATE VIEW {qn} AS\nSELECT {cols_list(vis)}\nFROM {t.qn}\nWHERE [IsActive] = 1;\n"
    else:  # AppendOnly
        body = f"CREATE VIEW {qn} AS\nSELECT {cols_list(vis)}\nFROM {t.qn};\n"
    return HEADER + body + grant(qn)


def view_history(t):
    vis = [c for c in t.columns if not c.hidden]
    qn = f"[{t.schema}].[v{t.name}History]"
    body = (f"CREATE VIEW {qn} AS\n"
            f"-- every row version, including deleted and superseded; both clocks visible\n"
            f"SELECT {cols_list(vis)}, [SysStart], [SysEnd]\n"
            f"FROM {t.qn} FOR SYSTEM_TIME ALL;\n")
    return HEADER + body + grant(qn)


def func_asof(t):
    vis = [c for c in t.columns if not c.hidden]
    qn = f"[{t.schema}].[f{t.name}AsOf]"
    body = (f"CREATE FUNCTION {qn} (@validAt DATETIMEOFFSET(7), @believedAtUtc DATETIME2(7))\n"
            f"RETURNS TABLE AS RETURN\n"
            f"-- bi-temporal as-of (decision 69): rows valid at @validAt as the database believed them at\n"
            f"-- @believedAtUtc (system time, UTC). A row deleted after @believedAtUtc is still returned.\n"
            f"SELECT {cols_list(vis)}, [SysStart], [SysEnd]\nFROM (\n"
            f"    SELECT {cols_list(vis)}, [SysStart], [SysEnd],\n"
            f"           ROW_NUMBER() OVER (PARTITION BY [EntityId] ORDER BY [ValidFrom] DESC, [RowSeq] DESC) AS _rn\n"
            f"    FROM {t.qn} FOR SYSTEM_TIME AS OF @believedAtUtc\n"
            f"    WHERE [IsDeleted] = 0\n"
            f"      AND [ValidFrom] <= @validAt\n"
            f"      AND ([ValidTo] IS NULL OR [ValidTo] > @validAt)\n"
            f") x WHERE x._rn = 1;\n")
    return HEADER + body + grant(qn)


def param_decl(c, default=True):
    if default and c.nullable:
        d = " = NULL"
    elif default and c.default is not None:
        d = f" = {c.default}"
    else:
        d = ""
    return f"    @{c.name} {c.type}{d}"


def poly_pairs(t):
    """(kindCol, entityCol) pairs such as SubjectKind/SubjectEntityId."""
    names = {c.name for c in t.columns}
    pairs = []
    for c in t.columns:
        m = re.fullmatch(r"(\w+?)Kind", c.name)
        if m and f"{m.group(1)}EntityId" in names:
            pairs.append((c.name, f"{m.group(1)}EntityId"))
    return pairs


def poly_checks(t, indent="    "):
    out = []
    for k, e in poly_pairs(t):
        out.append(f"{indent}IF @{e} IS NOT NULL AND [meta].[fEntityExists](@{k}, @{e}) = 0\n"
                   f"{indent}    THROW 50101, N'{t.schema}.{t.name}: no {e.replace('EntityId', '')} entity of kind @{k} with that id.', 1;")
    return "\n".join(out) + ("\n" if out else "")


def actor_block():
    return "    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;\n"


def proc_add(t):
    dom = t.domain
    has_vt = t.tclass in ("ValidTime", "BiTemporal")
    qn = f"[{t.schema}].[{t.name}_Add]"
    params = [param_decl(c) for c in dom]
    if has_vt:
        params += ["    @ValidFrom DATETIMEOFFSET(7) = NULL", "    @ValidFromQuality TINYINT = 0"]
    params += ["    @ActorId UNIQUEIDENTIFIER = NULL", "    @MigrationRunId UNIQUEIDENTIFIER = NULL"]
    if t.own_registry:
        params += ["    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT"]
    else:
        params += ["    @EntityId UNIQUEIDENTIFIER"]          # extension / shared identity: caller supplies
    params += ["    @RowId UNIQUEIDENTIFIER = NULL OUTPUT"]
    ins_cols = ["[EntityId]"] + (["[ValidFrom]", "[ValidFromQuality]"] if has_vt else []) + \
               ["[CreatedBy]", "[CreatedAt]", "[ModifiedBy]", "[ModifiedAt]", "[MigrationRunId]"] + [f"[{c.name}]" for c in dom]
    ins_vals = ["@EntityId"] + (["@ValidFrom", "@ValidFromQuality"] if has_vt else []) + \
               ["@ActorId", "@now", "@ActorId", "@now", "@MigrationRunId"] + [f"@{c.name}" for c in dom]
    reg = ""
    if t.own_registry:
        reg = (f"    SET @EntityId = ISNULL(@EntityId, NEWID());\n"
               f"    INSERT [{t.registry[0]}].[{t.registry[1]}] ([EntityId]) VALUES (@EntityId);\n")
    elif t.registry:
        reg = (f"    IF NOT EXISTS (SELECT 1 FROM [{t.registry[0]}].[{t.registry[1]}] WHERE [EntityId] = @EntityId)\n"
               f"        THROW 50102, N'{t.schema}.{t.name}: @EntityId is not a registered {t.registry[1][:-8]}.', 1;\n")
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n    SET XACT_ABORT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n"
            + (f"    SET @ValidFrom = ISNULL(@ValidFrom, @now);\n" if has_vt else "")
            + actor_block() + poly_checks(t)
            + "    BEGIN TRANSACTION;\n" + reg
            + f"    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);\n"
            + f"    INSERT {t.qn} ({', '.join(ins_cols)})\n    OUTPUT inserted.[RowId] INTO @out\n    VALUES ({', '.join(ins_vals)});\n"
            + "    SELECT @RowId = [RowId] FROM @out;\n    COMMIT TRANSACTION;\nEND;\n")
    return HEADER + body


def proc_revise(t):
    dom = t.domain
    qn = f"[{t.schema}].[{t.name}_Revise]"
    params = ["    @EntityId UNIQUEIDENTIFIER"] + [param_decl(c) for c in dom] + \
             ["    @ValidFrom DATETIMEOFFSET(7) = NULL", "    @ValidFromQuality TINYINT = 0",
              "    @ActorId UNIQUEIDENTIFIER = NULL", "    @MigrationRunId UNIQUEIDENTIFIER = NULL", "    @RowId UNIQUEIDENTIFIER = NULL OUTPUT"]
    ins_cols = ["[EntityId]", "[ValidFrom]", "[ValidFromQuality]", "[CreatedBy]", "[CreatedAt]", "[ModifiedBy]", "[ModifiedAt]", "[MigrationRunId]"] + [f"[{c.name}]" for c in dom]
    ins_vals = ["@EntityId", "@ValidFrom", "@ValidFromQuality", "@ActorId", "@now", "@ActorId", "@now", "@MigrationRunId"] + [f"@{c.name}" for c in dom]
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n    SET XACT_ABORT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n    SET @ValidFrom = ISNULL(@ValidFrom, @now);\n"
            + actor_block() + poly_checks(t)
            + f"    IF NOT EXISTS (SELECT 1 FROM {t.qn} WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)\n"
            + f"        THROW 50103, N'{t.schema}.{t.name}: no open row for @EntityId to revise.', 1;\n"
            + "    BEGIN TRANSACTION;\n"
            + f"    -- close the prior fact (decision 71: end of validity is a valid-time update)\n"
            + f"    UPDATE {t.qn} SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now\n"
            + f"    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;\n"
            + f"    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);\n"
            + f"    INSERT {t.qn} ({', '.join(ins_cols)})\n    OUTPUT inserted.[RowId] INTO @out\n    VALUES ({', '.join(ins_vals)});\n"
            + "    SELECT @RowId = [RowId] FROM @out;\n    COMMIT TRANSACTION;\nEND;\n")
    return HEADER + body


def proc_update(t):
    if t.tclass == "Subclass":
        key = t.pk[0]
        dom = [c for c in t.domain if c.name != key]
        keyparam, where = f"    @{key} UNIQUEIDENTIFIER", f"[{key}] = @{key}"
    else:
        dom = t.domain
        keyparam, where = "    @RowId UNIQUEIDENTIFIER", "[RowId] = @RowId"
    qn = f"[{t.schema}].[{t.name}_Update]"
    params = [keyparam] + [param_decl(c) for c in dom] + ["    @ActorId UNIQUEIDENTIFIER = NULL"]
    sets = ", ".join(f"[{c.name}] = @{c.name}" for c in dom)
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n    SET XACT_ABORT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block() + poly_checks(t)
            + f"    UPDATE {t.qn} SET {sets}, [ModifiedBy] = @ActorId, [ModifiedAt] = @now\n"
            + f"    WHERE {where} AND [IsDeleted] = 0;\n"
            + f"    IF @@ROWCOUNT = 0 THROW 50104, N'{t.schema}.{t.name}: no live row with that key.', 1;\nEND;\n")
    return HEADER + body


def proc_subclass_add(t):
    """Subclass (keyed by the parent's RowId): the caller supplies the key; the FK proves the parent exists."""
    key = t.pk[0]
    dom = [c for c in t.domain if c.name != key]
    qn = f"[{t.schema}].[{t.name}_Add]"
    params = [f"    @{key} UNIQUEIDENTIFIER"] + [param_decl(c) for c in dom] + ["    @ActorId UNIQUEIDENTIFIER = NULL", "    @MigrationRunId UNIQUEIDENTIFIER = NULL"]
    ins_cols = [f"[{key}]", "[CreatedBy]", "[CreatedAt]", "[ModifiedBy]", "[ModifiedAt]", "[MigrationRunId]"] + [f"[{c.name}]" for c in dom]
    ins_vals = [f"@{key}", "@ActorId", "@now", "@ActorId", "@now", "@MigrationRunId"] + [f"@{c.name}" for c in dom]
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n    SET XACT_ABORT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block() + poly_checks(t)
            + f"    INSERT {t.qn} ({', '.join(ins_cols)})\n    VALUES ({', '.join(ins_vals)});\nEND;\n")
    return HEADER + body


def proc_subclass_softdelete(t):
    key = t.pk[0]
    qn = f"[{t.schema}].[{t.name}_SoftDelete]"
    body = (f"CREATE PROCEDURE {qn}\n    @{key} UNIQUEIDENTIFIER,\n    @ActorId UNIQUEIDENTIFIER = NULL\nAS\nBEGIN\n"
            f"    SET NOCOUNT ON;\n    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block()
            + f"    UPDATE {t.qn} SET [IsDeleted] = 1, [DeletedBy] = @ActorId, [DeletedAt] = @now, [ModifiedBy] = @ActorId, [ModifiedAt] = @now\n"
            + f"    WHERE [{key}] = @{key} AND [IsDeleted] = 0;\n"
            + f"    IF @@ROWCOUNT = 0 THROW 50105, N'{t.schema}.{t.name}: nothing live to delete for that key.', 1;\nEND;\n")
    return HEADER + body


def proc_softdelete(t):
    qn = f"[{t.schema}].[{t.name}_SoftDelete]"
    body = (f"CREATE PROCEDURE {qn}\n    @EntityId UNIQUEIDENTIFIER,\n    @ActorId UNIQUEIDENTIFIER = NULL\nAS\nBEGIN\n"
            f"    SET NOCOUNT ON;\n    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block()
            + f"    -- decision 71: soft delete closes belief only; ValidTo is untouched\n"
            + f"    UPDATE {t.qn} SET [IsDeleted] = 1, [DeletedBy] = @ActorId, [DeletedAt] = @now, [ModifiedBy] = @ActorId, [ModifiedAt] = @now\n"
            + f"    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0;\n"
            + f"    IF @@ROWCOUNT = 0 THROW 50105, N'{t.schema}.{t.name}: nothing live to delete for @EntityId.', 1;\nEND;\n")
    return HEADER + body


def proc_upsert(t):
    dom = t.domain                                  # includes the natural key
    key = [c for c in dom if c.is_pk]
    rest = [c for c in dom if not c.is_pk]
    qn = f"[{t.schema}].[{t.name}_Upsert]"
    # a Reference row's EntityId (an identity a record can cite, e.g. personnel.TrainingModule) is server-assigned:
    # optional on insert (NEWID() when not given), never changed by an update
    ident = [c for c in rest if c.name == "EntityId" and c.type.upper() == "UNIQUEIDENTIFIER"]
    params = ([param_decl(c, default=False) for c in key]
              + [(f"    @{c.name} {c.type} = NULL" if c in ident else param_decl(c)) for c in rest]
              + ["    @ActorId UNIQUEIDENTIFIER = NULL", "    @MigrationRunId UNIQUEIDENTIFIER = NULL"])
    on = " AND ".join(f"t.[{c.name}] = @{c.name}" for c in key)
    sets = ", ".join(f"[{c.name}] = @{c.name}" for c in rest if c not in ident)
    ins_cols = [f"[{c.name}]" for c in dom] + ["[CreatedBy]", "[CreatedAt]", "[ModifiedBy]", "[ModifiedAt]", "[MigrationRunId]"]
    ins_vals = [(f"ISNULL(@{c.name}, NEWID())" if c in ident else f"@{c.name}") for c in dom] + ["@ActorId", "@now", "@ActorId", "@now", "@MigrationRunId"]
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block()
            + f"    IF EXISTS (SELECT 1 FROM {t.qn} t WHERE {on})\n"
            + (f"        UPDATE t SET {sets}, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM {t.qn} t WHERE {on};\n" if rest
               else f"        UPDATE t SET [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM {t.qn} t WHERE {on};\n")
            + f"    ELSE\n        INSERT {t.qn} ({', '.join(ins_cols)}) VALUES ({', '.join(ins_vals)});\nEND;\n")
    return HEADER + body


def proc_deactivate(t):
    key = [c for c in t.domain if c.is_pk]
    qn = f"[{t.schema}].[{t.name}_Deactivate]"
    params = [param_decl(c, default=False) for c in key] + ["    @ActorId UNIQUEIDENTIFIER = NULL"]
    on = " AND ".join(f"[{c.name}] = @{c.name}" for c in key)
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n"
            f"    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();\n" + actor_block()
            + f"    UPDATE {t.qn} SET [IsActive] = 0, [ModifiedBy] = @ActorId, [ModifiedAt] = @now WHERE {on} AND [IsActive] = 1;\n"
            + f"    IF @@ROWCOUNT = 0 THROW 50106, N'{t.schema}.{t.name}: no active row with that key.', 1;\nEND;\n")
    return HEADER + body


def proc_append(t):
    cols = [c for c in t.columns if not c.identity and not c.computed and not c.hidden]
    idc = next((c for c in t.columns if c.identity), None)
    keyc = next((c for c in t.columns if c.is_pk and not c.identity), None)
    qn = f"[{t.schema}].[{t.name}_Append]"
    params = [param_decl(c) for c in cols]
    out = None
    if idc:
        params.append(f"    @{idc.name} {idc.type} = NULL OUTPUT"); out = idc
    elif keyc and keyc.type == "UNIQUEIDENTIFIER":
        params = [p for p in params if not p.strip().startswith(f"@{keyc.name} ")]
        params.append(f"    @{keyc.name} UNIQUEIDENTIFIER = NULL OUTPUT"); out = keyc
    has_actor = any(c.name == "ActorId" and not c.is_pk for c in cols)   # a key named ActorId (personnel.Actor) is not the session actor
    body = (f"CREATE PROCEDURE {qn}\n" + ",\n".join(params) + "\nAS\nBEGIN\n    SET NOCOUNT ON;\n"
            + ("    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;\n" if has_actor else "")
            + poly_checks(t))
    ins = cols
    if out is not None and out is keyc:              # GUID key: supplied by the caller or generated here
        body += f"    SET @{keyc.name} = ISNULL(@{keyc.name}, NEWID());\n"
    body += (f"    INSERT {t.qn} ({', '.join(f'[{c.name}]' for c in ins)})\n"
             f"    VALUES ({', '.join(f'@{c.name}' for c in ins)});\n")
    if out is not None and out is idc:
        body += f"    SET @{idc.name} = SCOPE_IDENTITY();\n"
    body += "END;\n"
    return HEADER + body


def func_entity_exists(kinds, existing):
    lines = ["CREATE FUNCTION [meta].[fEntityExists] (@kind NVARCHAR(40), @entityId UNIQUEIDENTIFIER)",
             "RETURNS BIT AS BEGIN",
             "    -- generated from ref.SubjectKind; kinds whose table is not yet deployed return 0",
             "    IF @entityId IS NULL RETURN 0;",
             "    RETURN CASE @kind"]
    for k, s, tb, keycol in kinds:
        if s is None:
            lines.append(f"        WHEN N'{k}' THEN 1")
        elif (s, tb) in existing:
            lines.append(f"        WHEN N'{k}' THEN CASE WHEN EXISTS (SELECT 1 FROM [{s}].[{tb}] WHERE [{keycol}] = @entityId) THEN 1 ELSE 0 END")
        else:
            lines.append(f"        WHEN N'{k}' THEN 0   -- {s}.{tb} not deployed")
    if not kinds:   # bootstrap (tables-only) publish: ref.SubjectKind is not seeded yet; a CASE needs at least one WHEN
        lines.append("        WHEN N'Platform' THEN 1")
    lines += ["        ELSE 0 END;", "END;", ""]
    return HEADER + "\n".join(lines)


def view_alternate_key(tables):
    aks = [t for t in tables.values() if t.name == "AlternateKey"]
    if not aks:
        return None
    parts = []
    for t in sorted(aks, key=lambda x: x.schema):
        parts.append(f"SELECT N'{t.schema}' AS [SchemaName], [SubjectEntityId], [KeyKindCode], [KeyValue], [ScopeEntityId], [IsPrimaryLabel], [ValidFrom], [RowId]\n"
                     f"FROM [{t.schema}].[vAlternateKey]")
    body = "CREATE VIEW [core].[vAlternateKey] AS\n-- platform-wide search over every <schema>.AlternateKey (§0.4)\n" + "\nUNION ALL\n".join(parts) + ";\n"
    return HEADER + body + grant("[core].[vAlternateKey]")


# ----------------------------------------------------------------------------- driver

def generate(tables, kinds, existing):
    files = {}
    for t in tables.values():
        if t.tclass == "Registry":
            continue
        vdir, pdir = f"{t.schema}/Views", f"{t.schema}/Procedures"
        files[f"{vdir}/v{t.name}.sql"] = view_current(t)
        if t.tclass not in ("AppendOnly", "FileTable"):
            files[f"{vdir}/v{t.name}History.sql"] = view_history(t)
        if t.tclass == "BiTemporal":
            files[f"{t.schema}/Functions/f{t.name}AsOf.sql"] = func_asof(t)
        if t.tclass in ("ValidTime", "BiTemporal"):
            files[f"{pdir}/{t.name}_Add.sql"] = proc_add(t)
            files[f"{pdir}/{t.name}_Revise.sql"] = proc_revise(t)
            files[f"{pdir}/{t.name}_SoftDelete.sql"] = proc_softdelete(t)
        elif t.tclass == "Versioned":
            files[f"{pdir}/{t.name}_Add.sql"] = proc_add(t)
            files[f"{pdir}/{t.name}_Update.sql"] = proc_update(t)
            files[f"{pdir}/{t.name}_SoftDelete.sql"] = proc_softdelete(t)
        elif t.tclass == "Subclass":
            files[f"{pdir}/{t.name}_Add.sql"] = proc_subclass_add(t)
            files[f"{pdir}/{t.name}_Update.sql"] = proc_update(t)
            files[f"{pdir}/{t.name}_SoftDelete.sql"] = proc_subclass_softdelete(t)
        elif t.tclass == "FileTable":
            pass                                  # pass-through view only; files arrive through FILESTREAM
        elif t.tclass == "Reference":
            files[f"{pdir}/{t.name}_Upsert.sql"] = proc_upsert(t)
            files[f"{pdir}/{t.name}_Deactivate.sql"] = proc_deactivate(t)
        elif t.tclass == "AppendOnly":
            files[f"{pdir}/{t.name}_Append.sql"] = proc_append(t)
    files["meta/Functions/fEntityExists.sql"] = func_entity_exists(kinds, existing)
    ak = view_alternate_key(tables)
    if ak:
        files["core/Views/vAlternateKey.sql"] = ak
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--server", default="10.10.70.25")
    ap.add_argument("--database", default="PnCPlatform_V2_DEV")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    cur = connect(a.server, a.database).cursor()
    tables, kinds, existing = load(cur)
    files = generate(tables, kinds, existing)

    # existing generated files not produced this time are stale (a table was removed/renamed)
    stale = []
    for root, _, names in os.walk(DDL):
        for n in names:
            p = os.path.join(root, n)
            rel = os.path.relpath(p, DDL).replace("\\", "/")
            if n.endswith(".sql") and rel not in files and not rel.startswith(("PostDeploy/", "tools/", "bin/", "obj/")):
                try:
                    if open(p, encoding="utf-8").readline() == HEADER:
                        stale.append(rel)
                except OSError:
                    pass
    changed = []
    for rel, content in files.items():
        p = os.path.join(DDL, rel)
        old = open(p, encoding="utf-8").read() if os.path.exists(p) else None
        if old != content:
            changed.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                with open(p, "w", encoding="utf-8", newline="\n") as f:
                    f.write(content)
    if not a.check:
        for rel in stale:
            os.remove(os.path.join(DDL, rel))
    print(f"{len(files)} generated objects; {len(changed)} {'would change' if a.check else 'written'}; {len(stale)} stale {'found' if a.check else 'removed'}")
    for rel in changed[:40]:
        print("  ", rel)
    if a.check and (changed or stale):
        sys.exit(1)


if __name__ == "__main__":
    main()
