-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vConnectionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [FromKind], [FromEntityId], [ToKind], [ToEntityId], [RealisationCode], [CarrierAssetEntityId], [DesignStatus], [VerifiedByRecordEntityId], [WorkRequestEntityId], [DrawingKey], [Notes], [SysStart], [SysEnd]
FROM [connection].[Connection] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vConnectionHistory] TO [app_execute];
GO
