-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vControlBlockHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [LogicalDeviceEntityId], [ControlBlockKind], [CbName], [AppId], [ConfRev], [DatasetEntityId], [MulticastMac], [VlanId], [VlanPriority], [SysStart], [SysEnd]
FROM [connection].[ControlBlock] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vControlBlockHistory] TO [app_execute];
GO
