-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vDataAttributeHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [LogicalNodeEntityId], [DoName], [DaName], [Fc], [DataSource], [SysStart], [SysEnd]
FROM [connection].[DataAttribute] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vDataAttributeHistory] TO [app_execute];
GO
