-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vDatasetMemberHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [DatasetEntityId], [LdInst], [LnClass], [LnInst], [DoName], [DaName], [Fc], [SysStart], [SysEnd]
FROM [connection].[DatasetMember] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vDatasetMemberHistory] TO [app_execute];
GO
