-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vExtRefHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ConfigurationFileRevisionRowId], [IedEntityId], [IntAddr], [LdInst], [LnClass], [LnInst], [DoName], [DaName], [PublisherIedName], [CbName], [DatasetRef], [ConnectionEntityId], [SysStart], [SysEnd]
FROM [connection].[ExtRef] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vExtRefHistory] TO [app_execute];
GO
