-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vNetworkPortHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [MacAddress], [IpAddress], [SubnetMask], [Gateway], [VlanId], [Speed], [IsEnabled], [SysStart], [SysEnd]
FROM [connection].[NetworkPort] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vNetworkPortHistory] TO [app_execute];
GO
