-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [connection].[vSecurityPerimeterMemberHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [PerimeterEntityId], [DeviceEntityId], [Role], [SysStart], [SysEnd]
FROM [connection].[SecurityPerimeterMember] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [connection].[vSecurityPerimeterMemberHistory] TO [app_execute];
GO
