-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[AuditRequest_Add]
    @AuditEntityId UNIQUEIDENTIFIER,
    @RequestReference NVARCHAR(100),
    @RequirementEntityId UNIQUEIDENTIFIER = NULL,
    @SubjectKind NVARCHAR(40) = NULL,
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @RequestedAt DATETIMEOFFSET(7),
    @DueAt DATETIMEOFFSET(7) = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @AnsweredByPackageEntityId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'compliance.AuditRequest: no Subject entity of kind @SubjectKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [compliance].[AuditRequestRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [compliance].[AuditRequest] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [AuditEntityId], [RequestReference], [RequirementEntityId], [SubjectKind], [SubjectEntityId], [RequestedAt], [DueAt], [Description], [AnsweredByPackageEntityId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @AuditEntityId, @RequestReference, @RequirementEntityId, @SubjectKind, @SubjectEntityId, @RequestedAt, @DueAt, @Description, @AnsweredByPackageEntityId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
