-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[EvidencePackage_Update]
    @RowId UNIQUEIDENTIFIER,
    @AuditRequestEntityId UNIQUEIDENTIFIER = NULL,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @StandardVersionRowId UNIQUEIDENTIFIER,
    @PeriodStartAt DATETIMEOFFSET(7),
    @PeriodEndAt DATETIMEOFFSET(7),
    @ValidAsOf DATETIMEOFFSET(7),
    @BelievedAsOf DATETIMEOFFSET(7),
    @PreparedByActorId UNIQUEIDENTIFIER,
    @PreparedAt DATETIMEOFFSET(7),
    @ReviewedByActorId UNIQUEIDENTIFIER = NULL,
    @ReviewedAt DATETIMEOFFSET(7) = NULL,
    @ApprovedByActorId UNIQUEIDENTIFIER = NULL,
    @ApprovedAt DATETIMEOFFSET(7) = NULL,
    @SubmittedAt DATETIMEOFFSET(7) = NULL,
    @SubmittedToEntityEntityId UNIQUEIDENTIFIER = NULL,
    @PackageDocumentEntityId UNIQUEIDENTIFIER = NULL,
    @PackageHash BINARY(32) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'compliance.EvidencePackage: no Subject entity of kind @SubjectKind with that id.', 1;
    UPDATE [compliance].[EvidencePackage] SET [AuditRequestEntityId] = @AuditRequestEntityId, [SubjectKind] = @SubjectKind, [SubjectEntityId] = @SubjectEntityId, [StandardVersionRowId] = @StandardVersionRowId, [PeriodStartAt] = @PeriodStartAt, [PeriodEndAt] = @PeriodEndAt, [ValidAsOf] = @ValidAsOf, [BelievedAsOf] = @BelievedAsOf, [PreparedByActorId] = @PreparedByActorId, [PreparedAt] = @PreparedAt, [ReviewedByActorId] = @ReviewedByActorId, [ReviewedAt] = @ReviewedAt, [ApprovedByActorId] = @ApprovedByActorId, [ApprovedAt] = @ApprovedAt, [SubmittedAt] = @SubmittedAt, [SubmittedToEntityEntityId] = @SubmittedToEntityEntityId, [PackageDocumentEntityId] = @PackageDocumentEntityId, [PackageHash] = @PackageHash, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'compliance.EvidencePackage: no live row with that key.', 1;
END;
