-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[Exception_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @RuleDefinitionVersionRowId UNIQUEIDENTIFIER,
    @ObligationInstanceRowId UNIQUEIDENTIFIER = NULL,
    @ExceptionKind NVARCHAR(30),
    @OpenedAt DATETIMEOFFSET(7),
    @OpenedByActorId UNIQUEIDENTIFIER,
    @ClockDueAt DATETIMEOFFSET(7) = NULL,
    @MitigationPlanDocumentEntityId UNIQUEIDENTIFIER = NULL,
    @ReportedAt DATETIMEOFFSET(7) = NULL,
    @ReportedToEntityEntityId UNIQUEIDENTIFIER = NULL,
    @ReportReference NVARCHAR(100) = NULL,
    @ClosedAt DATETIMEOFFSET(7) = NULL,
    @ClosedByActorId UNIQUEIDENTIFIER = NULL,
    @ClosureBasis NVARCHAR(400) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'compliance.Exception: no Subject entity of kind @SubjectKind with that id.', 1;
    IF NOT EXISTS (SELECT 1 FROM [compliance].[Exception] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'compliance.Exception: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [compliance].[Exception] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [compliance].[Exception] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [RuleDefinitionVersionRowId], [ObligationInstanceRowId], [ExceptionKind], [OpenedAt], [OpenedByActorId], [ClockDueAt], [MitigationPlanDocumentEntityId], [ReportedAt], [ReportedToEntityEntityId], [ReportReference], [ClosedAt], [ClosedByActorId], [ClosureBasis])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SubjectKind, @SubjectEntityId, @RuleDefinitionVersionRowId, @ObligationInstanceRowId, @ExceptionKind, @OpenedAt, @OpenedByActorId, @ClockDueAt, @MitigationPlanDocumentEntityId, @ReportedAt, @ReportedToEntityEntityId, @ReportReference, @ClosedAt, @ClosedByActorId, @ClosureBasis);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
