-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[ObligationInstanceFact_Append]
    @ObligationInstanceRowId UNIQUEIDENTIFIER,
    @FactName NVARCHAR(200),
    @SourceRowId UNIQUEIDENTIFIER = NULL,
    @ValueAsRead NVARCHAR(400) = NULL,
    @ObligationInstanceFactId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [compliance].[ObligationInstanceFact] ([ObligationInstanceRowId], [FactName], [SourceRowId], [ValueAsRead])
    VALUES (@ObligationInstanceRowId, @FactName, @SourceRowId, @ValueAsRead);
    SET @ObligationInstanceFactId = SCOPE_IDENTITY();
END;
