-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[ObligationInstance_Add]
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER = NULL,
    @RuleDefinitionVersionRowId UNIQUEIDENTIFIER,
    @RequirementEntityId UNIQUEIDENTIFIER,
    @ElectedStandardVersionRowId UNIQUEIDENTIFIER = NULL,
    @PeriodStartAt DATETIMEOFFSET(7),
    @PeriodEndAt DATETIMEOFFSET(7) = NULL,
    @Status NVARCHAR(20),
    @RaisedWorkRequestEntityId UNIQUEIDENTIFIER = NULL,
    @EvaluationRunId UNIQUEIDENTIFIER,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF @SubjectEntityId IS NOT NULL AND [meta].[fEntityExists](@SubjectKind, @SubjectEntityId) = 0
        THROW 50101, N'compliance.ObligationInstance: no Subject entity of kind @SubjectKind with that id.', 1;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [compliance].[ObligationInstanceRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [compliance].[ObligationInstance] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [SubjectKind], [SubjectEntityId], [RuleDefinitionVersionRowId], [RequirementEntityId], [ElectedStandardVersionRowId], [PeriodStartAt], [PeriodEndAt], [Status], [RaisedWorkRequestEntityId], [EvaluationRunId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @SubjectKind, @SubjectEntityId, @RuleDefinitionVersionRowId, @RequirementEntityId, @ElectedStandardVersionRowId, @PeriodStartAt, @PeriodEndAt, @Status, @RaisedWorkRequestEntityId, @EvaluationRunId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
