-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[Requirement_Revise]
    @EntityId UNIQUEIDENTIFIER,
    @StandardVersionRowId UNIQUEIDENTIFIER,
    @RequirementNumber NVARCHAR(40),
    @SubRequirement NVARCHAR(40) = NULL,
    @Title NVARCHAR(200) = NULL,
    @Summary NVARCHAR(MAX) = NULL,
    @EvidenceGuidance NVARCHAR(MAX) = NULL,
    @SubjectKinds NVARCHAR(400) = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [compliance].[Requirement] WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL)
        THROW 50103, N'compliance.Requirement: no open row for @EntityId to revise.', 1;
    BEGIN TRANSACTION;
    -- close the prior fact (decision 71: end of validity is a valid-time update)
    UPDATE [compliance].[Requirement] SET [ValidTo] = @ValidFrom, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [EntityId] = @EntityId AND [IsDeleted] = 0 AND [ValidTo] IS NULL AND [ValidFrom] <= @ValidFrom;
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [compliance].[Requirement] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [StandardVersionRowId], [RequirementNumber], [SubRequirement], [Title], [Summary], [EvidenceGuidance], [SubjectKinds])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @StandardVersionRowId, @RequirementNumber, @SubRequirement, @Title, @Summary, @EvidenceGuidance, @SubjectKinds);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
