-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[Standard_Upsert]
    @StandardCode NVARCHAR(40),
    @IssuingEntityEntityId UNIQUEIDENTIFIER,
    @Family NVARCHAR(40) = NULL,
    @Subject NVARCHAR(200) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [compliance].[Standard] t WHERE t.[StandardCode] = @StandardCode)
        UPDATE t SET [IssuingEntityEntityId] = @IssuingEntityEntityId, [Family] = @Family, [Subject] = @Subject, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [compliance].[Standard] t WHERE t.[StandardCode] = @StandardCode;
    ELSE
        INSERT [compliance].[Standard] ([StandardCode], [IssuingEntityEntityId], [Family], [Subject], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@StandardCode, @IssuingEntityEntityId, @Family, @Subject, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
