-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[StandardVersion_Add]
    @StandardCode NVARCHAR(40),
    @VersionLabel NVARCHAR(40),
    @EffectiveFrom DATETIMEOFFSET(7) = NULL,
    @EffectiveTo DATETIMEOFFSET(7) = NULL,
    @OverlapUntil DATETIMEOFFSET(7) = NULL,
    @TextDocumentEntityId UNIQUEIDENTIFIER = NULL,
    @TextReference NVARCHAR(400) = NULL,
    @SupersedesVersionRowId UNIQUEIDENTIFIER = NULL,
    @ValidFrom DATETIMEOFFSET(7) = NULL,
    @ValidFromQuality TINYINT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    SET @ValidFrom = ISNULL(@ValidFrom, @now);
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [compliance].[StandardVersionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [compliance].[StandardVersion] ([EntityId], [ValidFrom], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [StandardCode], [VersionLabel], [EffectiveFrom], [EffectiveTo], [OverlapUntil], [TextDocumentEntityId], [TextReference], [SupersedesVersionRowId])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ValidFrom, @ValidFromQuality, @ActorId, @now, @ActorId, @now, @MigrationRunId, @StandardCode, @VersionLabel, @EffectiveFrom, @EffectiveTo, @OverlapUntil, @TextDocumentEntityId, @TextReference, @SupersedesVersionRowId);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
