-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [compliance].[SubjectVerdict_Deactivate]
    @SubjectKind NVARCHAR(40),
    @SubjectEntityId UNIQUEIDENTIFIER,
    @VerdictKind NVARCHAR(20),
    @DefinitionEntityId UNIQUEIDENTIFIER,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [compliance].[SubjectVerdict] SET [IsActive] = 0, [ModifiedBy] = @ActorId, [ModifiedAt] = @now WHERE [SubjectKind] = @SubjectKind AND [SubjectEntityId] = @SubjectEntityId AND [VerdictKind] = @VerdictKind AND [DefinitionEntityId] = @DefinitionEntityId AND [IsActive] = 1;
    IF @@ROWCOUNT = 0 THROW 50106, N'compliance.SubjectVerdict: no active row with that key.', 1;
END;
