-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[DefinitionVersion_Add]
    @DefinitionEntityId UNIQUEIDENTIFIER,
    @VersionNumber INT,
    @Status NVARCHAR(20),
    @EffectiveFrom DATETIMEOFFSET(7) = NULL,
    @EffectiveTo DATETIMEOFFSET(7) = NULL,
    @ApprovedBy UNIQUEIDENTIFIER = NULL,
    @ApprovedAt DATETIMEOFFSET(7) = NULL,
    @ChangeNote NVARCHAR(MAX) = NULL,
    @TestEvidenceRecordId UNIQUEIDENTIFIER = NULL,
    @PayloadText NVARCHAR(MAX) = NULL,
    @PayloadHash BINARY(32) = NULL,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [config].[DefinitionVersionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [config].[DefinitionVersion] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionEntityId], [VersionNumber], [Status], [EffectiveFrom], [EffectiveTo], [ApprovedBy], [ApprovedAt], [ChangeNote], [TestEvidenceRecordId], [PayloadText], [PayloadHash])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionEntityId, @VersionNumber, @Status, @EffectiveFrom, @EffectiveTo, @ApprovedBy, @ApprovedAt, @ChangeNote, @TestEvidenceRecordId, @PayloadText, @PayloadHash);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
