-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[RoleViewItem_Upsert]
    @RoleCode NVARCHAR(40),
    @ScreenKey NVARCHAR(60),
    @ItemKey NVARCHAR(60),
    @IsShown BIT,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [config].[RoleViewItem] t WHERE t.[RoleCode] = @RoleCode AND t.[ScreenKey] = @ScreenKey AND t.[ItemKey] = @ItemKey)
        UPDATE t SET [IsShown] = @IsShown, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [config].[RoleViewItem] t WHERE t.[RoleCode] = @RoleCode AND t.[ScreenKey] = @ScreenKey AND t.[ItemKey] = @ItemKey;
    ELSE
        INSERT [config].[RoleViewItem] ([RoleCode], [ScreenKey], [ItemKey], [IsShown], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@RoleCode, @ScreenKey, @ItemKey, @IsShown, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
