-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[SettingDefinition_Add]
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @SettingCode NVARCHAR(100),
    @Name NVARCHAR(200),
    @Category NVARCHAR(100) = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @DataType NVARCHAR(20),
    @UnitCode NVARCHAR(20) = NULL,
    @Base NVARCHAR(20) = NULL,
    @MinValue DECIMAL(28,10) = NULL,
    @MaxValue DECIMAL(28,10) = NULL,
    @DefaultValue NVARCHAR(400) = NULL,
    @EnumerationDefinitionRowId UNIQUEIDENTIFIER = NULL,
    @IsGroupSpecific BIT = 0,
    @AnsiCode NVARCHAR(10) = NULL,
    @IsCatalogueFact BIT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [config].[SettingDefinitionRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [config].[SettingDefinition] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionVersionRowId], [SettingCode], [Name], [Category], [Description], [DataType], [UnitCode], [Base], [MinValue], [MaxValue], [DefaultValue], [EnumerationDefinitionRowId], [IsGroupSpecific], [AnsiCode], [IsCatalogueFact])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionVersionRowId, @SettingCode, @Name, @Category, @Description, @DataType, @UnitCode, @Base, @MinValue, @MaxValue, @DefaultValue, @EnumerationDefinitionRowId, @IsGroupSpecific, @AnsiCode, @IsCatalogueFact);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
