-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[StandardSettingEntry_Update]
    @RowId UNIQUEIDENTIFIER,
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @SettingCode NVARCHAR(100),
    @ExpectedValue NVARCHAR(400),
    @Tolerance NVARCHAR(100) = NULL,
    @Basis NVARCHAR(400) = NULL,
    @Category NVARCHAR(100) = NULL,
    @DisplayOrder INT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [config].[StandardSettingEntry] SET [DefinitionVersionRowId] = @DefinitionVersionRowId, [SettingCode] = @SettingCode, [ExpectedValue] = @ExpectedValue, [Tolerance] = @Tolerance, [Basis] = @Basis, [Category] = @Category, [DisplayOrder] = @DisplayOrder, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'config.StandardSettingEntry: no live row with that key.', 1;
END;
