-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[TransformMapping_Add]
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @Direction NVARCHAR(20),
    @SourcePath NVARCHAR(400),
    @TargetKind NVARCHAR(40),
    @TargetKey NVARCHAR(100),
    @ConversionExpression NVARCHAR(MAX) = NULL,
    @IsRequired BIT = 0,
    @DefaultValue NVARCHAR(400) = NULL,
    @Sequence INT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL,
    @EntityId UNIQUEIDENTIFIER = NULL OUTPUT,
    @RowId UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    BEGIN TRANSACTION;
    SET @EntityId = ISNULL(@EntityId, NEWID());
    INSERT [config].[TransformMappingRegistry] ([EntityId]) VALUES (@EntityId);
    DECLARE @out TABLE ([RowId] UNIQUEIDENTIFIER);
    INSERT [config].[TransformMapping] ([EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId], [DefinitionVersionRowId], [Direction], [SourcePath], [TargetKind], [TargetKey], [ConversionExpression], [IsRequired], [DefaultValue], [Sequence])
    OUTPUT inserted.[RowId] INTO @out
    VALUES (@EntityId, @ActorId, @now, @ActorId, @now, @MigrationRunId, @DefinitionVersionRowId, @Direction, @SourcePath, @TargetKind, @TargetKey, @ConversionExpression, @IsRequired, @DefaultValue, @Sequence);
    SELECT @RowId = [RowId] FROM @out;
    COMMIT TRANSACTION;
END;
