-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[TransformMapping_Update]
    @RowId UNIQUEIDENTIFIER,
    @DefinitionVersionRowId UNIQUEIDENTIFIER,
    @Direction NVARCHAR(20),
    @SourcePath NVARCHAR(400),
    @TargetKind NVARCHAR(40),
    @TargetKey NVARCHAR(100),
    @ConversionExpression NVARCHAR(MAX) = NULL,
    @IsRequired BIT = 0,
    @DefaultValue NVARCHAR(400) = NULL,
    @Sequence INT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    UPDATE [config].[TransformMapping] SET [DefinitionVersionRowId] = @DefinitionVersionRowId, [Direction] = @Direction, [SourcePath] = @SourcePath, [TargetKind] = @TargetKind, [TargetKey] = @TargetKey, [ConversionExpression] = @ConversionExpression, [IsRequired] = @IsRequired, [DefaultValue] = @DefaultValue, [Sequence] = @Sequence, [ModifiedBy] = @ActorId, [ModifiedAt] = @now
    WHERE [RowId] = @RowId AND [IsDeleted] = 0;
    IF @@ROWCOUNT = 0 THROW 50104, N'config.TransformMapping: no live row with that key.', 1;
END;
