-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [config].[ViewItem_Upsert]
    @ScreenKey NVARCHAR(60),
    @ItemKey NVARCHAR(60),
    @Name NVARCHAR(100),
    @Description NVARCHAR(400) = NULL,
    @ItemKind NVARCHAR(20) = N'Tab',
    @DisplayOrder INT = 0,
    @ShownByDefault BIT = 1,
    @IsAlways BIT = 0,
    @ActorId UNIQUEIDENTIFIER = NULL,
    @MigrationRunId UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
    IF @ActorId IS NULL EXEC [personnel].[ResolveActor] @ActorId = @ActorId OUTPUT;
    IF EXISTS (SELECT 1 FROM [config].[ViewItem] t WHERE t.[ScreenKey] = @ScreenKey AND t.[ItemKey] = @ItemKey)
        UPDATE t SET [Name] = @Name, [Description] = @Description, [ItemKind] = @ItemKind, [DisplayOrder] = @DisplayOrder, [ShownByDefault] = @ShownByDefault, [IsAlways] = @IsAlways, [IsActive] = 1, [ModifiedBy] = @ActorId, [ModifiedAt] = @now FROM [config].[ViewItem] t WHERE t.[ScreenKey] = @ScreenKey AND t.[ItemKey] = @ItemKey;
    ELSE
        INSERT [config].[ViewItem] ([ScreenKey], [ItemKey], [Name], [Description], [ItemKind], [DisplayOrder], [ShownByDefault], [IsAlways], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [MigrationRunId]) VALUES (@ScreenKey, @ItemKey, @Name, @Description, @ItemKind, @DisplayOrder, @ShownByDefault, @IsAlways, @ActorId, @now, @ActorId, @now, @MigrationRunId);
END;
