-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE PROCEDURE [platform].[Deployment_Append]
    @ReleaseId BIGINT,
    @Environment NVARCHAR(10),
    @DatabaseName SYSNAME,
    @DeployedAt DATETIMEOFFSET(7),
    @DeployedByActorId UNIQUEIDENTIFIER,
    @Outcome NVARCHAR(20),
    @ChecklistRecordEntityId UNIQUEIDENTIFIER = NULL,
    @SmokeChecks INT = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @DeploymentId BIGINT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT [platform].[Deployment] ([ReleaseId], [Environment], [DatabaseName], [DeployedAt], [DeployedByActorId], [Outcome], [ChecklistRecordEntityId], [SmokeChecks], [Notes])
    VALUES (@ReleaseId, @Environment, @DatabaseName, @DeployedAt, @DeployedByActorId, @Outcome, @ChecklistRecordEntityId, @SmokeChecks, @Notes);
    SET @DeploymentId = SCOPE_IDENTITY();
END;
