-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [location].[vNodeFunctionHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [NodeEntityId], [FunctionLabel], [CascadeName], [SchemeEntityId], [SysStart], [SysEnd]
FROM [location].[NodeFunction] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [location].[vNodeFunctionHistory] TO [app_execute];
GO
