-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [location].[vSegmentHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [ValidFrom], [ValidTo], [ValidFromQuality], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [FromAdjacencyRowId], [ToAdjacencyRowId], [Length], [SysStart], [SysEnd]
FROM [location].[Segment] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [location].[vSegmentHistory] TO [app_execute];
GO
