-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vHoldInstance] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [BlockInstanceEntityId], [Reason], [HeldAt], [HeldByActorId], [ReleasedAt], [ReleasedByActorId], [ReleaseBasis]
FROM [process].[HoldInstance]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [process].[vHoldInstance] TO [app_execute];
GO
