-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vInstanceVersionSet] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ProcedureInstanceEntityId], [CalleeKey], [DefinitionVersionRowId]
FROM [process].[InstanceVersionSet]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [process].[vInstanceVersionSet] TO [app_execute];
GO
