-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vProcedureFactUseHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [BlockPath], [FactName], [SysStart], [SysEnd]
FROM [process].[ProcedureFactUse] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [process].[vProcedureFactUseHistory] TO [app_execute];
GO
