-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vProcedureStepRole] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [ProcedureStepRowId], [RoleCode], [RequiresAst]
FROM [process].[ProcedureStepRole]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [process].[vProcedureStepRole] TO [app_execute];
GO
