-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vStepInstance] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [BlockInstanceEntityId], [StepId], [State], [AssignedRoleCode], [ClaimedByActorId], [ClaimedAt], [ClaimExpiresAt], [Draft], [DraftModifiedAt], [CapturedAt], [CapturedByActorId], [CaptureSource], [CaptureTimeQuality], [CommittedRecordEntityId], [CommittedByActorId], [WitnessedByActorId], [AcceptedIntoPlatformByActorId], [CommittedAt], [Outcome], [DeviationFindingEntityId], [HeldReason]
FROM [process].[StepInstance]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [process].[vStepInstance] TO [app_execute];
GO
