-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [process].[vStepInstanceHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [BlockInstanceEntityId], [StepId], [State], [AssignedRoleCode], [ClaimedByActorId], [ClaimedAt], [ClaimExpiresAt], [Draft], [DraftModifiedAt], [CapturedAt], [CapturedByActorId], [CaptureSource], [CaptureTimeQuality], [CommittedRecordEntityId], [CommittedByActorId], [WitnessedByActorId], [AcceptedIntoPlatformByActorId], [CommittedAt], [Outcome], [DeviationFindingEntityId], [HeldReason], [SysStart], [SysEnd]
FROM [process].[StepInstance] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [process].[vStepInstanceHistory] TO [app_execute];
GO
