-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vCharacteristicDefinition] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [CharacteristicKey], [Name], [Description], [DataType], [UnitCode], [Base], [IsRequired], [AllowedValuesDefinitionRowId], [ReferenceTargetKind], [ValidationExpression], [DisplayOrder], [DisplayGroup], [IsCatalogueFact]
FROM [config].[CharacteristicDefinition]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [config].[vCharacteristicDefinition] TO [app_execute];
GO
