-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vEnumerationValueHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [ValueCode], [Name], [Description], [DisplayOrder], [SysStart], [SysEnd]
FROM [config].[EnumerationValue] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [config].[vEnumerationValueHistory] TO [app_execute];
GO
