-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vEnumerationValue] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [ValueCode], [Name], [Description], [DisplayOrder]
FROM [config].[EnumerationValue]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [config].[vEnumerationValue] TO [app_execute];
GO
