-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vStandardSettingEntryHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [SettingCode], [ExpectedValue], [Tolerance], [Basis], [Category], [DisplayOrder], [SysStart], [SysEnd]
FROM [config].[StandardSettingEntry] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [config].[vStandardSettingEntryHistory] TO [app_execute];
GO
