-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vStandardSettingEntry] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [SettingCode], [ExpectedValue], [Tolerance], [Basis], [Category], [DisplayOrder]
FROM [config].[StandardSettingEntry]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [config].[vStandardSettingEntry] TO [app_execute];
GO
