-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vTransformMappingHistory] AS
-- every row version, including deleted and superseded; both clocks visible
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [Direction], [SourcePath], [TargetKind], [TargetKey], [ConversionExpression], [IsRequired], [DefaultValue], [Sequence], [SysStart], [SysEnd]
FROM [config].[TransformMapping] FOR SYSTEM_TIME ALL;
GO
GRANT SELECT ON [config].[vTransformMappingHistory] TO [app_execute];
GO
