-- GENERATED by tools/generate.py from the deployed catalog — do not edit; regenerate with: python tools/generate.py
CREATE VIEW [config].[vTransformMapping] AS
SELECT [RowSeq], [RowId], [EntityId], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [IsDeleted], [DeletedBy], [DeletedAt], [MigrationRunId], [DefinitionVersionRowId], [Direction], [SourcePath], [TargetKind], [TargetKey], [ConversionExpression], [IsRequired], [DefaultValue], [Sequence]
FROM [config].[TransformMapping]
WHERE [IsDeleted] = 0;
GO
GRANT SELECT ON [config].[vTransformMapping] TO [app_execute];
GO
